In [1]:
!pip install pyvi

!pip install -q datasets
!pip install -q transformers
!pip install -q tf-models-official

Collecting pyvi
  Downloading pyvi-0.1.1-py2.py3-none-any.whl (8.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 21.5 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from pyvi) (1.2.2)
Collecting sklearn-crfsuite (from pyvi)
  Downloading sklearn_crfsuite-0.3.6-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pyvi) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pyvi) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pyvi) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pyvi) (3.2.0)
Collecting python-crfsuite>=0.8.3 (from sklearn-crfsuite->pyvi)
  Downloading python_crfsuite-0.9.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 29.2 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from sklearn-crfsuite->pyvi) (1.16.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from sklearn-crfsuite->pyvi) (0.9.0)
Requirement already satisfied: tqdm>=2.0 in /usr/local/lib/python3.10/dist-packages (from sklearn-crfsuite->pyvi) (4.66.1)
Installing collected packages: python-crfsuite, sklearn-crfsuite, pyvi
Successfully installed python-crfsuite-0.9.10 pyvi-0.1.1 sklearn-crfsuite-0.3.6
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 11.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 50.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 5.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.2/241.2 kB 27.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 68.8 MB/s eta 0:00:00
  Building wheel for seqeval (setup.py) ... done

In [2]:
!pip install -q emoji
!rm -rf teencode.txt
!wget https://gist.githubusercontent.com/nguyenvanhieuvn/7d9441c10b3c2739499fc5a4d9ea06fb/raw/df939245b3e841b62af115be4dcb3516dadc9fc5/teencode.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 397.5/397.5 kB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 10.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for vncorenlp (setup.py) ... done
Cloning into 'VnCoreNLP'...
remote: Enumerating objects: 259, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 259 (delta 17), reused 14 (delta 2), pack-reused 212
Receiving objects: 100% (259/259), 237.79 MiB | 16.38 MiB/s, done.
Resolving deltas: 100% (93/93), done.
Updating files: 100% (34/34), done.
--2023-12-23 13:49:56--  https://gist.githubusercontent.com/nguyenvanhieuvn/7d9441c10b3c2739499fc5a4d9ea06fb/raw/df939245b3e841b62af115be4dcb3516dadc9fc5/teencode.txt
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5656 (5.5K) [text/plain]
Saving to: ‘teencode.txt’

teencode.txt        100%[===================>]   5.52K  --.-KB/s    in 0s

2023-12-23 13:49:57 (50.5 MB/s) - ‘teencode.txt’ saved [5656/5656]

# Install & import libraries

In [3]:
import os
import tensorflow as tf
import numpy as np
import regex as re
import pandas as pd
from pyvi import ViTokenizer
from datasets import load_dataset

from official.nlp import optimization
from tensorflow.data import Dataset

from transformers import TFAutoModel
from transformers import AutoTokenizer

from keras.models import Model
from keras.layers import Input, Dense, Dropout, concatenate
from keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.train import CheckpointOptions

import matplotlib.pyplot as plt
from sklearn.metrics import classification_report

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Import datasets

In [5]:
TRAIN_PATH = '/content/drive/MyDrive/NEW_DATA/train_data.csv'
VAL_PATH = '/content/drive/MyDrive/NEW_DATA/val_data.csv'
TEST_PATH = '/content/drive/MyDrive/NEW_DATA/test_data.csv'

In [6]:
from datasets import load_dataset
raw_datasets = load_dataset('csv', data_files={'train': TRAIN_PATH, 'val': VAL_PATH, 'test': TEST_PATH})
raw_datasets

Generating train split: 0 examples [00:00, ? examples/s]

Generating val split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['Review', 'Price', 'Shipping', 'Outlook', 'Quality', 'Size', 'Shop_Service', 'General', 'Others'],
        num_rows: 8424
    })
    val: Dataset({
        features: ['Review', 'Price', 'Shipping', 'Outlook', 'Quality', 'Size', 'Shop_Service', 'General', 'Others'],
        num_rows: 936
    })
    test: Dataset({
        features: ['Review', 'Price', 'Shipping', 'Outlook', 'Quality', 'Size', 'Shop_Service', 'General', 'Others'],
        num_rows: 2340
    })
})

In [7]:
df_train = pd.read_csv(TRAIN_PATH)
df_val = pd.read_csv(VAL_PATH)
df_test = pd.read_csv(TEST_PATH)
df_test.head(3)

,Review,Price,Shipping,Outlook,Quality,Size,Shop_Service,General,Others
0,"Giày hơi có mùi nồng, lưu ý đôi LA không phải ...",-1,-1,-1,2,-1,-1,2,-1
1,Hàng về đẹp lắm nha ship thân thiện đi giày vừ...,-1,1,1,-1,-1,-1,-1,-1
2,Hàng ôk nên mua Dày rất đẹp,-1,-1,1,-1,-1,-1,2,-1

## Standardlize outputs

In [8]:
def make_outputs(df):
    outputs = []
    for row in range(len(df)):
        row_one_hot = []
        for col in range(1, len(df.columns)):
            sentiment = df.iloc[row, col]
            if   sentiment == -1: one_hot = [1, 0, 0, 0] # None
            elif sentiment == 1: one_hot = [0, 1, 0, 0] # Pos
            elif sentiment == 0: one_hot = [0, 0, 1, 0] # Neg
            elif sentiment == 2: one_hot = [0, 0, 0, 1] # Neu
            row_one_hot.append(one_hot)
        outputs.append(row_one_hot)
    return np.array(outputs, dtype='uint8')

In [9]:
y_train = make_outputs(df_train)
y_val = make_outputs(df_val)
y_test = make_outputs(df_test)

print('Train outputs:', y_train.shape)
print('Validate outputs:', y_val.shape)
print('Test outputs:', y_test.shape)
y_train[0]

Train outputs: (8424, 8, 4)
Validate outputs: (936, 8, 4)
Test outputs: (2340, 8, 4)

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]], dtype=uint8)

# Preprocessing

In [10]:
# Remove HTML code
def remove_HTML(text):
    return re.sub(r'<[^>]*>', '', text)


# Normalize acronyms
# !wget https://gist.githubusercontent.com/nguyenvanhieuvn/7d9441c10b3c2739499fc5a4d9ea06fb/raw/df939245b3e841b62af115be4dcb3516dadc9fc5/teencode.txt
replace_list = {
    'ô kêi': 'ok', 'okie': 'ok', 'o kê': 'ok', 'okey': 'ok', 'ôkê': 'ok', 'oki': 'ok', 'oke': 'ok', 'okay': 'ok', 'okê': 'ok',
    'tks': 'cảm ơn', 'thks': 'cảm ơn', 'thanks': 'cảm ơn', 'ths': 'cảm ơn', 'thank': 'cảm ơn',
    'kg': 'không', 'not': 'không', 'k': 'không', 'kh': 'không', 'kô': 'không', 'hok': 'không', 'ko': 'không', 'khong': 'không', 'kp': 'không phải',
    'he he': 'tích cực', 'hehe': 'tích cực', 'hihi': 'tích cực', 'haha': 'tích cực', 'hjhj': 'tích cực', 'thick': 'tích cực',
    'lol': 'tiêu cực', 'cc': 'tiêu cực', 'huhu': 'tiêu cực', 'cute': 'dễ thương',

    'sz': 'cỡ', 'size': 'cỡ',
    'wa': 'quá', 'wá': 'quá', 'qá': 'quá',
    'đx': 'được', 'dk': 'được', 'dc': 'được', 'đk': 'được', 'đc': 'được',
    'vs': 'với', 'j': 'gì', '“': ' ', 'time': 'thời gian', 'm': 'mình', 'mik': 'mình', 'r': 'rồi', 'bjo': 'bao giờ', 'very': 'rất',

    'authentic': 'chuẩn chính hãng', 'aut': 'chuẩn chính hãng', 'auth': 'chuẩn chính hãng', 'date': 'hạn sử dụng', 'hsd': 'hạn sử dụng',
    'store': 'cửa hàng', 'sop': 'cửa hàng', 'shopE': 'cửa hàng', 'shop': 'cửa hàng',
    'sp': 'sản phẩm', 'product': 'sản phẩm', 'hàg': 'hàng',
    'ship': 'giao hàng', 'delivery': 'giao hàng', 'síp': 'giao hàng', 'order': 'đặt hàng',

    'gud': 'tốt', 'wel done': 'tốt', 'good': 'tốt', 'gút': 'tốt', 'tot': 'tốt', 'nice': 'tốt', 'perfect': 'rất tốt',
    'quality': 'chất lượng', 'chất lg': 'chất lượng', 'chat': 'chất', 'excelent': 'hoàn hảo', 'bt': 'bình thường',
    'sad': 'tệ', 'por': 'tệ', 'poor': 'tệ', 'bad': 'tệ',
    'beautiful': 'đẹp tuyệt vời', 'dep': 'đẹp',
    'xau': 'xấu', 'sấu': 'xấu',

    'thik': 'thích', 'iu': 'yêu', 'fake': 'giả mạo',
    'quickly': 'nhanh', 'quick': 'nhanh', 'fast': 'nhanh',
    'fresh': 'tươi', 'delicious': 'ngon',

    'dt': 'điện thoại', 'fb': 'facebook', 'face': 'facebook', 'ks': 'khách sạn', 'nv': 'nhân viên',
    'nt': 'nhắn tin', 'ib': 'nhắn tin', 'tl': 'trả lời', 'trl': 'trả lời', 'rep': 'trả lời',
    'fback': 'feedback', 'fedback': 'feedback',
    'sd': 'sử dụng', 'sài': 'xài',

    '^_^': 'tích cực', ':)': 'tích cực', ':(': 'tiêu cực',
    '❤️': 'tích cực', '👍': 'tích cực', '🎉': 'tích cực', '😀': 'tích cực', '😍': 'tích cực', '😂': 'tích cực', '🤗': 'tích cực', '😙': 'tích cực', '🙂': 'tích cực',
    '😔': 'tiêu cực', '😓': 'tiêu cực',
    '⭐': 'star', '*': 'star', '🌟': 'star',
}

with open('teencode.txt', encoding='utf-8') as f:
    for pair in f.readlines():
        key, value = pair.split('\t')
        replace_list[key] = value.strip()


def normalize_acronyms(text):
    words = []
    for word in text.strip().split():
        if word.lower() not in replace_list.keys(): words.append(word)
        else: words.append(replace_list[word.lower()])
    return emoji.demojize(' '.join(words)) # Remove Emojis


# Word segmentation
def word_segmentation(text):
    words = ViTokenizer.tokenize(text)
    return words


# Remove unnecessary characters
def remove_unnecessary_characters(text):
    text = re.sub(r'[^\s\wáàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệóòỏõọôốồổỗộơớờởỡợíìỉĩịúùủũụưứừửữựýỳỷỹỵđÁÀẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬÉÈẺẼẸÊẾỀỂỄỆÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÍÌỈĨỊÚÙỦŨỤƯỨỪỬỮỰÝỲỶỸỴĐ_]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [12]:
def text_preprocess(text):
    text = remove_HTML(text)
    text = normalize_acronyms(text)
    text = word_segmentation(text)
    text = remove_unnecessary_characters(text)
    return text.lower()

## Tokenizing

In [ ]:
PRETRAINED_MODEL = 'vinai/phobert-base'

In [14]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(PRETRAINED_MODEL)
tokenizer.max_model_input_sizes

config.json:   0%|          | 0.00/557 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/895k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.13M [00:00<?, ?B/s]

{'vinai/phobert-base': 256, 'vinai/phobert-large': 256}

In [15]:
tokenizer.model_input_names

['input_ids', 'token_type_ids', 'attention_mask']

In [17]:
def tokenize_function(dataset):
    clean_texts = list(map(text_preprocess, dataset['Review']))
    return tokenizer(clean_texts, max_length=tokenizer.model_max_length, padding='max_length', truncation=True)

In [19]:
tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)
print('input_ids of sentence 1484:', tokenized_datasets['train'][1484]['input_ids'])

Map:   0%|          | 0/8424 [00:00<?, ? examples/s]

Map:   0%|          | 0/936 [00:00<?, ? examples/s]

Map:   0%|          | 0/2340 [00:00<?, ? examples/s]

input_ids of sentence 1484: [0, 119, 258, 204, 9389, 246, 15, 133, 123, 390, 1819, 59, 1493, 3808, 2126, 9389, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

## Prepare for TensorFlow

In [20]:
MODEL_PATH = '/content/drive/MyDrive/NEW_DATA/model_saving'

In [21]:
MAX_SEQUENCE_LENGTH = tokenizer.model_max_length

BATCH_SIZE = 12

STEPS_PER_EPOCH = len(raw_datasets['train']) // BATCH_SIZE
VALIDATION_STEPS = len(raw_datasets['val']) // BATCH_SIZE
EPOCHS = 20

In [22]:
def to_tensorflow_format(tokenized_dataset):
    features = tokenized_dataset.features
    return tokenized_dataset.remove_columns(list(features)[:-3]).with_format('tensorflow')

In [23]:
def preprocess_tokenized_dataset(tokenized_dataset, tokenizer, labels, batch_size, shuffle=False):
    tf_dataset = to_tensorflow_format(tokenized_dataset)
    features = {x: tf_dataset[x] for x in tokenizer.model_input_names}
    labels = labels.reshape(len(labels), -1)

    tf_dataset = Dataset.from_tensor_slices((features, labels))
    if shuffle: tf_dataset = tf_dataset.shuffle(buffer_size=len(tf_dataset))
    return tf_dataset.batch(batch_size).cache().prefetch(buffer_size=tf.data.AUTOTUNE)

In [24]:
train_tf_dataset = preprocess_tokenized_dataset(tokenized_datasets['train'], tokenizer, y_train, BATCH_SIZE, shuffle=True)
val_tf_dataset = preprocess_tokenized_dataset(tokenized_datasets['val'], tokenizer, y_val, BATCH_SIZE)
test_tf_dataset = preprocess_tokenized_dataset(tokenized_datasets['test'],  tokenizer, y_test, BATCH_SIZE)
train_tf_dataset

<_PrefetchDataset element_spec=({'input_ids': TensorSpec(shape=(None, 256), dtype=tf.int64, name=None), 'token_type_ids': TensorSpec(shape=(None, 256), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, 256), dtype=tf.int64, name=None)}, TensorSpec(shape=(None, 32), dtype=tf.uint8, name=None))>

# Fine-tuning with TensorFlow

## Define the model

In [26]:
def create_model(optimizer):
    inputs = {
        'input_ids'     : Input((MAX_SEQUENCE_LENGTH,), dtype='int32', name='input_ids'),
        'token_type_ids': Input((MAX_SEQUENCE_LENGTH,), dtype='int32', name='token_type_ids'),
        'attention_mask': Input((MAX_SEQUENCE_LENGTH,), dtype='int32', name='attention_mask'),
    }
    pretrained_bert = TFAutoModel.from_pretrained(PRETRAINED_MODEL, output_hidden_states=True)
    hidden_states = pretrained_bert(inputs).hidden_states

    pooled_output = concatenate(
        tuple([hidden_states[i] for i in range(-4, 0)]),
        name = 'last_4_hidden_states',
        axis = -1
    )[:, 0, :]
    x = Dropout(0.2)(pooled_output)
    print(pooled_output)

    outputs = concatenate([
        Dense(
            units = 4,
            activation = 'softmax',
            name = label.replace('#', '-').replace('&', '_'),
        )(x) for label in df_train.columns[1:]
    ], axis = -1)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer=optimizer, loss='binary_crossentropy')
    return model

## Optimzers

In [28]:
num_train_steps = STEPS_PER_EPOCH * EPOCHS
optimizer = optimization.create_optimizer(
    init_lr = 2e-4,
    num_train_steps = num_train_steps,
    num_warmup_steps = num_train_steps // 10
)
type(optimizer)

official.modeling.optimization.legacy_adamw.AdamWeightDecay

## Callbacks

In [30]:
# Stop if no improvement after 5 epochs
early_stop_callback = EarlyStopping(monitor='val_loss', patience=5, verbose=1)

checkpoint_path = MODEL_PATH + '/checkpoints/cp-{epoch:03d}.ckpt'
checkpoint_dir = os.path.dirname(checkpoint_path)

# Prevent from UnimplementedError when using TPU
options = CheckpointOptions(experimental_io_device='/job:localhost')

# Create a callback that saves the model's weights every 10 epochs
checkpoint_callback = ModelCheckpoint(
    filepath = checkpoint_path,
    save_best_only = True,
    save_weights_only = True,
    save_freq = 10 * STEPS_PER_EPOCH,
    options = options,
    verbose = 1
)

## Training

In [ ]:
model = create_model(optimizer)
history = model.fit(
    train_tf_dataset,
    validation_data = val_tf_dataset,
    validation_steps = VALIDATION_STEPS,
    steps_per_epoch = STEPS_PER_EPOCH,
    epochs = 20,
    callbacks = [
        early_stop_callback,
        checkpoint_callback
    ],
    verbose = 1,
)
model.save_weights(f'{MODEL_PATH}/PhoBert.h5')

In [ ]:
fig = plt.figure(figsize=(15, 5))
plt.plot(history.history['loss'], linestyle='solid', marker='o', color='crimson', label='Train')
plt.plot(history.history['val_loss'], linestyle='solid', marker='o', color='dodgerblue', label='Validation')
plt.xlabel('Epochs', fontsize = 14)
plt.ylabel('Loss',fontsize=14)
plt.title('Loss', fontsize=15)
plt.legend(loc='best')
fig.savefig(f'{MODEL_PATH}/evaluation.png', bbox_inches='tight')
plt.show()

## Reload the model

In [31]:
reloaded_model = create_model(optimizer)
reloaded_model.load_weights(f'{MODEL_PATH}/PhoBert.h5')
reloaded_model.summary()

tf_model.h5:   0%|          | 0.00/740M [00:00<?, ?B/s]

Some layers from the model checkpoint at vinai/phobert-base were not used when initializing TFRobertaModel: ['lm_head']
- This IS expected if you are initializing TFRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFRobertaModel were initialized from the model checkpoint at vinai/phobert-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaModel for predictions without further training.

KerasTensor(type_spec=TensorSpec(shape=(None, 3072), dtype=tf.float32, name=None), name='tf.__operators__.getitem/strided_slice:0', description="created by layer 'tf.__operators__.getitem'")
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 attention_mask (InputLayer  [(None, 256)]                0         []
 )

 input_ids (InputLayer)      [(None, 256)]                0         []

 token_type_ids (InputLayer  [(None, 256)]                0         []
 )

 tf_roberta_model (TFRobert  TFBaseModelOutputWithPooli   1349982   ['attention_mask[0][0]',
 aModel)                     ngAndCrossAttentions(last_   72         'input_ids[0][0]',
                             hidden_state=(None, 256, 7              'token_type_ids[0][0]']
                             68),
                              pooler_output=(None, 768)
                             , past_key_values=None, hi
                             dden_states=((None, 256, 7
                             68),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768),
                              (None, 256, 768)),
                              attentions=None, cross_at
                             tentions=None)

 last_4_hidden_states (Conc  (None, 256, 3072)            0         ['tf_roberta_model[0][9]',
 atenate)                                                            'tf_roberta_model[0][10]',
                                                                     'tf_roberta_model[0][11]',
                                                                     'tf_roberta_model[0][12]']

 tf.__operators__.getitem (  (None, 3072)                 0         ['last_4_hidden_states[0][0]']
 SlicingOpLambda)

 dropout_37 (Dropout)        (None, 3072)                 0         ['tf.__operators__.getitem[0][
                                                                    0]']

 Price (Dense)               (None, 4)                    12292     ['dropout_37[0][0]']

 Shipping (Dense)            (None, 4)                    12292     ['dropout_37[0][0]']

 Outlook (Dense)             (None, 4)                    12292     ['dropout_37[0][0]']

 Quality (Dense)             (None, 4)                    12292     ['dropout_37[0][0]']

 Size (Dense)                (None, 4)                    12292     ['dropout_37[0][0]']

 Shop_Service (Dense)        (None, 4)                    12292     ['dropout_37[0][0]']

 General (Dense)             (None, 4)                    12292     ['dropout_37[0][0]']

 Others (Dense)              (None, 4)                    12292     ['dropout_37[0][0]']

 concatenate (Concatenate)   (None, 32)                   0         ['Price[0][0]',
                                                                     'Shipping[0][0]',
                                                                     'Outlook[0][0]',
                                                                     'Quality[0][0]',
                                                                     'Size[0][0]',
                                                                     'Shop_Service[0][0]',
                                                                     'General[0][0]',
                                                                     'Others[0][0]']

==================================================================================================
Total params: 135096608 (515.35 MB)
Trainable params: 135096608 (515.35 MB)
Non-trainable params: 0 (0.00 Byte)
__________________________________________________________________________________________________

# Prediction

In [32]:
y_test_argmax = np.argmax(y_test, axis=-1)
y_test_argmax

array([[0, 0, 0, ..., 0, 3, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 3, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 3, ..., 0, 0, 0],
       [0, 0, 0, ..., 2, 0, 0]])

## Predict on test data

In [33]:
def predict(model, inputs, batch_size=1, verbose=0):
    y_pred = model.predict(inputs, batch_size=batch_size, verbose=verbose)
    y_pred = y_pred.reshape(len(y_pred), -1, 4)
    return np.argmax(y_pred, axis=-1) # sentiment values (position that have max value)

In [34]:
def print_acsa_pred(replacements, categories, sentence_pred):
    sentiments = map(lambda x: replacements[x], sentence_pred)
    for category, sentiment in zip(categories, sentiments):
        if sentiment: print(f'=> {category},{sentiment}')

In [36]:
y_pred = predict(reloaded_model, test_tf_dataset, BATCH_SIZE, verbose=1)
reloaded_model.evaluate(test_tf_dataset, batch_size=BATCH_SIZE, verbose=1)

195/195 [==============================] - 53s 223ms/step
195/195 [==============================] - 48s 223ms/step - loss: 0.1512

0.15124358236789703

In [ ]:
replacements = {0: None, 1: 'positive', 2: 'negative', 3: 'neutral'}
categories = df_test.columns[1:]
print('Example:', df_test['Review'][1])
print_acsa_pred(replacements, categories, y_pred[1])

## Predict random text

In [ ]:
example_input = text_preprocess(input('Enter your sentence: '))
tokenized_input = tokenizer(example_input, padding='max_length', truncation=True)
features = {x: [[tokenized_input[x]]] for x in tokenizer.model_input_names}

pred = predict(reloaded_model, Dataset.from_tensor_slices(features))
print_acsa_pred(replacements, categories, pred[0])

# Report metrics

# Aspect score

In [ ]:
list_aspect = ['Price', 'Shipping', 'Outlook', 'Quality', 'Size', 'Shop_Service', 'General']
for idx, i in enumerate(list_aspect):
    print(f'Aspect: {i}')
    true = df_test[i].values
    pred = [row[idx] for row in y_pred]
    for i in range(len(pred)):
        if pred[i] == 0:
            pred[i] = -1
        elif pred[i] == 3:
            pred[i] = 2
        elif pred[i] == 2:
            pred[i] = 0
    print(classification_report(pred, true))

In [ ]:
y_pred

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

## Aspect Detection

In [ ]:
aspect_test = []
aspect_pred = []

for row_test, row_pred in zip(y_test_argmax, y_pred):
    for index, (col_test, col_pred) in enumerate(zip(row_test, row_pred)):
        aspect_test.append(bool(col_test) * categories[index])
        aspect_pred.append(bool(col_pred) * categories[index])

In [ ]:
aspect_report = classification_report(aspect_test, aspect_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_test, aspect_pred, digits=4, zero_division=1))

              precision    recall  f1-score   support

                 0.9566    0.9463    0.9515     14062
     General     0.6349    0.7516    0.6883       479
      Others     0.8452    0.7513    0.7955       189
     Outlook     0.9254    0.9276    0.9265      1271
       Price     0.8083    0.8035    0.8059       341
     Quality     0.8264    0.8120    0.8191       686
    Shipping     0.9358    0.9716    0.9534       705
Shop_Service     0.8209    0.8783    0.8486       600
        Size     0.7995    0.8553    0.8265       387

    accuracy                         0.9275     18720
   macro avg     0.8392    0.8553    0.8461     18720
weighted avg     0.9293    0.9275    0.9281     18720

## Polarity Detection

In [ ]:
y_test_flat = y_test_argmax.flatten()
y_pred_flat = y_pred.flatten()
target_names = list(map(str, replacements.values()))

In [ ]:
polarity_report = classification_report(y_test_flat, y_pred_flat, digits=4, output_dict=True)
print(classification_report(y_test_flat, y_pred_flat, target_names=target_names, digits=4))

              precision    recall  f1-score   support

        None     0.9566    0.9463    0.9515     14062
    positive     0.8136    0.8818    0.8463      3273
    negative     0.7431    0.5436    0.6279       596
     neutral     0.5151    0.5399    0.5272       789

    accuracy                         0.9051     18720
   macro avg     0.7571    0.7279    0.7382     18720
weighted avg     0.9062    0.9051    0.9049     18720

## Aspect + Polarity

In [ ]:
aspect_polarity_test = []
aspect_polarity_pred = []

for row_test, row_pred in zip(y_test_argmax, y_pred):
    for index, (col_test, col_pred) in enumerate(zip(row_test, row_pred)):
        aspect_polarity_test.append(f'{categories[index]},{replacements[col_test]}')
        aspect_polarity_pred.append(f'{categories[index]},{replacements[col_pred]}')

In [ ]:
aspect_polarity_test = [x for x in aspect_polarity_test if x != 'Others,None']
aspect_polarity_test = [x for x in aspect_polarity_test if x != 'Others,neutral']

aspect_polarity_pred = [x for x in aspect_polarity_pred if x != 'Others,None']
aspect_polarity_pred = [x for x in aspect_polarity_pred if x != 'Others,neutral']

In [ ]:
aspect_polarity_report = classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1))

                       precision    recall  f1-score   support

         General,None     0.9329    0.8888    0.9103      1861
     General,negative     0.3333    0.0909    0.1429        11
      General,neutral     0.5789    0.5410    0.5593       183
     General,positive     0.5267    0.7263    0.6106       285
         Outlook,None     0.9137    0.9111    0.9124      1069
     Outlook,negative     0.7761    0.5474    0.6420        95
      Outlook,neutral     0.4000    0.3793    0.3894        58
     Outlook,positive     0.9019    0.9293    0.9154      1118
           Price,None     0.9665    0.9675    0.9670      1999
       Price,negative     0.0000    0.0000    0.0000         3
        Price,neutral     0.6591    0.3187    0.4296        91
       Price,positive     0.7347    0.8745    0.7985       247
         Quality,None     0.9226    0.9293    0.9259      1654
     Quality,negative     0.6875    0.3367    0.4521        98
      Quality,neutral     0.3333    0.4818    0.3941       110
     Quality,positive     0.8373    0.8180    0.8275       478
        Shipping,None     0.9876    0.9713    0.9793      1635
    Shipping,negative     0.8778    0.6371    0.7383       124
     Shipping,neutral     0.1429    0.2188    0.1728        32
    Shipping,positive     0.9022    0.9745    0.9370       549
    Shop_Service,None     0.9570    0.9339    0.9453      1740
Shop_Service,negative     0.7339    0.6500    0.6894       140
 Shop_Service,neutral     0.3750    0.2069    0.2667        29
Shop_Service,positive     0.7590    0.8840    0.8167       431
            Size,None     0.9709    0.9575    0.9642      1953
        Size,negative     0.6602    0.5440    0.5965       125
         Size,neutral     0.4121    0.7010    0.5191        97
        Size,positive     0.8014    0.7091    0.7524       165

             accuracy                         0.8960     16380
            macro avg     0.6816    0.6475    0.6520     16380
         weighted avg     0.9012    0.8960    0.8965     16380

## Summary

In [ ]:
aspect_dict = aspect_report['macro avg']
aspect_dict['accuracy'] = aspect_report['accuracy']

polarity_dict  = polarity_report['macro avg']
polarity_dict['accuracy'] = polarity_report['accuracy']

aspect_polarity_dict = aspect_polarity_report['macro avg']
aspect_polarity_dict['accuracy'] = aspect_polarity_report['accuracy']

In [ ]:
df_report = pd.DataFrame.from_dict([aspect_dict, polarity_dict, aspect_polarity_dict])
df_report.index = ['Aspect Detection', 'Polarity Detection', 'Aspect + Polarity']
df_report.drop('support', axis=1)

                    precision    recall  f1-score  accuracy
Aspect Detection     0.839232  0.855283  0.846145  0.927457
Polarity Detection   0.757132  0.727904  0.738230  0.905075
Aspect + Polarity    0.681586  0.647450  0.651952  0.895971