In [1]:
pip install pyvi

Collecting pyvi
  Downloading pyvi-0.1.1-py2.py3-none-any.whl (8.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 23.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.10/site-packages (from pyvi) (1.2.2)
Collecting sklearn-crfsuite (from pyvi)
  Downloading sklearn_crfsuite-0.3.6-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: numpy>=1.17.3 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->pyvi) (1.24.3)
Requirement already satisfied: scipy>=1.3.2 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->pyvi) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->pyvi) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->pyvi) (3.2.0)
Collecting python-crfsuite>=0.8.3 (from sklearn-crfsuite->pyvi)
  Obtaining dependency information for python-crfsuite>=0.8.3 from https://files.pythonhosted.org/packages/38/1d/c475ba7d11e9735f00eb08e2f5315aa2e21c24cc85a0474c3fd425edef58/python_crfsuite-0.9.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading python_crfsuite-0.9.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from sklearn-crfsuite->pyvi) (1.16.0)
Requirement already satisfied: tabulate in /opt/conda/lib/python3.10/site-packages (from sklearn-crfsuite->pyvi) (0.9.0)
Requirement already satisfied: tqdm>=2.0 in /opt/conda/lib/python3.10/site-packages (from sklearn-crfsuite->pyvi) (4.66.1)
Downloading python_crfsuite-0.9.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 58.9 MB/s eta 0:00:00
Installing collected packages: python-crfsuite, sklearn-crfsuite, pyvi
Successfully installed python-crfsuite-0.9.10 pyvi-0.1.1 sklearn-crfsuite-0.3.6
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install gensim

Requirement already satisfied: gensim in /opt/conda/lib/python3.10/site-packages (4.3.2)
Requirement already satisfied: numpy>=1.18.5 in /opt/conda/lib/python3.10/site-packages (from gensim) (1.24.3)
Requirement already satisfied: scipy>=1.7.0 in /opt/conda/lib/python3.10/site-packages (from gensim) (1.11.4)
Requirement already satisfied: smart-open>=1.8.1 in /opt/conda/lib/python3.10/site-packages (from gensim) (6.3.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install vncorenlp

Collecting vncorenlp
  Downloading vncorenlp-1.0.3.tar.gz (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 9.8 MB/s eta 0:00:00:00:010:01
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from vncorenlp) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->vncorenlp) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->vncorenlp) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->vncorenlp) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->vncorenlp) (2023.11.17)
Building wheels for collected packages: vncorenlp
  Building wheel for vncorenlp (setup.py) ... done
  Created wheel for vncorenlp: filename=vncorenlp-1.0.3-py3-none-any.whl size=2645932 sha256=9bd1ec1c34e5f760cdf00c1a8f2b10053d3ed349ebc344be171d45a48b2e8496
  Stored in directory: /root/.cache/pip/wheels/5d/d9/b3/41f6c6b1ab758561fd4aab55dc0480b9d7a131c6aaa573a3fa
Successfully built vncorenlp
Installing collected packages: vncorenlp
Successfully installed vncorenlp-1.0.3
Note: you may need to restart the kernel to use updated packages.

In [4]:
!git clone https://github.com/vncorenlp/VnCoreNLP.git

Cloning into 'VnCoreNLP'...
remote: Enumerating objects: 259, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 259 (delta 17), reused 14 (delta 2), pack-reused 212
Receiving objects: 100% (259/259), 237.79 MiB | 50.67 MiB/s, done.
Resolving deltas: 100% (93/93), done.

In [5]:
!rm -rf teencode.txt
!wget https://gist.githubusercontent.com/nguyenvanhieuvn/7d9441c10b3c2739499fc5a4d9ea06fb/raw/df939245b3e841b62af115be4dcb3516dadc9fc5/teencode.txt

--2023-12-21 01:59:48--  https://gist.githubusercontent.com/nguyenvanhieuvn/7d9441c10b3c2739499fc5a4d9ea06fb/raw/df939245b3e841b62af115be4dcb3516dadc9fc5/teencode.txt
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5656 (5.5K) [text/plain]
Saving to: 'teencode.txt'

teencode.txt        100%[===================>]   5.52K  --.-KB/s    in 0s

2023-12-21 01:59:48 (57.6 MB/s) - 'teencode.txt' saved [5656/5656]

In [6]:
import sys
sys.path.insert(1, '/kaggle/input/preprocess')

from preprocess import (
    remove_HTML,
    convert_unicode,
    # standardize_sentence_typing,
    normalize_acronyms,
    #word_segmentation, # When use PhoBERT
    remove_unnecessary_characters
)

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [7]:
import pandas as pd
import numpy as np
import re
from pyvi import ViTokenizer
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras.layers import Dense, Dropout, Concatenate, Input
from keras.layers import LSTM, Embedding, Bidirectional, GRU
from keras.layers import SpatialDropout1D, Conv1D, GlobalAveragePooling1D, GlobalMaxPooling1D
from keras.preprocessing.text import Tokenizer
import seaborn as sns
from gensim import models
from keras.initializers import Constant
from keras.preprocessing.sequence import pad_sequences
from keras.losses import BinaryCrossentropy, CategoricalCrossentropy
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt

# I. Read Data

In [8]:
df_train = pd.read_csv('/kaggle/input/sneaker-reviews-2-0/train_data_final.csv')
df_val = pd.read_csv('/kaggle/input/sneaker-reviews-2-0/val_data_final.csv')
df_test = pd.read_csv('/kaggle/input/sneaker-reviews-2-0/test_data_final.csv')

In [9]:
df_train = df_train.rename(columns={'Review': 'Comment'})
df_val = df_val.rename(columns={'Review': 'Comment'})
df_test = df_test.rename(columns={'Review': 'Comment'})

In [10]:
df = pd.read_csv('/kaggle/input/sneaker-reviews/Raw data.csv')

In [11]:
df_train['Others'] = [-1] * len(df_train)
df_test['Others'] = [-1] * len(df_test)
df_val['Others'] = [-1] * len(df_val)

In [12]:
def convert_others(dft, df):
    for i in range(len(dft)):
        idx = df[df['Comment'] == dft['Comment'][i]].index.values[0]
        if type(df['Others'][idx]) == str:
            if(df['Others'][idx] == 'x'):
                dft.loc[i, 'Others'] = 2
            else:
                dft.loc[i, 'Others'] = int(df['Others'][idx])
    return dft

In [13]:
df_train = convert_others(df_train, df)
df_test = convert_others(df_test, df)
df_val = convert_others(df_val, df)

# II. Preprocess

In [14]:
import regex as re
import string
import emoji

from vncorenlp import VnCoreNLP
from nltk import flatten

In [15]:
def text_preprocess(text):
    text = remove_HTML(text)
    text = convert_unicode(text)
    # text = standardize_sentence_typing(text)
    text = normalize_acronyms(text)
    #text = word_segmentation(text) # When use PhoBERT
    text = remove_unnecessary_characters(text)
    return text.lower()
    #return text

In [16]:
WORDS_NO_UNIKEY = {
    "ă": "aw", "ắ": "aws", "ằ": "awf", "ẳ": "awr", "ẵ": "awx", "ặ": "awj",
    "â": "aa", "ấ": "aas", "ậ": "aaj", "ẩ": "aar", "ầ": "aaf", "ẫ": "aax",
    "á": "as", "à": "af", "ả": "ar", "ã": "ax", "ạ": "aj",
    "ô": "oo", "ố": "oos", "ồ": "oof", "ổ": "oor", "ỗ": "oox", "ộ": "ooj",
    "ó": "os", "ò": "of", "ỏ": "or", "õ": "ox", "ọ": "oj",
    "ơ": "ow", "ớ": "ows", "ờ": "owf", "ở": "owr", "ỡ": "owx", "ợ": "owj",
    "é": "es", "è": "ef", "ẻ": "er", "ẽ": "ex", "ẹ": "ej",
    "ê": "ee", "ế": "ees", "ề": "eef", "ể": "eer", "ễ": "eex", "ệ": "eej",
    "ú": "us", "ù": "uf", "ủ": "ur", "ũ": "ux", "ụ": "uj",
    "ư": "uw", "ứ": "uws", "ừ": "uwf", "ử": "uwr", "ữ": "uwx", "ự": "uwj",
    "í": "is", "ì": "if", "ỉ": "ir", "ị": "ij", "ĩ": "ix",
    "ý": "ys", "ỳ": "yf", "ỷ": "yr", "ỵ": "yj", "ỹ": "yx", "đ": "dd",
}

In [17]:
def remove_duplication(word):
    if word == '':
        return word
    prev_word = ""
    output = ""
    for c in word:
        if c != prev_word:
            _c = c.lower()
            raw_word = WORDS_NO_UNIKEY.get(_c, _c)[0]
            if prev_word == "" or raw_word != WORDS_NO_UNIKEY.get(prev_word, prev_word)[0]:
                output += c
                prev_word = raw_word
    return output

In [18]:
def preprocess(cm):
    new_cm = text_preprocess(cm)
    new_cm = remove_duplication(new_cm)
    new_cm = ViTokenizer.tokenize(new_cm)
    return new_cm

In [19]:
df_train['Preprocessed'] = df_train['Comment'].apply(preprocess)
df_val['Preprocessed'] = df_val['Comment'].apply(preprocess)
df_test['Preprocessed'] = df_test['Comment'].apply(preprocess)

In [20]:
cols = df_train.columns.drop(['Comment', 'Preprocessed'])
for col in cols:
    df_train[col] = df_train[col].astype(int)
    df_val[col] = df_val[col].astype(int)
    df_test[col] = df_test[col].astype(int)

In [21]:
df_train

,Comment,Price,Shipping,Outlook,Quality,Size,Shop_Service,General,Others,Preprocessed
0,"Giày đẹp, đi êm lắm",-1,-1,1,1,-1,-1,-1,-1,giày đẹp đi êm lắm
1,Mình săn sale với giá khá rẻ Chất lượng ok Sh...,1,1,-1,1,-1,-1,-1,-1,mình săn sale với giá khá rẻ chất_lượng ok shi...
2,Hình ảnh và video chỉ mang tính chất minh họa ...,1,1,-1,-1,-1,-1,1,-1,hình_ảnh và video chỉ mang tính_chất minh_họa ...
3,Mình đặt size 39 nhưng chật k đeo nổi. Còn giầ...,-1,1,1,-1,0,-1,-1,-1,mình đặt cỡ 39 nhưng chật không đeo nổi còn gi...
4,Nên mua nha mọi người đẹp xuất sắc lun ạ,-1,-1,1,-1,-1,-1,-1,-1,nên mua nha mọi người đẹp xuất_sắc lun ạ
...,...,...,...,...,...,...,...,...,...,...
8419,"sản phẩm như mô tả, chất lượng tốt, đáng sử dụ...",-1,-1,-1,1,-1,1,-1,-1,sản_phẩm như mô_tả chất_lượng tốt đáng sử_dụng...
8420,"sản phẩm tốt mọi nguòi nên mua ạ,giá tiền phù ...",2,-1,-1,-1,-1,-1,1,-1,sản_phẩm tốt mọi nguòi nên mua ạ giá tiền phù_...
8421,Nên mua nhé giày đẹp lắm ❤,-1,-1,1,-1,-1,-1,-1,-1,nên mua nhé giày đẹp lắm red_heart
8422,Hàng đẹp lắm ạ. Mk mua 2 đôi đều ưng ạ. Shop u...,-1,-1,1,-1,-1,1,-1,-1,hàng đẹp lắm ạ mình mua 2 đôi đều ưng ạ cửa_hà...
8423,"Giày xinh lắm nhe, giá như này mà dc giày chất...",-1,-1,1,1,-1,-1,-1,-1,giày xinh lắm nhe giá_như này mà được giày chấ...

# III. Create Input

In [22]:
def get_label_stage_1(df):
    is_price = df.Price.replace({-1: 0, 0: 1, 2: 1})
    is_shipping = df.Shipping.replace({-1: 0, 0: 1, 2: 1})
    is_outlook = df.Outlook.replace({-1: 0, 0: 1, 2: 1})
    is_quality = df.Quality.replace({-1: 0, 0: 1, 2: 1})
    is_size = df.Size.replace({-1: 0, 0: 1, 2: 1})
    is_shopservice = df.Shop_Service.replace({-1: 0, 0: 1, 2: 1})
    is_general = df.General.replace({-1: 0, 0: 1, 2: 1})
    is_others = df.Others.replace({-1: 0, 0: 1, 2: 1})
    dict = {
          'is_price': is_price, 
          'is_shipping': is_shipping,
          'is_outlook': is_outlook,
          'is_quality': is_quality,
          'is_size': is_size,
          'is_shopservice': is_shopservice,
          'is_general': is_general, 
          'is_others': is_others
    }
    df_aspect = pd.DataFrame(dict)
    return df_aspect

In [23]:
def get_index_label(label_stage_df, aspect):
    return [indx_ for indx_ in label_stage_df[label_stage_df['is_{}'.format(aspect)]==1].index.values if indx_ != 0]

def get_list_index_label(label_stage_df, lst_aspect):
    lst_indx_label = {}
    for aspect in lst_aspect:
        lst_indx_label[aspect] = get_index_label(label_stage_df, aspect)
        
    return lst_indx_label

def get_data_stage_2(lst_indx_label, df):
    data = {}
    for aspect, indx in lst_indx_label.items():
        data[aspect] = df.iloc[indx]
    return data

def get_label_stage_2(df_input):
    df_stage_2 = df_input.copy()

    y_price = tf.keras.utils.to_categorical(df_stage_2['price'].Price, num_classes = 3)
    y_shipping = tf.keras.utils.to_categorical(df_stage_2['shipping'].Shipping, num_classes = 3)
    y_outlook = tf.keras.utils.to_categorical(df_stage_2['outlook'].Outlook, num_classes = 3)
    y_quality = tf.keras.utils.to_categorical(df_stage_2['quality'].Quality, num_classes = 3)
    y_others = df_stage_2['others'].Others.replace({-1:0}).to_numpy()
    y_size = tf.keras.utils.to_categorical(df_stage_2['size'].Size, num_classes = 3)
    y_shopservice = tf.keras.utils.to_categorical(df_stage_2['shopservice'].Shop_Service, num_classes = 3)
    y_general = tf.keras.utils.to_categorical(df_stage_2['general'].General, num_classes = 3)
    
    dict2 = {'price': y_price, 
             'shipping': y_shipping,
             'outlook': y_outlook,
             'quality': y_quality,
             'others': y_others,
             'size': y_size,
             'shopservice': y_shopservice,
             'general': y_general}
    del df_stage_2
    
    return dict2

In [24]:
def get_label_stage_3(df_input):
    df_stage_3 = df_input.copy()

    y_price = tf.keras.utils.to_categorical(df_stage_3['Price'], num_classes = 4)
    y_shipping = tf.keras.utils.to_categorical(df_stage_3['Shipping'], num_classes = 4)
    y_outlook = tf.keras.utils.to_categorical(df_stage_3['Outlook'], num_classes = 4)
    y_quality = tf.keras.utils.to_categorical(df_stage_3['Quality'], num_classes = 4)
    y_others = df_stage_3['Others'].replace({-1:0}).to_numpy()
    y_size = tf.keras.utils.to_categorical(df_stage_3['Size'], num_classes = 4)
    y_shopservice = tf.keras.utils.to_categorical(df_stage_3['Shop_Service'], num_classes = 4)
    y_general = tf.keras.utils.to_categorical(df_stage_3['General'], num_classes = 4)
    
    dict3 = {'price': y_price, 
             'shipping': y_shipping,
             'outlook': y_outlook,
             'quality': y_quality,
             'others': y_others,
             'size': y_size,
             'shopservice': y_shopservice,
             'general': y_general}
    del df_stage_3
    
    return dict3

In [25]:
def get_cmt(dict_df, lst_aspect):
    dict_cmt = {}
    for aspect in lst_aspect:
        dict_cmt[aspect] = dict_df[aspect]['Preprocessed'].values
    return dict_cmt

In [26]:
def get_array_label(df):
    label_stage_1_df = get_label_stage_1(df)
    lst_aspect = ['price', 'shipping', 'outlook', 'quality', 'size', 'shopservice', 'general', 'others']
    lst_indx = get_list_index_label(label_stage_1_df, lst_aspect)
    
    df_temp = get_data_stage_2(lst_indx, df)
    cmt_df = get_cmt(df_temp, lst_aspect)
    
    label_stage_2 = get_label_stage_2(df_temp)
    label_stage_3 = get_label_stage_3(df)
    del label_stage_1_df, lst_aspect, df_temp
    
    return cmt_df, label_stage_2, label_stage_3

In [27]:
df_train.shape, df_val.shape, df_test.shape

((8424, 10), (936, 10), (2340, 10))

In [28]:
label_aspect_train = get_label_stage_1(df_train)
label_aspect_val = get_label_stage_1(df_val)
label_aspect_test = get_label_stage_1(df_test)

In [29]:
label_aspect_train

,is_price,is_shipping,is_outlook,is_quality,is_size,is_shopservice,is_general,is_others
0,0,0,1,1,0,0,0,0
1,1,1,0,1,0,0,0,0
2,1,1,0,0,0,0,1,0
3,0,1,1,0,1,0,0,0
4,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...
8419,0,0,0,1,0,1,0,0
8420,1,0,0,0,0,0,1,0
8421,0,0,1,0,0,0,0,0
8422,0,0,1,0,0,1,0,0
8423,0,0,1,1,0,0,0,0

In [30]:
cmt_train, label_sentiment_train, lb_train = get_array_label(df_train)
cmt_val, label_sentiment_val, lb_val = get_array_label(df_val)
cmt_test, label_sentiment_test, lb_test = get_array_label(df_test)

# IV. Embedding

In [31]:
max_len = 200

In [32]:
def get_tokenize(train, val, test):
    tok = Tokenizer(filters='')
    tok.fit_on_texts(train)
    tok.fit_on_texts(val)
    tok.fit_on_texts(test)
    
    tokenized_train = tok.texts_to_sequences(train)
    tokenized_val = tok.texts_to_sequences(val)
    tokenized_test = tok.texts_to_sequences(test)
    
    return tok, tokenized_train, tokenized_val, tokenized_test

In [33]:
def get_padded(max_len, tokenized_train, tokenized_val, tokenized_test):
    padded_train = pad_sequences(tokenized_train, padding = 'post', maxlen = max_len)
    padded_val = pad_sequences(tokenized_val, padding = 'post', maxlen = max_len)
    padded_test = pad_sequences(tokenized_test, padding = 'post', maxlen = max_len)
    
    return padded_train, padded_val, padded_test

In [34]:
def get_embedding_matrix(embedding_dim, vocab_size, tok):
    embed_matrix = np.zeros(shape=(vocab_size, embedding_dim))
    word_failed = []

    for word, i in tok.word_index.items():
        try:
            embed_vector = w2c_model[word]
        except:
            word_failed.append(word)
        else:
            embed_matrix[i] = embed_vector
            
    return embed_matrix

In [35]:
w2v_path = '/kaggle/input/elmo-sen/elmo_aivivn_train_test_wikn_sen.txt'
w2c_model = models.KeyedVectors.load_word2vec_format(w2v_path, binary = False)

In [36]:
tokenizer_aspect, tokenized_aspect_train, tokenized_aspect_val, tokenized_aspect_test = get_tokenize(df_train['Preprocessed'].values, df_val['Preprocessed'].values, df_test['Preprocessed'].values)

In [37]:
padded_aspect_train, padded_aspect_val, padded_aspect_test = get_padded(max_len, tokenized_aspect_train, tokenized_aspect_val, tokenized_aspect_test)

In [38]:
embedding_dim = 1024 
vocab_aspect_size = len(tokenizer_aspect.word_index)+1
embedding_aspect_matrix = get_embedding_matrix(embedding_dim, vocab_aspect_size, tokenizer_aspect)

In [39]:
embedding_aspect_matrix.shape

(10034, 1024)

# V. Model

## 1. BiLSTM

## a) Build Model

In [40]:
def bilstm_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_aspect_size,
                      output_dim=embedding_dim,
                      embeddings_initializer=Constant(embedding_aspect_matrix),
                      input_length=max_len,
                      trainable=True)(input)
    lstm = Bidirectional(LSTM(units = 200, activation = 'tanh'))(embed)
    
    # aspect 
    aspect_dense2 = Dense(128, activation='relu')(lstm)
    aspect_dropout1 = Dropout(0.2)(aspect_dense2)
    aspect_dense3 = Dense(64, activation='relu')(aspect_dropout1)
    aspect_dense4 = Dense(32, activation='relu')(aspect_dense3)
    aspect_dense5 = Dense(8, activation='sigmoid')(aspect_dense4)
    
    aspect_model = tf.keras.Model(inputs = input, outputs = aspect_dense5)
    aspect_model.compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    # Fit model
    history = aspect_model.fit(x=padded_aspect_train,
                               y=label_aspect_train.to_numpy(),
                               validation_data=(padded_aspect_val, label_aspect_val.to_numpy()),
                               batch_size = 128,
                               epochs=epochs,
                               callbacks = [callback],
                               verbose=1)
    
    return aspect_model

In [41]:
aspect_model_bil = bilstm_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val)

Epoch 1/70
66/66 [==============================] - 23s 193ms/step - loss: 0.5722 - acc: 0.3403 - val_loss: 0.5012 - val_acc: 0.3611
Epoch 2/70
66/66 [==============================] - 10s 157ms/step - loss: 0.4533 - acc: 0.4180 - val_loss: 0.3914 - val_acc: 0.4840
Epoch 3/70
66/66 [==============================] - 10s 152ms/step - loss: 0.3639 - acc: 0.5134 - val_loss: 0.3184 - val_acc: 0.5673
Epoch 4/70
66/66 [==============================] - 9s 137ms/step - loss: 0.3082 - acc: 0.5643 - val_loss: 0.2757 - val_acc: 0.5897
Epoch 5/70
66/66 [==============================] - 8s 127ms/step - loss: 0.2656 - acc: 0.5946 - val_loss: 0.2514 - val_acc: 0.5994
Epoch 6/70
66/66 [==============================] - 9s 132ms/step - loss: 0.2400 - acc: 0.6064 - val_loss: 0.2387 - val_acc: 0.5919
Epoch 7/70
66/66 [==============================] - 8s 127ms/step - loss: 0.2187 - acc: 0.6269 - val_loss: 0.2316 - val_acc: 0.5908
Epoch 8/70
66/66 [==============================] - 8s 117ms/step - loss: 0.2018 - acc: 0.6233 - val_loss: 0.2287 - val_acc: 0.5876
Epoch 9/70
66/66 [==============================] - 9s 130ms/step - loss: 0.1887 - acc: 0.6292 - val_loss: 0.2242 - val_acc: 0.5940
Epoch 10/70
66/66 [==============================] - 7s 113ms/step - loss: 0.1750 - acc: 0.6333 - val_loss: 0.2240 - val_acc: 0.5652
Epoch 11/70
66/66 [==============================] - 8s 117ms/step - loss: 0.1655 - acc: 0.6415 - val_loss: 0.2253 - val_acc: 0.5962
Epoch 12/70
66/66 [==============================] - 7s 112ms/step - loss: 0.1564 - acc: 0.6449 - val_loss: 0.2271 - val_acc: 0.5684
Epoch 13/70
66/66 [==============================] - 8s 118ms/step - loss: 0.1456 - acc: 0.6407 - val_loss: 0.2289 - val_acc: 0.5470

In [42]:
pred_train = aspect_model_bil.predict(padded_aspect_train)
pred_val = aspect_model_bil.predict(padded_aspect_val)
pred_test = aspect_model_bil.predict(padded_aspect_test)

df_train_pred = round(pd.DataFrame(pred_train), 0)
df_train_true_ = label_aspect_train
df_train_pred.columns = df_train_true_.columns

df_val_pred = round(pd.DataFrame(pred_val), 0)
df_val_true_ = label_aspect_val
df_val_pred.columns = df_val_true_.columns

df_test_pred = round(pd.DataFrame(pred_test), 0)
df_test_true_ = label_aspect_test
df_test_pred.columns = df_test_true_.columns

264/264 [==============================] - 4s 13ms/step
30/30 [==============================] - 0s 12ms/step
74/74 [==============================] - 1s 13ms/step

In [43]:
#import os, glob
#for filename in glob.glob("/kaggle/working/elmo*"):
    #os.remove(filename)

In [44]:
def get_pd_report(label_aspect_train, df_test_true_, df_test_pred):
    aspect_result_bilstm_report = {}
    for col in label_aspect_train.columns:
        aspect_result_bilstm = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
        aspect_result_bilstm_report[col] = pd.DataFrame(aspect_result_bilstm).T
        aspect_result_bilstm_report[col]['aspect'] = col
        
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_bilstm_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_bilstm_report[indx]])
    
    return output_aspect_report

In [45]:
aspect_result_bilstm_report = {}
for col in label_aspect_train.columns:
    print(col)
    aspect_result_bilstm = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
    print(aspect_result_bilstm)
    
    aspect_result_bilstm_report[col] = pd.DataFrame(aspect_result_bilstm).T
    aspect_result_bilstm_report[col]['aspect'] = col
    
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_bilstm_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_bilstm_report[indx]])

is_price
{'0': {'precision': 0.9499518768046198, 'recall': 0.9874937468734367, 'f1-score': 0.9683590875643855, 'support': 1999}, '1': {'precision': 0.9045801526717557, 'recall': 0.6950146627565983, 'f1-score': 0.7860696517412937, 'support': 341}, 'accuracy': 0.9448717948717948, 'macro avg': {'precision': 0.9272660147381877, 'recall': 0.8412542048150176, 'f1-score': 0.8772143696528396, 'support': 2340}, 'weighted avg': {'precision': 0.9433400144416683, 'recall': 0.9448717948717948, 'f1-score': 0.9417946868739263, 'support': 2340}}
is_shipping
{'0': {'precision': 0.9725609756097561, 'recall': 0.9755351681957186, 'f1-score': 0.9740458015267176, 'support': 1635}, '1': {'precision': 0.9428571428571428, 'recall': 0.9361702127659575, 'f1-score': 0.9395017793594306, 'support': 705}, 'accuracy': 0.9636752136752137, 'macro avg': {'precision': 0.9577090592334494, 'recall': 0.955852690480838, 'f1-score': 0.9567737904430741, 'support': 2340}, 'weighted avg': {'precision': 0.9636117439471098, 'recall': 0.9636752136752137, 'f1-score': 0.9636383076686248, 'support': 2340}}
is_outlook
{'0': {'precision': 0.8816725978647687, 'recall': 0.9270346117867165, 'f1-score': 0.9037847697218422, 'support': 1069}, '1': {'precision': 0.9358552631578947, 'recall': 0.8953579858379229, 'f1-score': 0.9151588258946521, 'support': 1271}, 'accuracy': 0.9098290598290598, 'macro avg': {'precision': 0.9087639305113318, 'recall': 0.9111962988123197, 'f1-score': 0.9094717978082472, 'support': 2340}, 'weighted avg': {'precision': 0.9111025840133, 'recall': 0.9098290598290598, 'f1-score': 0.9099627292926292, 'support': 2340}}
is_quality
{'0': {'precision': 0.9210042865890998, 'recall': 0.909310761789601, 'f1-score': 0.9151201703681169, 'support': 1654}, '1': {'precision': 0.7878359264497878, 'recall': 0.8119533527696793, 'f1-score': 0.7997128499641063, 'support': 686}, 'accuracy': 0.8807692307692307, 'macro avg': {'precision': 0.8544201065194439, 'recall': 0.8606320572796402, 'f1-score': 0.8574165101661115, 'support': 2340}, 'weighted avg': {'precision': 0.8819643314371476, 'recall': 0.8807692307692307, 'f1-score': 0.8812870841300181, 'support': 2340}}
is_size
{'0': {'precision': 0.9612442631310556, 'recall': 0.9651817716333846, 'f1-score': 0.9632089933571794, 'support': 1953}, '1': {'precision': 0.820580474934037, 'recall': 0.8036175710594315, 'f1-score': 0.8120104438642298, 'support': 387}, 'accuracy': 0.9384615384615385, 'macro avg': {'precision': 0.8909123690325462, 'recall': 0.8843996713464081, 'f1-score': 0.8876097186107046, 'support': 2340}, 'weighted avg': {'precision': 0.9379806366215487, 'recall': 0.9384615384615385, 'f1-score': 0.9382030794025762, 'support': 2340}}
is_shopservice
{'0': {'precision': 0.9183561643835616, 'recall': 0.9632183908045977, 'f1-score': 0.9402524544179524, 'support': 1740}, '1': {'precision': 0.8757281553398059, 'recall': 0.7516666666666667, 'f1-score': 0.8089686098654709, 'support': 600}, 'accuracy': 0.908974358974359, 'macro avg': {'precision': 0.8970421598616838, 'recall': 0.8574425287356322, 'f1-score': 0.8746105321417117, 'support': 2340}, 'weighted avg': {'precision': 0.9074259056543934, 'recall': 0.908974358974359, 'f1-score': 0.9065899301737264, 'support': 2340}}
is_general
{'0': {'precision': 0.9069020866773676, 'recall': 0.9108006448146158, 'f1-score': 0.9088471849865951, 'support': 1861}, '1': {'precision': 0.6475583864118896, 'recall': 0.6367432150313153, 'f1-score': 0.6421052631578947, 'support': 479}, 'accuracy': 0.8547008547008547, 'macro avg': {'precision': 0.7772302365446286, 'recall': 0.7737719299229655, 'f1-score': 0.7754762240722449, 'support': 2340}, 'weighted avg': {'precision': 0.853814209571742, 'recall': 0.8547008547008547, 'f1-score': 0.8542448856037116, 'support': 2340}}
is_others
{'0': {'precision': 0.9756657483930211, 'recall': 0.9879125987912599, 'f1-score': 0.9817509817509817, 'support': 2151}, '1': {'precision': 0.8395061728395061, 'recall': 0.7195767195767195, 'f1-score': 0.7749287749287749, 'support': 189}, 'accuracy': 0.9662393162393162, 'macro avg': {'precision': 0.9075859606162636, 'recall': 0.8537446591839897, 'f1-score': 0.8783398783398784, 'support': 2340}, 'weighted avg': {'precision': 0.9646682442136986, 'recall': 0.9662393162393162, 'f1-score': 0.9650461111999574, 'support': 2340}}

In [46]:
for col in label_aspect_train.columns:
    print(col)
    aspect_result = classification_report(df_test_true_[col], df_test_pred[col])

    print(aspect_result)

is_price
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      1999
           1       0.90      0.70      0.79       341

    accuracy                           0.94      2340
   macro avg       0.93      0.84      0.88      2340
weighted avg       0.94      0.94      0.94      2340

is_shipping
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1635
           1       0.94      0.94      0.94       705

    accuracy                           0.96      2340
   macro avg       0.96      0.96      0.96      2340
weighted avg       0.96      0.96      0.96      2340

is_outlook
              precision    recall  f1-score   support

           0       0.88      0.93      0.90      1069
           1       0.94      0.90      0.92      1271

    accuracy                           0.91      2340
   macro avg       0.91      0.91      0.91      2340
weighted avg       0.91      0.91      0.91      2340

is_quality
              precision    recall  f1-score   support

           0       0.92      0.91      0.92      1654
           1       0.79      0.81      0.80       686

    accuracy                           0.88      2340
   macro avg       0.85      0.86      0.86      2340
weighted avg       0.88      0.88      0.88      2340

is_size
              precision    recall  f1-score   support

           0       0.96      0.97      0.96      1953
           1       0.82      0.80      0.81       387

    accuracy                           0.94      2340
   macro avg       0.89      0.88      0.89      2340
weighted avg       0.94      0.94      0.94      2340

is_shopservice
              precision    recall  f1-score   support

           0       0.92      0.96      0.94      1740
           1       0.88      0.75      0.81       600

    accuracy                           0.91      2340
   macro avg       0.90      0.86      0.87      2340
weighted avg       0.91      0.91      0.91      2340

is_general
              precision    recall  f1-score   support

           0       0.91      0.91      0.91      1861
           1       0.65      0.64      0.64       479

    accuracy                           0.85      2340
   macro avg       0.78      0.77      0.78      2340
weighted avg       0.85      0.85      0.85      2340

is_others
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      2151
           1       0.84      0.72      0.77       189

    accuracy                           0.97      2340
   macro avg       0.91      0.85      0.88      2340
weighted avg       0.96      0.97      0.97      2340

In [47]:
path = '/kaggle/working/'

In [48]:
def save_result_pred_aspect(pred_aspect, true_aspect, data_eval, model_type):
    df_pred = round(pd.DataFrame(pred_aspect), 0)
    df_true = pd.DataFrame(true_aspect)
    for i, aspect in enumerate(['price', 'shipping', 'outlook', 'quality',
                              'size', 'shopservice', 'general', 'others']):
        if data_eval == 'test':
            with open(f'{path}elmo_{model_type}_aspect_test_result.txt', "a") as dest:
                dest.write("Classification report for aspect: {} \n".format(aspect.upper()))
                dest.write(classification_report(df_true[f'is_{aspect}'], df_pred[f'is_{aspect}']))
    
        elif data_eval == 'eval':
            with open(f'{path}elmo_{model_type}_aspect_val_result.txt', "a") as dest:
                dest.write("Classification report for aspect: {} \n".format(aspect.upper()))
                dest.write(classification_report(df_true[f'is_{aspect}'], df_pred[f'is_{aspect}']))
        else:
            raise('data eval is invalid')

In [49]:
save_result_pred_aspect(df_test_true_, df_test_pred, data_eval = 'test', model_type = 'bilstm')
save_result_pred_aspect(df_val_true_, df_val_pred, data_eval = 'eval', model_type = 'bilstm')

In [50]:
def bilstm_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_sentiment_size[aspect],
                  output_dim=embedding_dim,
                  embeddings_initializer=Constant(embedding_sentiment_matrix[aspect]),
                  input_length=max_len,
                  trainable=True)(input)
    lstm = Bidirectional(LSTM(units = 200, activation = 'tanh'))(embed)
    sentiment_dense2 = Dense(128, activation='relu')(lstm)
    sentiment_dropout1 = Dropout(0.2)(sentiment_dense2)
    sentiment_dense3 = Dense(64, activation='relu')(sentiment_dropout1)
    sentiment_dense4 = Dense(32, activation='relu')(sentiment_dense3)
    out_sentiment = Dense(units = 3, activation = 'softmax')(sentiment_dense4)
    
    sentiment_model_bil[aspect] = tf.keras.Model(inputs = input, outputs = out_sentiment)
    sentiment_model_bil[aspect].compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    history = sentiment_model_bil[aspect].fit(x=padded_sentiment_train[aspect],
                                          y=label_sentiment_train[aspect],
                                          validation_data=(padded_sentiment_val[aspect], label_sentiment_val[aspect]),
                                          batch_size = 128,
                                          epochs=epochs,
                                          callbacks = [callback],
                                          verbose=1)
    
    return sentiment_model_bil[aspect]

In [51]:
lst_aspect = []
for col in label_aspect_train.columns.values:
    if col!='is_others':
        lst_aspect.append(col.split('_')[1])

In [52]:
tokenized_sentiment_train = {}
tokenized_sentiment_val = {}
tokenized_sentiment_test = {}
tokenizer_sentiment = {}

for aspect in lst_aspect:
    tokenizer_sentiment[aspect], tokenized_sentiment_train[aspect], tokenized_sentiment_val[aspect], tokenized_sentiment_test[aspect] = get_tokenize(cmt_train[aspect], cmt_val[aspect], cmt_test[aspect])

padded_sentiment_train = {}
padded_sentiment_val = {}
padded_sentiment_test = {}
for aspect in lst_aspect:
    padded_sentiment_train[aspect], padded_sentiment_val[aspect], padded_sentiment_test[aspect] = get_padded(max_len, tokenized_sentiment_train[aspect], tokenized_sentiment_val[aspect], tokenized_sentiment_test[aspect])

#embedding matrix stage 2
vocab_sentiment_size = {}
embedding_sentiment_matrix = {}
for aspect in lst_aspect:
    vocab_sentiment_size[aspect]  = len(tokenizer_sentiment[aspect].word_index)+1
    embedding_sentiment_matrix[aspect] = get_embedding_matrix(embedding_dim, vocab_sentiment_size[aspect], tokenizer_sentiment[aspect])

In [53]:
sentiment_model_bil = {}
for aspect in lst_aspect:
    sentiment_model_bil[aspect] = bilstm_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val)

Epoch 1/70
10/10 [==============================] - 7s 280ms/step - loss: 0.6372 - acc: 0.5532 - val_loss: 0.5621 - val_acc: 0.7681
Epoch 2/70
10/10 [==============================] - 2s 162ms/step - loss: 0.5165 - acc: 0.7426 - val_loss: 0.4551 - val_acc: 0.7681
Epoch 3/70
10/10 [==============================] - 2s 172ms/step - loss: 0.4331 - acc: 0.7426 - val_loss: 0.3916 - val_acc: 0.7681
Epoch 4/70
10/10 [==============================] - 2s 187ms/step - loss: 0.3952 - acc: 0.7426 - val_loss: 0.3706 - val_acc: 0.7681
Epoch 5/70
10/10 [==============================] - 2s 163ms/step - loss: 0.3880 - acc: 0.7426 - val_loss: 0.3645 - val_acc: 0.7681
Epoch 6/70
10/10 [==============================] - 2s 176ms/step - loss: 0.3683 - acc: 0.7426 - val_loss: 0.3503 - val_acc: 0.7681
Epoch 7/70
10/10 [==============================] - 2s 174ms/step - loss: 0.3449 - acc: 0.7482 - val_loss: 0.3253 - val_acc: 0.7681
Epoch 8/70
10/10 [==============================] - 1s 150ms/step - loss: 0.3065 - acc: 0.7778 - val_loss: 0.2868 - val_acc: 0.8116
Epoch 9/70
10/10 [==============================] - 1s 137ms/step - loss: 0.2494 - acc: 0.8505 - val_loss: 0.2504 - val_acc: 0.8406
Epoch 10/70
10/10 [==============================] - 1s 139ms/step - loss: 0.2136 - acc: 0.8921 - val_loss: 0.2327 - val_acc: 0.8478
Epoch 11/70
10/10 [==============================] - 1s 147ms/step - loss: 0.1787 - acc: 0.8993 - val_loss: 0.2239 - val_acc: 0.8478
Epoch 12/70
10/10 [==============================] - 2s 164ms/step - loss: 0.1564 - acc: 0.9193 - val_loss: 0.2161 - val_acc: 0.8841
Epoch 13/70
10/10 [==============================] - 1s 145ms/step - loss: 0.1391 - acc: 0.9329 - val_loss: 0.2149 - val_acc: 0.8841
Epoch 14/70
10/10 [==============================] - 2s 164ms/step - loss: 0.1247 - acc: 0.9408 - val_loss: 0.2137 - val_acc: 0.8986
Epoch 15/70
10/10 [==============================] - 2s 155ms/step - loss: 0.1133 - acc: 0.9512 - val_loss: 0.2238 - val_acc: 0.8986
Epoch 16/70
10/10 [==============================] - 1s 125ms/step - loss: 0.0998 - acc: 0.9576 - val_loss: 0.2398 - val_acc: 0.8696
Epoch 17/70
10/10 [==============================] - 1s 128ms/step - loss: 0.0931 - acc: 0.9592 - val_loss: 0.2749 - val_acc: 0.8333
Epoch 1/70
20/20 [==============================] - 9s 236ms/step - loss: 0.5544 - acc: 0.7249 - val_loss: 0.4345 - val_acc: 0.7799
Epoch 2/70
20/20 [==============================] - 4s 177ms/step - loss: 0.3931 - acc: 0.7930 - val_loss: 0.3907 - val_acc: 0.7799
Epoch 3/70
20/20 [==============================] - 3s 168ms/step - loss: 0.3701 - acc: 0.7930 - val_loss: 0.3687 - val_acc: 0.7799
Epoch 4/70
20/20 [==============================] - 3s 169ms/step - loss: 0.3359 - acc: 0.7930 - val_loss: 0.3215 - val_acc: 0.7799
Epoch 5/70
20/20 [==============================] - 3s 143ms/step - loss: 0.2703 - acc: 0.8149 - val_loss: 0.2355 - val_acc: 0.8867
Epoch 6/70
20/20 [==============================] - 3s 154ms/step - loss: 0.2020 - acc: 0.9001 - val_loss: 0.1987 - val_acc: 0.9094
Epoch 7/70
20/20 [==============================] - 3s 135ms/step - loss: 0.1653 - acc: 0.9252 - val_loss: 0.1941 - val_acc: 0.9159
Epoch 8/70
20/20 [==============================] - 3s 155ms/step - loss: 0.1441 - acc: 0.9279 - val_loss: 0.1695 - val_acc: 0.9094
Epoch 9/70
20/20 [==============================] - 3s 153ms/step - loss: 0.1288 - acc: 0.9319 - val_loss: 0.1558 - val_acc: 0.9094
Epoch 10/70
20/20 [==============================] - 2s 125ms/step - loss: 0.1190 - acc: 0.9367 - val_loss: 0.1621 - val_acc: 0.9029
Epoch 11/70
20/20 [==============================] - 3s 131ms/step - loss: 0.1071 - acc: 0.9415 - val_loss: 0.1710 - val_acc: 0.9061
Epoch 12/70
20/20 [==============================] - 3s 121ms/step - loss: 0.1037 - acc: 0.9423 - val_loss: 0.1557 - val_acc: 0.9094
Epoch 13/70
20/20 [==============================] - 2s 119ms/step - loss: 0.0879 - acc: 0.9498 - val_loss: 0.1782 - val_acc: 0.9061
Epoch 14/70
20/20 [==============================] - 2s 126ms/step - loss: 0.0779 - acc: 0.9590 - val_loss: 0.1770 - val_acc: 0.8997
Epoch 15/70
20/20 [==============================] - 3s 133ms/step - loss: 0.0725 - acc: 0.9594 - val_loss: 0.1806 - val_acc: 0.8964
Epoch 1/70
36/36 [==============================] - 12s 204ms/step - loss: 0.4533 - acc: 0.8306 - val_loss: 0.2458 - val_acc: 0.9024
Epoch 2/70
36/36 [==============================] - 6s 173ms/step - loss: 0.2669 - acc: 0.8777 - val_loss: 0.2173 - val_acc: 0.9024
Epoch 3/70
36/36 [==============================] - 6s 155ms/step - loss: 0.2299 - acc: 0.8777 - val_loss: 0.1757 - val_acc: 0.9024
Epoch 4/70
36/36 [==============================] - 5s 140ms/step - loss: 0.1807 - acc: 0.8935 - val_loss: 0.1455 - val_acc: 0.9163
Epoch 5/70
36/36 [==============================] - 5s 140ms/step - loss: 0.1511 - acc: 0.9183 - val_loss: 0.1386 - val_acc: 0.9203
Epoch 6/70
36/36 [==============================] - 5s 128ms/step - loss: 0.1369 - acc: 0.9248 - val_loss: 0.1247 - val_acc: 0.9303
Epoch 7/70
36/36 [==============================] - 4s 119ms/step - loss: 0.1216 - acc: 0.9312 - val_loss: 0.1234 - val_acc: 0.9343
Epoch 8/70
36/36 [==============================] - 5s 129ms/step - loss: 0.1095 - acc: 0.9349 - val_loss: 0.1179 - val_acc: 0.9402
Epoch 9/70
36/36 [==============================] - 4s 120ms/step - loss: 0.0976 - acc: 0.9419 - val_loss: 0.1229 - val_acc: 0.9343
Epoch 10/70
36/36 [==============================] - 4s 120ms/step - loss: 0.0866 - acc: 0.9498 - val_loss: 0.1259 - val_acc: 0.9343
Epoch 11/70
36/36 [==============================] - 4s 123ms/step - loss: 0.0793 - acc: 0.9531 - val_loss: 0.1262 - val_acc: 0.9323
Epoch 1/70
20/20 [==============================] - 9s 227ms/step - loss: 0.6545 - acc: 0.5474 - val_loss: 0.5956 - val_acc: 0.6953
Epoch 2/70
20/20 [==============================] - 4s 180ms/step - loss: 0.5362 - acc: 0.7108 - val_loss: 0.4942 - val_acc: 0.6953
Epoch 3/70
20/20 [==============================] - 3s 175ms/step - loss: 0.4773 - acc: 0.7116 - val_loss: 0.4840 - val_acc: 0.6953
Epoch 4/70
20/20 [==============================] - 3s 169ms/step - loss: 0.4598 - acc: 0.7116 - val_loss: 0.4675 - val_acc: 0.6953
Epoch 5/70
20/20 [==============================] - 3s 142ms/step - loss: 0.4337 - acc: 0.7124 - val_loss: 0.4310 - val_acc: 0.6989
Epoch 6/70
20/20 [==============================] - 3s 132ms/step - loss: 0.3838 - acc: 0.7438 - val_loss: 0.3840 - val_acc: 0.7455
Epoch 7/70
20/20 [==============================] - 3s 129ms/step - loss: 0.3320 - acc: 0.7894 - val_loss: 0.3616 - val_acc: 0.7527
Epoch 8/70
20/20 [==============================] - 3s 146ms/step - loss: 0.2990 - acc: 0.8025 - val_loss: 0.3304 - val_acc: 0.7742
Epoch 9/70
20/20 [==============================] - 3s 140ms/step - loss: 0.2674 - acc: 0.8338 - val_loss: 0.3166 - val_acc: 0.7885
Epoch 10/70
20/20 [==============================] - 3s 133ms/step - loss: 0.2386 - acc: 0.8524 - val_loss: 0.3086 - val_acc: 0.7849
Epoch 11/70
20/20 [==============================] - 3s 134ms/step - loss: 0.2161 - acc: 0.8739 - val_loss: 0.3085 - val_acc: 0.8029
Epoch 12/70
20/20 [==============================] - 3s 135ms/step - loss: 0.2002 - acc: 0.8854 - val_loss: 0.3096 - val_acc: 0.8029
Epoch 13/70
20/20 [==============================] - 3s 130ms/step - loss: 0.1789 - acc: 0.9004 - val_loss: 0.3223 - val_acc: 0.7993
Epoch 14/70
20/20 [==============================] - 2s 126ms/step - loss: 0.1557 - acc: 0.9195 - val_loss: 0.3415 - val_acc: 0.7921
Epoch 1/70
12/12 [==============================] - 8s 307ms/step - loss: 0.6811 - acc: 0.4485 - val_loss: 0.6418 - val_acc: 0.4800
Epoch 2/70
12/12 [==============================] - 2s 175ms/step - loss: 0.6311 - acc: 0.4750 - val_loss: 0.6061 - val_acc: 0.5333
Epoch 3/70
12/12 [==============================] - 2s 173ms/step - loss: 0.5918 - acc: 0.5675 - val_loss: 0.5745 - val_acc: 0.5467
Epoch 4/70
12/12 [==============================] - 2s 163ms/step - loss: 0.5506 - acc: 0.6182 - val_loss: 0.5322 - val_acc: 0.6067
Epoch 5/70
12/12 [==============================] - 2s 171ms/step - loss: 0.4920 - acc: 0.6592 - val_loss: 0.4850 - val_acc: 0.6600
Epoch 6/70
12/12 [==============================] - 2s 153ms/step - loss: 0.4381 - acc: 0.6864 - val_loss: 0.4880 - val_acc: 0.6267
Epoch 7/70
12/12 [==============================] - 2s 147ms/step - loss: 0.4106 - acc: 0.6989 - val_loss: 0.4446 - val_acc: 0.6467
Epoch 8/70
12/12 [==============================] - 2s 160ms/step - loss: 0.3786 - acc: 0.7218 - val_loss: 0.4318 - val_acc: 0.6667
Epoch 9/70
12/12 [==============================] - 2s 144ms/step - loss: 0.3629 - acc: 0.7371 - val_loss: 0.4309 - val_acc: 0.6600
Epoch 10/70
12/12 [==============================] - 2s 154ms/step - loss: 0.3484 - acc: 0.7531 - val_loss: 0.4270 - val_acc: 0.6600
Epoch 11/70
12/12 [==============================] - 2s 163ms/step - loss: 0.3300 - acc: 0.7615 - val_loss: 0.4226 - val_acc: 0.6933
Epoch 12/70
12/12 [==============================] - 2s 160ms/step - loss: 0.3082 - acc: 0.7872 - val_loss: 0.4206 - val_acc: 0.6867
Epoch 13/70
12/12 [==============================] - 2s 137ms/step - loss: 0.2930 - acc: 0.8025 - val_loss: 0.4390 - val_acc: 0.7000
Epoch 14/70
12/12 [==============================] - 2s 140ms/step - loss: 0.2930 - acc: 0.8025 - val_loss: 0.4300 - val_acc: 0.7067
Epoch 15/70
12/12 [==============================] - 2s 137ms/step - loss: 0.2737 - acc: 0.8289 - val_loss: 0.4322 - val_acc: 0.7067
Epoch 1/70
18/18 [==============================] - 9s 243ms/step - loss: 0.6775 - acc: 0.6277 - val_loss: 0.6401 - val_acc: 0.7438
Epoch 2/70
18/18 [==============================] - 3s 175ms/step - loss: 0.6247 - acc: 0.7319 - val_loss: 0.5889 - val_acc: 0.7438
Epoch 3/70
18/18 [==============================] - 3s 164ms/step - loss: 0.5765 - acc: 0.7292 - val_loss: 0.5185 - val_acc: 0.7438
Epoch 4/70
18/18 [==============================] - 3s 166ms/step - loss: 0.4961 - acc: 0.7432 - val_loss: 0.4233 - val_acc: 0.7562
Epoch 5/70
18/18 [==============================] - 3s 160ms/step - loss: 0.3981 - acc: 0.7870 - val_loss: 0.3212 - val_acc: 0.8306
Epoch 6/70
18/18 [==============================] - 2s 131ms/step - loss: 0.3135 - acc: 0.8353 - val_loss: 0.2985 - val_acc: 0.8099
Epoch 7/70
18/18 [==============================] - 2s 133ms/step - loss: 0.2703 - acc: 0.8520 - val_loss: 0.2647 - val_acc: 0.8430
Epoch 8/70
18/18 [==============================] - 2s 132ms/step - loss: 0.2453 - acc: 0.8709 - val_loss: 0.2495 - val_acc: 0.8512
Epoch 9/70
18/18 [==============================] - 2s 127ms/step - loss: 0.2184 - acc: 0.8840 - val_loss: 0.2507 - val_acc: 0.8595
Epoch 10/70
18/18 [==============================] - 3s 141ms/step - loss: 0.2078 - acc: 0.8894 - val_loss: 0.2433 - val_acc: 0.8264
Epoch 11/70
18/18 [==============================] - 2s 123ms/step - loss: 0.1881 - acc: 0.9039 - val_loss: 0.2368 - val_acc: 0.8512
Epoch 12/70
18/18 [==============================] - 3s 157ms/step - loss: 0.1741 - acc: 0.9134 - val_loss: 0.2569 - val_acc: 0.8430
Epoch 13/70
18/18 [==============================] - 2s 140ms/step - loss: 0.1660 - acc: 0.9134 - val_loss: 0.2491 - val_acc: 0.8430
Epoch 14/70
18/18 [==============================] - 2s 120ms/step - loss: 0.1506 - acc: 0.9201 - val_loss: 0.2969 - val_acc: 0.8264
Epoch 1/70
13/13 [==============================] - 8s 257ms/step - loss: 0.6630 - acc: 0.5426 - val_loss: 0.6244 - val_acc: 0.5479
Epoch 2/70
13/13 [==============================] - 2s 177ms/step - loss: 0.5848 - acc: 0.5991 - val_loss: 0.5501 - val_acc: 0.5479
Epoch 3/70
13/13 [==============================] - 2s 183ms/step - loss: 0.5167 - acc: 0.6052 - val_loss: 0.5005 - val_acc: 0.5479
Epoch 4/70
13/13 [==============================] - 2s 182ms/step - loss: 0.4712 - acc: 0.6089 - val_loss: 0.4763 - val_acc: 0.5957
Epoch 5/70
13/13 [==============================] - 2s 146ms/step - loss: 0.4466 - acc: 0.6648 - val_loss: 0.4514 - val_acc: 0.6755
Epoch 6/70
13/13 [==============================] - 2s 164ms/step - loss: 0.4084 - acc: 0.7318 - val_loss: 0.4201 - val_acc: 0.7553
Epoch 7/70
13/13 [==============================] - 2s 149ms/step - loss: 0.3715 - acc: 0.7676 - val_loss: 0.3971 - val_acc: 0.7606
Epoch 8/70
13/13 [==============================] - 2s 171ms/step - loss: 0.3485 - acc: 0.7841 - val_loss: 0.4147 - val_acc: 0.7553
Epoch 9/70
13/13 [==============================] - 2s 170ms/step - loss: 0.3313 - acc: 0.7968 - val_loss: 0.3809 - val_acc: 0.7553
Epoch 10/70
13/13 [==============================] - 2s 145ms/step - loss: 0.3094 - acc: 0.8175 - val_loss: 0.3754 - val_acc: 0.7447
Epoch 11/70
13/13 [==============================] - 2s 145ms/step - loss: 0.2938 - acc: 0.8309 - val_loss: 0.3912 - val_acc: 0.7713
Epoch 12/70
13/13 [==============================] - 2s 137ms/step - loss: 0.2751 - acc: 0.8467 - val_loss: 0.4003 - val_acc: 0.7660
Epoch 13/70
13/13 [==============================] - 2s 137ms/step - loss: 0.2584 - acc: 0.8607 - val_loss: 0.4056 - val_acc: 0.7606

In [54]:
df_sentiment_train_pred = {}
df_sentiment_train_true_ = {}

df_sentiment_val_true_ = {}
df_sentiment_val_pred = {}

df_sentiment_test_true_ = {}
df_sentiment_test_pred = {}


for aspect in lst_aspect:
    pred_sentiment_train = sentiment_model_bil[aspect].predict(padded_sentiment_train[aspect])
    pred_sentiment_val = sentiment_model_bil[aspect].predict(padded_sentiment_val[aspect])
    pred_sentiment_test = sentiment_model_bil[aspect].predict(padded_sentiment_test[aspect])
    
    df_sentiment_train_pred[aspect] = np.argmax(pred_sentiment_train, axis=1)
    df_sentiment_train_true_[aspect] = np.argmax(label_sentiment_train[aspect], axis = 1)
    
    df_sentiment_val_pred[aspect] = np.argmax(pred_sentiment_val, axis=1)
    df_sentiment_val_true_[aspect] = np.argmax(label_sentiment_val[aspect], axis = 1)
    
    df_sentiment_test_pred[aspect] = np.argmax(pred_sentiment_test, axis=1)
    df_sentiment_test_true_[aspect] = np.argmax(label_sentiment_test[aspect], axis=1)

40/40 [==============================] - 1s 12ms/step
5/5 [==============================] - 0s 12ms/step
11/11 [==============================] - 0s 12ms/step
79/79 [==============================] - 2s 13ms/step
10/10 [==============================] - 0s 12ms/step
23/23 [==============================] - 0s 13ms/step
143/143 [==============================] - 2s 13ms/step
16/16 [==============================] - 0s 12ms/step
40/40 [==============================] - 1s 12ms/step
79/79 [==============================] - 2s 13ms/step
9/9 [==============================] - 0s 12ms/step
22/22 [==============================] - 0s 12ms/step
45/45 [==============================] - 1s 12ms/step
5/5 [==============================] - 0s 12ms/step
13/13 [==============================] - 0s 12ms/step
70/70 [==============================] - 2s 12ms/step
8/8 [==============================] - 0s 12ms/step
19/19 [==============================] - 0s 13ms/step
52/52 [==============================] - 1s 12ms/step
6/6 [==============================] - 0s 12ms/step
15/15 [==============================] - 0s 13ms/step

In [55]:
def get_pd_report_sentiment(df_sentiment_test_true_, df_sentiment_test_pred):
    sentiment_result_bilstm = {}
    for aspect in lst_aspect:
        sentiment_result_bilstm[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
        sentiment_result_bilstm[aspect]['aspect'] = aspect

    output_sentiment_report = pd.DataFrame()
    for indx, val in sentiment_result_bilstm.items():
        output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

    return output_aspect_report

In [56]:
sentiment_result_bilstm = {}
# for aspect in lst_aspect:
for aspect in lst_aspect:
    sentiment_result_bilstm[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
    sentiment_result_bilstm[aspect]['aspect'] = aspect

output_sentiment_report = pd.DataFrame()
for indx, val in sentiment_result_bilstm.items():
    output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [57]:
output_sentiment_report

              precision    recall  f1-score      support       aspect
0              0.000000  0.000000  0.000000     3.000000        price
1              0.944206  0.890688  0.916667   247.000000        price
2              0.731481  0.868132  0.793970    91.000000        price
accuracy       0.876833  0.876833  0.876833     0.876833        price
macro avg      0.558562  0.586273  0.570212   341.000000        price
weighted avg   0.879131  0.876833  0.875859   341.000000        price
0              0.834586  0.895161  0.863813   124.000000     shipping
1              0.961818  0.963570  0.962693   549.000000     shipping
2              0.090909  0.062500  0.074074    32.000000     shipping
accuracy       0.910638  0.910638  0.910638     0.910638     shipping
macro avg      0.629105  0.640410  0.633527   705.000000     shipping
weighted avg   0.899909  0.910638  0.904967   705.000000     shipping
0              0.757143  0.557895  0.642424    95.000000      outlook
1              0.939626  0.988372  0.963383  1118.000000      outlook
2              0.440000  0.189655  0.265060    58.000000      outlook
accuracy       0.919748  0.919748  0.919748     0.919748      outlook
macro avg      0.712256  0.578641  0.623622  1271.000000      outlook
weighted avg   0.903187  0.919748  0.907526  1271.000000      outlook
0              0.750000  0.581633  0.655172    98.000000      quality
1              0.875969  0.945607  0.909457   478.000000      quality
2              0.580645  0.495413  0.534653   109.000000      quality
accuracy       0.821898  0.821898  0.821898     0.821898      quality
macro avg      0.735538  0.674217  0.699761   685.000000      quality
weighted avg   0.810954  0.821898  0.813437   685.000000      quality
0              0.596491  0.816000  0.689189   125.000000         size
1              0.898204  0.909091  0.903614   165.000000         size
2              0.551020  0.278351  0.369863    97.000000         size
accuracy       0.720930  0.720930  0.720930     0.720930         size
macro avg      0.681905  0.667814  0.654222   387.000000         size
weighted avg   0.713731  0.720930  0.700573   387.000000         size
0              0.670391  0.857143  0.752351   140.000000  shopservice
1              0.928741  0.907193  0.917840   431.000000  shopservice
2              0.000000  0.000000  0.000000    29.000000  shopservice
accuracy       0.851667  0.851667  0.851667     0.851667  shopservice
macro avg      0.533044  0.588112  0.556730   600.000000  shopservice
weighted avg   0.823570  0.851667  0.834864   600.000000  shopservice
0              0.000000  0.000000  0.000000    11.000000      general
1              0.810127  0.898246  0.851913   285.000000      general
2              0.783951  0.697802  0.738372   182.000000      general
accuracy       0.801255  0.801255  0.801255     0.801255      general
macro avg      0.531359  0.532016  0.530095   478.000000      general
weighted avg   0.781517  0.801255  0.789078   478.000000      general

In [58]:
for aspect in lst_aspect:
    print(aspect)
    print(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist()))

price
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.94      0.89      0.92       247
           2       0.73      0.87      0.79        91

    accuracy                           0.88       341
   macro avg       0.56      0.59      0.57       341
weighted avg       0.88      0.88      0.88       341

shipping
              precision    recall  f1-score   support

           0       0.83      0.90      0.86       124
           1       0.96      0.96      0.96       549
           2       0.09      0.06      0.07        32

    accuracy                           0.91       705
   macro avg       0.63      0.64      0.63       705
weighted avg       0.90      0.91      0.90       705

outlook
              precision    recall  f1-score   support

           0       0.76      0.56      0.64        95
           1       0.94      0.99      0.96      1118
           2       0.44      0.19      0.27        58

    accuracy                           0.92      1271
   macro avg       0.71      0.58      0.62      1271
weighted avg       0.90      0.92      0.91      1271

quality
              precision    recall  f1-score   support

           0       0.75      0.58      0.66        98
           1       0.88      0.95      0.91       478
           2       0.58      0.50      0.53       109

    accuracy                           0.82       685
   macro avg       0.74      0.67      0.70       685
weighted avg       0.81      0.82      0.81       685

size
              precision    recall  f1-score   support

           0       0.60      0.82      0.69       125
           1       0.90      0.91      0.90       165
           2       0.55      0.28      0.37        97

    accuracy                           0.72       387
   macro avg       0.68      0.67      0.65       387
weighted avg       0.71      0.72      0.70       387

shopservice
              precision    recall  f1-score   support

           0       0.67      0.86      0.75       140
           1       0.93      0.91      0.92       431
           2       0.00      0.00      0.00        29

    accuracy                           0.85       600
   macro avg       0.53      0.59      0.56       600
weighted avg       0.82      0.85      0.83       600

general
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.81      0.90      0.85       285
           2       0.78      0.70      0.74       182

    accuracy                           0.80       478
   macro avg       0.53      0.53      0.53       478
weighted avg       0.78      0.80      0.79       478

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [59]:
for i in lst_aspect:
    with open(f'{path}elmo_bilstm_test_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_test_true_[i].tolist(), df_sentiment_test_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [60]:
for i in lst_aspect:
    with open(f'{path}elmo_bilstm_val_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_val_true_[i].tolist(), df_sentiment_val_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## 2. BiGRU

In [61]:
def gru_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_aspect_size,
                      output_dim=embedding_dim,
                      embeddings_initializer=Constant(embedding_aspect_matrix),
                      input_length=max_len,
                      trainable=True)(input)
    lstm = Bidirectional(GRU(units = 200, activation = 'tanh'))(embed)
    
    # aspect 
    aspect_dense2 = Dense(128, activation='relu')(lstm)
    aspect_dropout1 = Dropout(0.2)(aspect_dense2)
    aspect_dense3 = Dense(64, activation='relu')(aspect_dropout1)
    aspect_dense4 = Dense(32, activation='relu')(aspect_dense3)
    aspect_dense5 = Dense(8, activation='sigmoid')(aspect_dense4)
    
    aspect_model = tf.keras.Model(inputs = input, outputs = aspect_dense5)
    aspect_model.compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    # Fit model
    history = aspect_model.fit(x=padded_aspect_train,
                               y=label_aspect_train.to_numpy(),
                               validation_data=(padded_aspect_val, label_aspect_val.to_numpy()),
                               batch_size = 128,
                               epochs=epochs,
                               callbacks = [callback],
                               verbose=1)
    
    return aspect_model

def gru_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_sentiment_size[aspect],
                  output_dim=embedding_dim,
                  embeddings_initializer=Constant(embedding_sentiment_matrix[aspect]),
                  input_length=max_len,
                  trainable=True)(input)
    lstm = Bidirectional(GRU(units = 200, activation = 'tanh'))(embed)
    sentiment_dense2 = Dense(128, activation='relu')(lstm)
    sentiment_dropout1 = Dropout(0.2)(sentiment_dense2)
    sentiment_dense3 = Dense(64, activation='relu')(sentiment_dropout1)
    sentiment_dense4 = Dense(32, activation='relu')(sentiment_dense3)
    out_sentiment = Dense(units = 3, activation = 'softmax')(sentiment_dense4)
    
    sentiment_model_gru[aspect] = tf.keras.Model(inputs = input, outputs = out_sentiment)
    sentiment_model_gru[aspect].compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    history = sentiment_model_gru[aspect].fit(x=padded_sentiment_train[aspect],
                                          y=label_sentiment_train[aspect],
                                          validation_data=(padded_sentiment_val[aspect], label_sentiment_val[aspect]),
                                          batch_size = 128,
                                          epochs=epochs,
                                          callbacks = [callback],
                                          verbose=1)
    
    return sentiment_model_gru[aspect]

In [62]:
aspect_model_gru = gru_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val)

Epoch 1/70
66/66 [==============================] - 17s 177ms/step - loss: 0.5966 - acc: 0.2472 - val_loss: 0.5104 - val_acc: 0.3173
Epoch 2/70
66/66 [==============================] - 9s 142ms/step - loss: 0.4859 - acc: 0.3712 - val_loss: 0.4637 - val_acc: 0.4038
Epoch 3/70
66/66 [==============================] - 8s 127ms/step - loss: 0.4486 - acc: 0.4097 - val_loss: 0.4238 - val_acc: 0.4391
Epoch 4/70
66/66 [==============================] - 9s 132ms/step - loss: 0.4083 - acc: 0.4636 - val_loss: 0.3799 - val_acc: 0.4968
Epoch 5/70
66/66 [==============================] - 7s 108ms/step - loss: 0.3707 - acc: 0.4937 - val_loss: 0.3419 - val_acc: 0.5118
Epoch 6/70
66/66 [==============================] - 8s 115ms/step - loss: 0.3337 - acc: 0.5336 - val_loss: 0.3075 - val_acc: 0.5823
Epoch 7/70
66/66 [==============================] - 8s 114ms/step - loss: 0.2984 - acc: 0.5677 - val_loss: 0.2772 - val_acc: 0.5759
Epoch 8/70
66/66 [==============================] - 7s 102ms/step - loss: 0.2675 - acc: 0.5749 - val_loss: 0.2528 - val_acc: 0.5865
Epoch 9/70
66/66 [==============================] - 6s 99ms/step - loss: 0.2444 - acc: 0.5782 - val_loss: 0.2371 - val_acc: 0.6004
Epoch 10/70
66/66 [==============================] - 7s 105ms/step - loss: 0.2257 - acc: 0.6017 - val_loss: 0.2252 - val_acc: 0.5791
Epoch 11/70
66/66 [==============================] - 6s 98ms/step - loss: 0.2113 - acc: 0.6002 - val_loss: 0.2185 - val_acc: 0.5897
Epoch 12/70
66/66 [==============================] - 7s 101ms/step - loss: 0.1984 - acc: 0.6015 - val_loss: 0.2139 - val_acc: 0.5801
Epoch 13/70
66/66 [==============================] - 7s 99ms/step - loss: 0.1870 - acc: 0.6054 - val_loss: 0.2104 - val_acc: 0.5897
Epoch 14/70
66/66 [==============================] - 6s 95ms/step - loss: 0.1769 - acc: 0.6205 - val_loss: 0.2087 - val_acc: 0.5812
Epoch 15/70
66/66 [==============================] - 6s 96ms/step - loss: 0.1673 - acc: 0.6206 - val_loss: 0.2062 - val_acc: 0.5865
Epoch 16/70
66/66 [==============================] - 6s 97ms/step - loss: 0.1597 - acc: 0.6248 - val_loss: 0.2079 - val_acc: 0.5684
Epoch 17/70
66/66 [==============================] - 6s 94ms/step - loss: 0.1514 - acc: 0.6224 - val_loss: 0.2061 - val_acc: 0.5737
Epoch 18/70
66/66 [==============================] - 6s 93ms/step - loss: 0.1440 - acc: 0.6274 - val_loss: 0.2061 - val_acc: 0.5502
Epoch 19/70
66/66 [==============================] - 6s 90ms/step - loss: 0.1380 - acc: 0.6259 - val_loss: 0.2086 - val_acc: 0.5780
Epoch 20/70
66/66 [==============================] - 6s 95ms/step - loss: 0.1332 - acc: 0.6337 - val_loss: 0.2109 - val_acc: 0.5641
Epoch 21/70
66/66 [==============================] - 6s 90ms/step - loss: 0.1254 - acc: 0.6280 - val_loss: 0.2133 - val_acc: 0.5673

In [63]:
pred_train = aspect_model_gru.predict(padded_aspect_train)
pred_val = aspect_model_gru.predict(padded_aspect_val)
pred_test = aspect_model_gru.predict(padded_aspect_test)

df_train_pred = round(pd.DataFrame(pred_train), 0)
df_train_true_ = label_aspect_train
df_train_pred.columns = df_train_true_.columns

df_val_pred = round(pd.DataFrame(pred_val), 0)
df_val_true_ = label_aspect_val
df_val_pred.columns = df_val_true_.columns

df_test_pred = round(pd.DataFrame(pred_test), 0)
df_test_true_ = label_aspect_test
df_test_pred.columns = df_test_true_.columns

264/264 [==============================] - 4s 11ms/step
30/30 [==============================] - 0s 11ms/step
74/74 [==============================] - 1s 11ms/step

In [64]:
def get_pd_report(label_aspect_train, df_test_true_, df_test_pred):
    aspect_result_gru_report = {}
    for col in label_aspect_train.columns:
        aspect_result_gru_report = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
        aspect_result_gru_report[col] = pd.DataFrame(aspect_result_bilstm).T
        aspect_result_gru_report[col]['aspect'] = col
        
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_gru_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_gru_report[indx]])
    
    return output_aspect_report

In [65]:
aspect_result_gru_report = {}
for col in label_aspect_train.columns:
    print(col)
    aspect_result_gru = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
    print(aspect_result_gru)
    
    aspect_result_gru_report[col] = pd.DataFrame(aspect_result_gru).T
    aspect_result_gru_report[col]['aspect'] = col
    
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_gru_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_gru_report[indx]])

is_price
{'0': {'precision': 0.95947265625, 'recall': 0.9829914957478739, 'f1-score': 0.9710896960711637, 'support': 1999}, '1': {'precision': 0.8835616438356164, 'recall': 0.7565982404692082, 'f1-score': 0.8151658767772513, 'support': 341}, 'accuracy': 0.95, 'macro avg': {'precision': 0.9215171500428082, 'recall': 0.869794868108541, 'f1-score': 0.8931277864242075, 'support': 2340}, 'weighted avg': {'precision': 0.9484104104238013, 'recall': 0.95, 'f1-score': 0.9483674642851706, 'support': 2340}}
is_shipping
{'0': {'precision': 0.977328431372549, 'recall': 0.9755351681957186, 'f1-score': 0.9764309764309763, 'support': 1635}, '1': {'precision': 0.943502824858757, 'recall': 0.9475177304964539, 'f1-score': 0.9455060155697098, 'support': 705}, 'accuracy': 0.9670940170940171, 'macro avg': {'precision': 0.9604156281156531, 'recall': 0.9615264493460862, 'f1-score': 0.9609684960003431, 'support': 2340}, 'weighted avg': {'precision': 0.9671373832562142, 'recall': 0.9670940170940171, 'f1-score': 0.9671138407868768, 'support': 2340}}
is_outlook
{'0': {'precision': 0.9083333333333333, 'recall': 0.9176800748362957, 'f1-score': 0.9129827826896232, 'support': 1069}, '1': {'precision': 0.9301587301587302, 'recall': 0.9221085759244689, 'f1-score': 0.9261161596207033, 'support': 1271}, 'accuracy': 0.92008547008547, 'macro avg': {'precision': 0.9192460317460318, 'recall': 0.9198943253803823, 'f1-score': 0.9195494711551633, 'support': 2340}, 'weighted avg': {'precision': 0.9201880681047349, 'recall': 0.92008547008547, 'f1-score': 0.9201163391338124, 'support': 2340}}
is_quality
{'0': {'precision': 0.9218280216476248, 'recall': 0.9268440145102781, 'f1-score': 0.9243292131444076, 'support': 1654}, '1': {'precision': 0.8212703101920237, 'recall': 0.8104956268221575, 'f1-score': 0.8158473954512107, 'support': 686}, 'accuracy': 0.8927350427350428, 'macro avg': {'precision': 0.8715491659198242, 'recall': 0.8686698206662178, 'f1-score': 0.8700883042978091, 'support': 2340}, 'weighted avg': {'precision': 0.8923482823063673, 'recall': 0.8927350427350428, 'f1-score': 0.8925264238548636, 'support': 2340}}
is_size
{'0': {'precision': 0.9740663900414938, 'recall': 0.9615975422427036, 'f1-score': 0.9677918062355063, 'support': 1953}, '1': {'precision': 0.8179611650485437, 'recall': 0.8708010335917312, 'f1-score': 0.8435544430538171, 'support': 387}, 'accuracy': 0.9465811965811965, 'macro avg': {'precision': 0.8960137775450188, 'recall': 0.9161992879172174, 'f1-score': 0.9056731246446617, 'support': 2340}, 'weighted avg': {'precision': 0.9482489874465059, 'recall': 0.9465811965811965, 'f1-score': 0.9472448577093038, 'support': 2340}}
is_shopservice
{'0': {'precision': 0.9300503637381086, 'recall': 0.9551724137931035, 'f1-score': 0.9424440034023249, 'support': 1740}, '1': {'precision': 0.8589511754068716, 'recall': 0.7916666666666666, 'f1-score': 0.8239375542064181, 'support': 600}, 'accuracy': 0.9132478632478632, 'macro avg': {'precision': 0.89450076957249, 'recall': 0.873419540229885, 'f1-score': 0.8831907788043716, 'support': 2340}, 'weighted avg': {'precision': 0.9118198026275348, 'recall': 0.9132478632478632, 'f1-score': 0.9120577343777334, 'support': 2340}}
is_general
{'0': {'precision': 0.8934343434343435, 'recall': 0.9505642127888232, 'f1-score': 0.9211142931528248, 'support': 1861}, '1': {'precision': 0.7444444444444445, 'recall': 0.5594989561586639, 'f1-score': 0.6388557806912991, 'support': 479}, 'accuracy': 0.8705128205128205, 'macro avg': {'precision': 0.818939393939394, 'recall': 0.7550315844737435, 'f1-score': 0.779985036922062, 'support': 2340}, 'weighted avg': {'precision': 0.8629359837693171, 'recall': 0.8705128205128205, 'f1-score': 0.8633357344053586, 'support': 2340}}
is_others
{'0': {'precision': 0.9783010156971376, 'recall': 0.9851231985123199, 'f1-score': 0.9817002548065786, 'support': 2151}, '1': {'precision': 0.8160919540229885, 'recall': 0.7513227513227513, 'f1-score': 0.7823691460055097, 'support': 189}, 'accuracy': 0.9662393162393162, 'macro avg': {'precision': 0.8971964848600631, 'recall': 0.8682229749175356, 'f1-score': 0.8820347004060441, 'support': 2340}, 'weighted avg': {'precision': 0.9651995145619178, 'recall': 0.9662393162393162, 'f1-score': 0.9656004344803386, 'support': 2340}}

In [66]:
for col in label_aspect_train.columns:
    print(col)
    aspect_result = classification_report(df_test_true_[col], df_test_pred[col])

    print(aspect_result)

is_price
              precision    recall  f1-score   support

           0       0.96      0.98      0.97      1999
           1       0.88      0.76      0.82       341

    accuracy                           0.95      2340
   macro avg       0.92      0.87      0.89      2340
weighted avg       0.95      0.95      0.95      2340

is_shipping
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1635
           1       0.94      0.95      0.95       705

    accuracy                           0.97      2340
   macro avg       0.96      0.96      0.96      2340
weighted avg       0.97      0.97      0.97      2340

is_outlook
              precision    recall  f1-score   support

           0       0.91      0.92      0.91      1069
           1       0.93      0.92      0.93      1271

    accuracy                           0.92      2340
   macro avg       0.92      0.92      0.92      2340
weighted avg       0.92      0.92      0.92      2340

is_quality
              precision    recall  f1-score   support

           0       0.92      0.93      0.92      1654
           1       0.82      0.81      0.82       686

    accuracy                           0.89      2340
   macro avg       0.87      0.87      0.87      2340
weighted avg       0.89      0.89      0.89      2340

is_size
              precision    recall  f1-score   support

           0       0.97      0.96      0.97      1953
           1       0.82      0.87      0.84       387

    accuracy                           0.95      2340
   macro avg       0.90      0.92      0.91      2340
weighted avg       0.95      0.95      0.95      2340

is_shopservice
              precision    recall  f1-score   support

           0       0.93      0.96      0.94      1740
           1       0.86      0.79      0.82       600

    accuracy                           0.91      2340
   macro avg       0.89      0.87      0.88      2340
weighted avg       0.91      0.91      0.91      2340

is_general
              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1861
           1       0.74      0.56      0.64       479

    accuracy                           0.87      2340
   macro avg       0.82      0.76      0.78      2340
weighted avg       0.86      0.87      0.86      2340

is_others
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      2151
           1       0.82      0.75      0.78       189

    accuracy                           0.97      2340
   macro avg       0.90      0.87      0.88      2340
weighted avg       0.97      0.97      0.97      2340

In [67]:
path = '/kaggle/working/'

In [68]:
save_result_pred_aspect(df_test_true_, df_test_pred, data_eval = 'test', model_type = 'bigru')
save_result_pred_aspect(df_val_true_, df_val_pred, data_eval = 'eval', model_type = 'bigru')

In [69]:
lst_aspect = []
for col in label_aspect_train.columns.values:
    if col!='is_others':
        lst_aspect.append(col.split('_')[1])

In [70]:
sentiment_model_gru = {}
for aspect in lst_aspect:
    sentiment_model_gru[aspect] = gru_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val)

Epoch 1/70
10/10 [==============================] - 7s 269ms/step - loss: 0.5579 - acc: 0.7290 - val_loss: 0.4813 - val_acc: 0.7681
Epoch 2/70
10/10 [==============================] - 2s 184ms/step - loss: 0.4504 - acc: 0.7426 - val_loss: 0.4120 - val_acc: 0.7681
Epoch 3/70
10/10 [==============================] - 2s 162ms/step - loss: 0.4122 - acc: 0.7426 - val_loss: 0.3881 - val_acc: 0.7681
Epoch 4/70
10/10 [==============================] - 2s 159ms/step - loss: 0.3965 - acc: 0.7426 - val_loss: 0.3712 - val_acc: 0.7681
Epoch 5/70
10/10 [==============================] - 2s 160ms/step - loss: 0.3813 - acc: 0.7426 - val_loss: 0.3618 - val_acc: 0.7681
Epoch 6/70
10/10 [==============================] - 2s 167ms/step - loss: 0.3706 - acc: 0.7426 - val_loss: 0.3549 - val_acc: 0.7681
Epoch 7/70
10/10 [==============================] - 1s 143ms/step - loss: 0.3621 - acc: 0.7426 - val_loss: 0.3483 - val_acc: 0.7681
Epoch 8/70
10/10 [==============================] - 1s 131ms/step - loss: 0.3494 - acc: 0.7466 - val_loss: 0.3412 - val_acc: 0.7754
Epoch 9/70
10/10 [==============================] - 1s 139ms/step - loss: 0.3335 - acc: 0.7610 - val_loss: 0.3278 - val_acc: 0.7826
Epoch 10/70
10/10 [==============================] - 1s 141ms/step - loss: 0.3115 - acc: 0.7802 - val_loss: 0.3117 - val_acc: 0.7826
Epoch 11/70
10/10 [==============================] - 1s 140ms/step - loss: 0.2837 - acc: 0.8082 - val_loss: 0.2913 - val_acc: 0.7826
Epoch 12/70
10/10 [==============================] - 1s 126ms/step - loss: 0.2472 - acc: 0.8409 - val_loss: 0.2656 - val_acc: 0.8478
Epoch 13/70
10/10 [==============================] - 1s 119ms/step - loss: 0.2125 - acc: 0.8657 - val_loss: 0.2376 - val_acc: 0.8623
Epoch 14/70
10/10 [==============================] - 1s 153ms/step - loss: 0.1846 - acc: 0.8985 - val_loss: 0.2278 - val_acc: 0.8623
Epoch 15/70
10/10 [==============================] - 1s 117ms/step - loss: 0.1572 - acc: 0.9113 - val_loss: 0.2177 - val_acc: 0.8406
Epoch 16/70
10/10 [==============================] - 1s 130ms/step - loss: 0.1428 - acc: 0.9233 - val_loss: 0.2120 - val_acc: 0.8406
Epoch 17/70
10/10 [==============================] - 1s 120ms/step - loss: 0.1313 - acc: 0.9329 - val_loss: 0.2076 - val_acc: 0.8841
Epoch 18/70
10/10 [==============================] - 1s 107ms/step - loss: 0.1321 - acc: 0.9329 - val_loss: 0.2103 - val_acc: 0.8768
Epoch 19/70
10/10 [==============================] - 1s 118ms/step - loss: 0.1149 - acc: 0.9408 - val_loss: 0.1991 - val_acc: 0.8768
Epoch 20/70
10/10 [==============================] - 1s 106ms/step - loss: 0.1059 - acc: 0.9536 - val_loss: 0.1956 - val_acc: 0.8696
Epoch 21/70
10/10 [==============================] - 1s 118ms/step - loss: 0.0962 - acc: 0.9560 - val_loss: 0.1970 - val_acc: 0.8623
Epoch 22/70
10/10 [==============================] - 1s 100ms/step - loss: 0.0838 - acc: 0.9648 - val_loss: 0.2058 - val_acc: 0.8841
Epoch 23/70
10/10 [==============================] - 1s 131ms/step - loss: 0.0800 - acc: 0.9656 - val_loss: 0.2061 - val_acc: 0.8841
Epoch 1/70
20/20 [==============================] - 9s 208ms/step - loss: 0.5737 - acc: 0.6461 - val_loss: 0.4679 - val_acc: 0.7799
Epoch 2/70
20/20 [==============================] - 3s 159ms/step - loss: 0.4072 - acc: 0.7930 - val_loss: 0.3926 - val_acc: 0.7799
Epoch 3/70
20/20 [==============================] - 3s 162ms/step - loss: 0.3706 - acc: 0.7930 - val_loss: 0.3800 - val_acc: 0.7799
Epoch 4/70
20/20 [==============================] - 3s 147ms/step - loss: 0.3565 - acc: 0.7930 - val_loss: 0.3608 - val_acc: 0.7799
Epoch 5/70
20/20 [==============================] - 2s 125ms/step - loss: 0.3329 - acc: 0.7930 - val_loss: 0.3312 - val_acc: 0.7832
Epoch 6/70
20/20 [==============================] - 3s 129ms/step - loss: 0.2932 - acc: 0.8089 - val_loss: 0.2881 - val_acc: 0.8155
Epoch 7/70
20/20 [==============================] - 2s 125ms/step - loss: 0.2395 - acc: 0.8579 - val_loss: 0.2300 - val_acc: 0.8706
Epoch 8/70
20/20 [==============================] - 2s 126ms/step - loss: 0.1930 - acc: 0.9076 - val_loss: 0.1881 - val_acc: 0.9094
Epoch 9/70
20/20 [==============================] - 2s 112ms/step - loss: 0.1664 - acc: 0.9208 - val_loss: 0.1644 - val_acc: 0.9191
Epoch 10/70
20/20 [==============================] - 2s 116ms/step - loss: 0.1515 - acc: 0.9252 - val_loss: 0.1558 - val_acc: 0.9223
Epoch 11/70
20/20 [==============================] - 2s 111ms/step - loss: 0.1377 - acc: 0.9335 - val_loss: 0.1501 - val_acc: 0.9159
Epoch 12/70
20/20 [==============================] - 2s 111ms/step - loss: 0.1242 - acc: 0.9343 - val_loss: 0.1481 - val_acc: 0.9223
Epoch 13/70
20/20 [==============================] - 2s 97ms/step - loss: 0.1150 - acc: 0.9387 - val_loss: 0.1416 - val_acc: 0.9159
Epoch 14/70
20/20 [==============================] - 2s 107ms/step - loss: 0.1080 - acc: 0.9391 - val_loss: 0.1499 - val_acc: 0.9256
Epoch 15/70
20/20 [==============================] - 2s 108ms/step - loss: 0.0963 - acc: 0.9439 - val_loss: 0.1937 - val_acc: 0.9159
Epoch 16/70
20/20 [==============================] - 2s 107ms/step - loss: 0.1050 - acc: 0.9383 - val_loss: 0.1433 - val_acc: 0.9159
Epoch 1/70
36/36 [==============================] - 11s 188ms/step - loss: 0.4594 - acc: 0.8504 - val_loss: 0.2583 - val_acc: 0.9024
Epoch 2/70
36/36 [==============================] - 6s 159ms/step - loss: 0.2636 - acc: 0.8777 - val_loss: 0.2164 - val_acc: 0.9024
Epoch 3/70
36/36 [==============================] - 5s 129ms/step - loss: 0.2408 - acc: 0.8777 - val_loss: 0.2021 - val_acc: 0.9024
Epoch 4/70
36/36 [==============================] - 4s 118ms/step - loss: 0.2141 - acc: 0.8786 - val_loss: 0.1834 - val_acc: 0.9004
Epoch 5/70
36/36 [==============================] - 4s 109ms/step - loss: 0.1884 - acc: 0.8922 - val_loss: 0.1619 - val_acc: 0.9064
Epoch 6/70
36/36 [==============================] - 5s 141ms/step - loss: 0.1612 - acc: 0.9080 - val_loss: 0.1417 - val_acc: 0.9163
Epoch 7/70
36/36 [==============================] - 4s 104ms/step - loss: 0.1424 - acc: 0.9172 - val_loss: 0.1403 - val_acc: 0.9243
Epoch 8/70
36/36 [==============================] - 3s 91ms/step - loss: 0.1324 - acc: 0.9235 - val_loss: 0.1232 - val_acc: 0.9382
Epoch 9/70
36/36 [==============================] - 3s 96ms/step - loss: 0.1206 - acc: 0.9305 - val_loss: 0.1177 - val_acc: 0.9343
Epoch 10/70
36/36 [==============================] - 3s 96ms/step - loss: 0.1107 - acc: 0.9347 - val_loss: 0.1151 - val_acc: 0.9382
Epoch 11/70
36/36 [==============================] - 3s 93ms/step - loss: 0.1040 - acc: 0.9382 - val_loss: 0.1149 - val_acc: 0.9422
Epoch 12/70
36/36 [==============================] - 3s 94ms/step - loss: 0.0964 - acc: 0.9450 - val_loss: 0.1088 - val_acc: 0.9323
Epoch 13/70
36/36 [==============================] - 4s 101ms/step - loss: 0.0888 - acc: 0.9492 - val_loss: 0.1097 - val_acc: 0.9323
Epoch 14/70
36/36 [==============================] - 4s 106ms/step - loss: 0.0786 - acc: 0.9533 - val_loss: 0.1102 - val_acc: 0.9223
Epoch 15/70
36/36 [==============================] - 3s 90ms/step - loss: 0.0726 - acc: 0.9610 - val_loss: 0.1120 - val_acc: 0.9323
Epoch 1/70
20/20 [==============================] - 10s 215ms/step - loss: 0.5460 - acc: 0.7065 - val_loss: 0.4922 - val_acc: 0.6953
Epoch 2/70
20/20 [==============================] - 3s 164ms/step - loss: 0.4710 - acc: 0.7116 - val_loss: 0.4740 - val_acc: 0.6953
Epoch 3/70
20/20 [==============================] - 3s 160ms/step - loss: 0.4504 - acc: 0.7116 - val_loss: 0.4583 - val_acc: 0.6953
Epoch 4/70
20/20 [==============================] - 3s 145ms/step - loss: 0.4351 - acc: 0.7116 - val_loss: 0.4442 - val_acc: 0.6953
Epoch 5/70
20/20 [==============================] - 3s 135ms/step - loss: 0.4151 - acc: 0.7128 - val_loss: 0.4275 - val_acc: 0.6953
Epoch 6/70
20/20 [==============================] - 3s 125ms/step - loss: 0.3936 - acc: 0.7192 - val_loss: 0.4064 - val_acc: 0.7025
Epoch 7/70
20/20 [==============================] - 3s 123ms/step - loss: 0.3642 - acc: 0.7287 - val_loss: 0.3788 - val_acc: 0.7025
Epoch 8/70
20/20 [==============================] - 3s 132ms/step - loss: 0.3333 - acc: 0.7604 - val_loss: 0.3559 - val_acc: 0.7276
Epoch 9/70
20/20 [==============================] - 3s 122ms/step - loss: 0.3051 - acc: 0.7953 - val_loss: 0.3268 - val_acc: 0.7419
Epoch 10/70
20/20 [==============================] - 2s 120ms/step - loss: 0.2796 - acc: 0.8163 - val_loss: 0.3105 - val_acc: 0.7742
Epoch 11/70
20/20 [==============================] - 3s 123ms/step - loss: 0.2635 - acc: 0.8179 - val_loss: 0.2907 - val_acc: 0.7885
Epoch 12/70
20/20 [==============================] - 2s 102ms/step - loss: 0.2511 - acc: 0.8409 - val_loss: 0.2870 - val_acc: 0.7814
Epoch 13/70
20/20 [==============================] - 3s 129ms/step - loss: 0.2311 - acc: 0.8520 - val_loss: 0.3003 - val_acc: 0.7814
Epoch 14/70
20/20 [==============================] - 2s 115ms/step - loss: 0.2178 - acc: 0.8639 - val_loss: 0.2785 - val_acc: 0.8136
Epoch 15/70
20/20 [==============================] - 2s 101ms/step - loss: 0.2026 - acc: 0.8608 - val_loss: 0.2877 - val_acc: 0.8029
Epoch 16/70
20/20 [==============================] - 2s 101ms/step - loss: 0.1839 - acc: 0.8909 - val_loss: 0.2981 - val_acc: 0.7921
Epoch 17/70
20/20 [==============================] - 2s 111ms/step - loss: 0.1823 - acc: 0.8834 - val_loss: 0.3211 - val_acc: 0.7957
Epoch 1/70
12/12 [==============================] - 8s 261ms/step - loss: 0.6687 - acc: 0.4138 - val_loss: 0.6377 - val_acc: 0.4733
Epoch 2/70
12/12 [==============================] - 2s 181ms/step - loss: 0.6298 - acc: 0.4395 - val_loss: 0.6120 - val_acc: 0.5067
Epoch 3/70
12/12 [==============================] - 2s 165ms/step - loss: 0.6117 - acc: 0.4611 - val_loss: 0.6037 - val_acc: 0.5133
Epoch 4/70
12/12 [==============================] - 2s 162ms/step - loss: 0.5978 - acc: 0.5146 - val_loss: 0.5957 - val_acc: 0.5267
Epoch 5/70
12/12 [==============================] - 2s 147ms/step - loss: 0.5836 - acc: 0.5389 - val_loss: 0.5826 - val_acc: 0.5400
Epoch 6/70
12/12 [==============================] - 2s 140ms/step - loss: 0.5649 - acc: 0.5737 - val_loss: 0.5679 - val_acc: 0.5533
Epoch 7/70
12/12 [==============================] - 2s 154ms/step - loss: 0.5384 - acc: 0.5974 - val_loss: 0.5474 - val_acc: 0.5467
Epoch 8/70
12/12 [==============================] - 2s 161ms/step - loss: 0.5108 - acc: 0.6140 - val_loss: 0.5219 - val_acc: 0.5800
Epoch 9/70
12/12 [==============================] - 2s 163ms/step - loss: 0.4744 - acc: 0.6558 - val_loss: 0.4909 - val_acc: 0.6133
Epoch 10/70
12/12 [==============================] - 2s 126ms/step - loss: 0.4344 - acc: 0.6898 - val_loss: 0.4666 - val_acc: 0.6400
Epoch 11/70
12/12 [==============================] - 2s 133ms/step - loss: 0.3979 - acc: 0.7177 - val_loss: 0.4416 - val_acc: 0.6467
Epoch 12/70
12/12 [==============================] - 1s 125ms/step - loss: 0.3749 - acc: 0.7420 - val_loss: 0.4271 - val_acc: 0.6733
Epoch 13/70
12/12 [==============================] - 2s 139ms/step - loss: 0.3529 - acc: 0.7650 - val_loss: 0.4190 - val_acc: 0.6933
Epoch 14/70
12/12 [==============================] - 1s 104ms/step - loss: 0.3307 - acc: 0.7796 - val_loss: 0.4176 - val_acc: 0.7133
Epoch 15/70
12/12 [==============================] - 1s 112ms/step - loss: 0.3274 - acc: 0.7823 - val_loss: 0.4101 - val_acc: 0.7000
Epoch 16/70
12/12 [==============================] - 1s 95ms/step - loss: 0.3033 - acc: 0.8067 - val_loss: 0.4166 - val_acc: 0.7267
Epoch 17/70
12/12 [==============================] - 1s 111ms/step - loss: 0.2923 - acc: 0.8122 - val_loss: 0.4100 - val_acc: 0.7067
Epoch 18/70
12/12 [==============================] - 1s 116ms/step - loss: 0.2799 - acc: 0.8345 - val_loss: 0.4195 - val_acc: 0.7133
Epoch 19/70
12/12 [==============================] - 1s 110ms/step - loss: 0.2679 - acc: 0.8359 - val_loss: 0.4218 - val_acc: 0.7267
Epoch 20/70
12/12 [==============================] - 2s 135ms/step - loss: 0.2535 - acc: 0.8442 - val_loss: 0.4273 - val_acc: 0.7267
Epoch 1/70
18/18 [==============================] - 9s 225ms/step - loss: 0.6270 - acc: 0.5537 - val_loss: 0.5167 - val_acc: 0.7397
Epoch 2/70
18/18 [==============================] - 3s 170ms/step - loss: 0.4726 - acc: 0.7243 - val_loss: 0.4247 - val_acc: 0.7438
Epoch 3/70
18/18 [==============================] - 3s 158ms/step - loss: 0.4280 - acc: 0.7243 - val_loss: 0.4124 - val_acc: 0.7438
Epoch 4/70
18/18 [==============================] - 2s 136ms/step - loss: 0.4140 - acc: 0.7243 - val_loss: 0.4014 - val_acc: 0.7438
Epoch 5/70
18/18 [==============================] - 2s 130ms/step - loss: 0.4030 - acc: 0.7310 - val_loss: 0.3885 - val_acc: 0.7479
Epoch 6/70
18/18 [==============================] - 2s 135ms/step - loss: 0.3848 - acc: 0.7482 - val_loss: 0.3669 - val_acc: 0.7603
Epoch 7/70
18/18 [==============================] - 2s 136ms/step - loss: 0.3629 - acc: 0.7717 - val_loss: 0.3338 - val_acc: 0.7562
Epoch 8/70
18/18 [==============================] - 2s 125ms/step - loss: 0.3331 - acc: 0.7902 - val_loss: 0.2963 - val_acc: 0.8182
Epoch 9/70
18/18 [==============================] - 2s 123ms/step - loss: 0.3001 - acc: 0.8208 - val_loss: 0.2689 - val_acc: 0.8264
Epoch 10/70
18/18 [==============================] - 2s 108ms/step - loss: 0.2719 - acc: 0.8407 - val_loss: 0.2448 - val_acc: 0.8554
Epoch 11/70
18/18 [==============================] - 2s 113ms/step - loss: 0.2458 - acc: 0.8628 - val_loss: 0.2329 - val_acc: 0.8719
Epoch 12/70
18/18 [==============================] - 2s 118ms/step - loss: 0.2265 - acc: 0.8691 - val_loss: 0.2294 - val_acc: 0.8636
Epoch 13/70
18/18 [==============================] - 2s 114ms/step - loss: 0.2036 - acc: 0.8881 - val_loss: 0.2229 - val_acc: 0.8554
Epoch 14/70
18/18 [==============================] - 2s 108ms/step - loss: 0.1885 - acc: 0.8989 - val_loss: 0.2222 - val_acc: 0.8554
Epoch 15/70
18/18 [==============================] - 2s 97ms/step - loss: 0.1825 - acc: 0.9025 - val_loss: 0.2388 - val_acc: 0.8430
Epoch 16/70
18/18 [==============================] - 2s 115ms/step - loss: 0.1666 - acc: 0.9111 - val_loss: 0.2486 - val_acc: 0.8430
Epoch 17/70
18/18 [==============================] - 2s 108ms/step - loss: 0.1588 - acc: 0.9147 - val_loss: 0.2172 - val_acc: 0.8595
Epoch 18/70
18/18 [==============================] - 2s 100ms/step - loss: 0.1418 - acc: 0.9237 - val_loss: 0.2364 - val_acc: 0.8512
Epoch 19/70
18/18 [==============================] - 2s 107ms/step - loss: 0.1309 - acc: 0.9332 - val_loss: 0.2363 - val_acc: 0.8554
Epoch 20/70
18/18 [==============================] - 2s 100ms/step - loss: 0.1246 - acc: 0.9314 - val_loss: 0.2314 - val_acc: 0.8636
Epoch 1/70
13/13 [==============================] - 8s 243ms/step - loss: 0.6988 - acc: 0.3029 - val_loss: 0.6501 - val_acc: 0.5691
Epoch 2/70
13/13 [==============================] - 2s 165ms/step - loss: 0.6168 - acc: 0.6083 - val_loss: 0.5801 - val_acc: 0.5638
Epoch 3/70
13/13 [==============================] - 2s 154ms/step - loss: 0.5385 - acc: 0.6204 - val_loss: 0.5319 - val_acc: 0.5585
Epoch 4/70
13/13 [==============================] - 2s 157ms/step - loss: 0.4866 - acc: 0.6533 - val_loss: 0.4947 - val_acc: 0.6011
Epoch 5/70
13/13 [==============================] - 2s 140ms/step - loss: 0.4532 - acc: 0.6776 - val_loss: 0.4705 - val_acc: 0.6223
Epoch 6/70
13/13 [==============================] - 2s 134ms/step - loss: 0.4213 - acc: 0.7165 - val_loss: 0.4482 - val_acc: 0.6702
Epoch 7/70
13/13 [==============================] - 2s 141ms/step - loss: 0.4061 - acc: 0.7196 - val_loss: 0.4338 - val_acc: 0.6862
Epoch 8/70
13/13 [==============================] - 2s 160ms/step - loss: 0.3809 - acc: 0.7464 - val_loss: 0.4151 - val_acc: 0.7128
Epoch 9/70
13/13 [==============================] - 2s 117ms/step - loss: 0.3636 - acc: 0.7603 - val_loss: 0.4243 - val_acc: 0.7074
Epoch 10/70
13/13 [==============================] - 1s 118ms/step - loss: 0.3483 - acc: 0.7725 - val_loss: 0.4044 - val_acc: 0.7181
Epoch 11/70
13/13 [==============================] - 2s 126ms/step - loss: 0.3312 - acc: 0.7914 - val_loss: 0.3809 - val_acc: 0.7500
Epoch 12/70
13/13 [==============================] - 1s 103ms/step - loss: 0.3141 - acc: 0.7987 - val_loss: 0.3755 - val_acc: 0.7606
Epoch 13/70
13/13 [==============================] - 2s 125ms/step - loss: 0.3054 - acc: 0.8114 - val_loss: 0.3737 - val_acc: 0.7713
Epoch 14/70
13/13 [==============================] - 2s 133ms/step - loss: 0.2886 - acc: 0.8297 - val_loss: 0.3727 - val_acc: 0.7819
Epoch 15/70
13/13 [==============================] - 1s 117ms/step - loss: 0.2836 - acc: 0.8333 - val_loss: 0.3682 - val_acc: 0.7819
Epoch 16/70
13/13 [==============================] - 1s 101ms/step - loss: 0.2645 - acc: 0.8485 - val_loss: 0.3835 - val_acc: 0.7819
Epoch 17/70
13/13 [==============================] - 2s 118ms/step - loss: 0.2560 - acc: 0.8564 - val_loss: 0.3807 - val_acc: 0.7819
Epoch 18/70
13/13 [==============================] - 1s 112ms/step - loss: 0.2413 - acc: 0.8668 - val_loss: 0.3944 - val_acc: 0.7766

In [71]:
df_sentiment_train_pred = {}
df_sentiment_train_true_ = {}

df_sentiment_val_true_ = {}
df_sentiment_val_pred = {}

df_sentiment_test_true_ = {}
df_sentiment_test_pred = {}


for aspect in lst_aspect:
    pred_sentiment_train = sentiment_model_gru[aspect].predict(padded_sentiment_train[aspect])
    pred_sentiment_val = sentiment_model_gru[aspect].predict(padded_sentiment_val[aspect])
    pred_sentiment_test = sentiment_model_gru[aspect].predict(padded_sentiment_test[aspect])
    
    df_sentiment_train_pred[aspect] = np.argmax(pred_sentiment_train, axis=1)
    df_sentiment_train_true_[aspect] = np.argmax(label_sentiment_train[aspect], axis = 1)
    
    df_sentiment_val_pred[aspect] = np.argmax(pred_sentiment_val, axis=1)
    df_sentiment_val_true_[aspect] = np.argmax(label_sentiment_val[aspect], axis = 1)
    
    df_sentiment_test_pred[aspect] = np.argmax(pred_sentiment_test, axis=1)
    df_sentiment_test_true_[aspect] = np.argmax(label_sentiment_test[aspect], axis=1)

40/40 [==============================] - 1s 11ms/step
5/5 [==============================] - 0s 10ms/step
11/11 [==============================] - 0s 11ms/step
79/79 [==============================] - 1s 11ms/step
10/10 [==============================] - 0s 10ms/step
23/23 [==============================] - 0s 11ms/step
143/143 [==============================] - 2s 11ms/step
16/16 [==============================] - 0s 11ms/step
40/40 [==============================] - 0s 11ms/step
79/79 [==============================] - 1s 11ms/step
9/9 [==============================] - 0s 10ms/step
22/22 [==============================] - 0s 11ms/step
45/45 [==============================] - 1s 11ms/step
5/5 [==============================] - 0s 10ms/step
13/13 [==============================] - 0s 11ms/step
70/70 [==============================] - 1s 11ms/step
8/8 [==============================] - 0s 10ms/step
19/19 [==============================] - 0s 11ms/step
52/52 [==============================] - 1s 11ms/step
6/6 [==============================] - 0s 10ms/step
15/15 [==============================] - 0s 11ms/step

In [72]:
def get_pd_report_sentiment(df_sentiment_test_true_, df_sentiment_test_pred):
    sentiment_result_bilstm = {}
    for aspect in lst_aspect:
        sentiment_result_bilstm[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
        sentiment_result_bilstm[aspect]['aspect'] = aspect

    output_sentiment_report = pd.DataFrame()
    for indx, val in sentiment_result_bilstm.items():
        output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

    return output_aspect_report

In [73]:
sentiment_result_gru = {}
# for aspect in lst_aspect:
for aspect in lst_aspect:
    sentiment_result_gru[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
    sentiment_result_gru[aspect]['aspect'] = aspect

output_sentiment_report = pd.DataFrame()
for indx, val in sentiment_result_bilstm.items():
    output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [74]:
output_sentiment_report

              precision    recall  f1-score      support       aspect
0              0.000000  0.000000  0.000000     3.000000        price
1              0.944206  0.890688  0.916667   247.000000        price
2              0.731481  0.868132  0.793970    91.000000        price
accuracy       0.876833  0.876833  0.876833     0.876833        price
macro avg      0.558562  0.586273  0.570212   341.000000        price
weighted avg   0.879131  0.876833  0.875859   341.000000        price
0              0.834586  0.895161  0.863813   124.000000     shipping
1              0.961818  0.963570  0.962693   549.000000     shipping
2              0.090909  0.062500  0.074074    32.000000     shipping
accuracy       0.910638  0.910638  0.910638     0.910638     shipping
macro avg      0.629105  0.640410  0.633527   705.000000     shipping
weighted avg   0.899909  0.910638  0.904967   705.000000     shipping
0              0.757143  0.557895  0.642424    95.000000      outlook
1              0.939626  0.988372  0.963383  1118.000000      outlook
2              0.440000  0.189655  0.265060    58.000000      outlook
accuracy       0.919748  0.919748  0.919748     0.919748      outlook
macro avg      0.712256  0.578641  0.623622  1271.000000      outlook
weighted avg   0.903187  0.919748  0.907526  1271.000000      outlook
0              0.750000  0.581633  0.655172    98.000000      quality
1              0.875969  0.945607  0.909457   478.000000      quality
2              0.580645  0.495413  0.534653   109.000000      quality
accuracy       0.821898  0.821898  0.821898     0.821898      quality
macro avg      0.735538  0.674217  0.699761   685.000000      quality
weighted avg   0.810954  0.821898  0.813437   685.000000      quality
0              0.596491  0.816000  0.689189   125.000000         size
1              0.898204  0.909091  0.903614   165.000000         size
2              0.551020  0.278351  0.369863    97.000000         size
accuracy       0.720930  0.720930  0.720930     0.720930         size
macro avg      0.681905  0.667814  0.654222   387.000000         size
weighted avg   0.713731  0.720930  0.700573   387.000000         size
0              0.670391  0.857143  0.752351   140.000000  shopservice
1              0.928741  0.907193  0.917840   431.000000  shopservice
2              0.000000  0.000000  0.000000    29.000000  shopservice
accuracy       0.851667  0.851667  0.851667     0.851667  shopservice
macro avg      0.533044  0.588112  0.556730   600.000000  shopservice
weighted avg   0.823570  0.851667  0.834864   600.000000  shopservice
0              0.000000  0.000000  0.000000    11.000000      general
1              0.810127  0.898246  0.851913   285.000000      general
2              0.783951  0.697802  0.738372   182.000000      general
accuracy       0.801255  0.801255  0.801255     0.801255      general
macro avg      0.531359  0.532016  0.530095   478.000000      general
weighted avg   0.781517  0.801255  0.789078   478.000000      general

In [75]:
for aspect in lst_aspect:
    print(aspect)
    print(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist()))

price
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.90      0.91      0.91       247
           2       0.77      0.77      0.77        91

    accuracy                           0.87       341
   macro avg       0.56      0.56      0.56       341
weighted avg       0.86      0.87      0.86       341

shipping
              precision    recall  f1-score   support

           0       0.80      0.94      0.86       124
           1       0.96      0.97      0.96       549
           2       0.00      0.00      0.00        32

    accuracy                           0.92       705
   macro avg       0.58      0.64      0.61       705
weighted avg       0.89      0.92      0.90       705

outlook
              precision    recall  f1-score   support

           0       0.70      0.78      0.74        95
           1       0.97      0.96      0.97      1118
           2       0.30      0.28      0.29        58

    accuracy                           0.92      1271
   macro avg       0.65      0.67      0.66      1271
weighted avg       0.92      0.92      0.92      1271

quality
              precision    recall  f1-score   support

           0       0.65      0.53      0.58        98
           1       0.85      0.95      0.90       478
           2       0.50      0.33      0.40       109

    accuracy                           0.79       685
   macro avg       0.67      0.60      0.63       685
weighted avg       0.77      0.79      0.77       685

size
              precision    recall  f1-score   support

           0       0.67      0.66      0.66       125
           1       0.84      0.95      0.89       165
           2       0.53      0.43      0.47        97

    accuracy                           0.72       387
   macro avg       0.68      0.68      0.68       387
weighted avg       0.71      0.72      0.71       387

shopservice
              precision    recall  f1-score   support

           0       0.76      0.87      0.81       140
           1       0.93      0.95      0.94       431
           2       0.00      0.00      0.00        29

    accuracy                           0.89       600
   macro avg       0.56      0.61      0.58       600
weighted avg       0.85      0.89      0.86       600

general
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.79      0.90      0.84       285
           2       0.78      0.66      0.72       182

    accuracy                           0.79       478
   macro avg       0.53      0.52      0.52       478
weighted avg       0.77      0.79      0.78       478

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [76]:
for i in lst_aspect:
    with open(f'{path}elmo_bigru_test_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_test_true_[i].tolist(), df_sentiment_test_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [77]:
for i in lst_aspect:
    with open(f'{path}elmo_bigru_val_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_val_true_[i].tolist(), df_sentiment_val_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## 3. BiLSTM + Conv1D

In [78]:
def bilstm_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_aspect_size,
                      output_dim=embedding_dim,
                      embeddings_initializer=Constant(embedding_aspect_matrix),
                      input_length=max_len,
                      trainable=True)(input)
    dropout1 = SpatialDropout1D(0.2)(embed)

    lstm = Bidirectional(LSTM(units = 200, activation = 'tanh', return_sequences = True))(dropout1)
    conv = Conv1D(128, kernel_size = 2, padding = "valid", kernel_initializer = "he_uniform")(lstm)

    avg_pool1 = GlobalAveragePooling1D()(conv)
    max_pool1 = GlobalMaxPooling1D()(conv)
    
    concat = Concatenate(axis=-1)([avg_pool1, max_pool1])
    dense2 = Dense(units = 128, activation = 'relu')(concat)
    dropout1 = Dropout(rate = 0.2)(dense2)
    dense3 = Dense(units = 64, activation = 'relu')(dropout1)
    dense4 = Dense(units = 32, activation = 'relu')(dense3)
    out_aspect = Dense(units = 8, activation = 'sigmoid', name='out_aspect')(dense4)
    
    aspect_model = tf.keras.Model(inputs = input, outputs = out_aspect)
    aspect_model.compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    # Fit model
    history = aspect_model.fit(x=padded_aspect_train,
                               y=label_aspect_train.to_numpy(),
                               validation_data=(padded_aspect_val, label_aspect_val.to_numpy()),
                               batch_size = 128,
                               epochs=epochs,
                               callbacks = [callback],
                               verbose=1)
    
    return aspect_model

def bilstm_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_sentiment_size[aspect],
                  output_dim=embedding_dim,
                  embeddings_initializer=Constant(embedding_sentiment_matrix[aspect]),
                  input_length=max_len,
                  trainable=True)(input)
  
    dropout1 = SpatialDropout1D(0.2)(embed)
    lstm = Bidirectional(LSTM(units = 200, activation = 'tanh', return_sequences = True))(dropout1)
    conv = Conv1D(128, kernel_size = 2, padding = "valid", kernel_initializer = "he_uniform")(lstm)

    avg_pool1 = GlobalAveragePooling1D()(conv)
    max_pool1 = GlobalMaxPooling1D()(conv)
      
      
    concat = Concatenate(axis=-1)([avg_pool1, max_pool1])

    sentiment_dense2 = Dense(128, activation='relu')(concat)
    sentiment_dropout1 = Dropout(0.2)(sentiment_dense2)
    sentiment_dense3 = Dense(64, activation='relu')(sentiment_dropout1)
    sentiment_dense4 = Dense(32, activation='relu')(sentiment_dense3)
    out_sentiment = Dense(units = 3, activation = 'softmax')(sentiment_dense4)
    
    sentiment_model_bil_con[aspect] = tf.keras.Model(inputs = input, outputs = out_sentiment)
    sentiment_model_bil_con[aspect].compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    history = sentiment_model_bil_con[aspect].fit(x=padded_sentiment_train[aspect],
                                          y=label_sentiment_train[aspect],
                                          validation_data=(padded_sentiment_val[aspect], label_sentiment_val[aspect]),
                                          batch_size = 128,
                                          epochs=epochs,
                                          callbacks = [callback],
                                          verbose=1)
    
    return sentiment_model_bil_con[aspect]

In [79]:
aspect_model_bil_con = bilstm_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val)

Epoch 1/70
66/66 [==============================] - 23s 196ms/step - loss: 0.5915 - acc: 0.2793 - val_loss: 0.5016 - val_acc: 0.2842
Epoch 2/70
66/66 [==============================] - 11s 169ms/step - loss: 0.4636 - acc: 0.3852 - val_loss: 0.3907 - val_acc: 0.5235
Epoch 3/70
66/66 [==============================] - 11s 167ms/step - loss: 0.3791 - acc: 0.5089 - val_loss: 0.3186 - val_acc: 0.5513
Epoch 4/70
66/66 [==============================] - 10s 159ms/step - loss: 0.3252 - acc: 0.5313 - val_loss: 0.2854 - val_acc: 0.5940
Epoch 5/70
66/66 [==============================] - 10s 148ms/step - loss: 0.2887 - acc: 0.5459 - val_loss: 0.2549 - val_acc: 0.5459
Epoch 6/70
66/66 [==============================] - 9s 143ms/step - loss: 0.2630 - acc: 0.5399 - val_loss: 0.2405 - val_acc: 0.5769
Epoch 7/70
66/66 [==============================] - 9s 139ms/step - loss: 0.2440 - acc: 0.5493 - val_loss: 0.2289 - val_acc: 0.5780
Epoch 8/70
66/66 [==============================] - 9s 143ms/step - loss: 0.2283 - acc: 0.5488 - val_loss: 0.2220 - val_acc: 0.5459
Epoch 9/70
66/66 [==============================] - 9s 138ms/step - loss: 0.2148 - acc: 0.5666 - val_loss: 0.2143 - val_acc: 0.5534
Epoch 10/70
66/66 [==============================] - 9s 139ms/step - loss: 0.2042 - acc: 0.5704 - val_loss: 0.2116 - val_acc: 0.5801
Epoch 11/70
66/66 [==============================] - 9s 133ms/step - loss: 0.1952 - acc: 0.5820 - val_loss: 0.2037 - val_acc: 0.5620
Epoch 12/70
66/66 [==============================] - 9s 133ms/step - loss: 0.1860 - acc: 0.5869 - val_loss: 0.2038 - val_acc: 0.5769
Epoch 13/70
66/66 [==============================] - 9s 135ms/step - loss: 0.1800 - acc: 0.5859 - val_loss: 0.2031 - val_acc: 0.5566
Epoch 14/70
66/66 [==============================] - 9s 133ms/step - loss: 0.1718 - acc: 0.5838 - val_loss: 0.1995 - val_acc: 0.5780
Epoch 15/70
66/66 [==============================] - 9s 131ms/step - loss: 0.1669 - acc: 0.5984 - val_loss: 0.1976 - val_acc: 0.5652
Epoch 16/70
66/66 [==============================] - 9s 131ms/step - loss: 0.1613 - acc: 0.6052 - val_loss: 0.1974 - val_acc: 0.5363
Epoch 17/70
66/66 [==============================] - 8s 128ms/step - loss: 0.1572 - acc: 0.6021 - val_loss: 0.1969 - val_acc: 0.5705
Epoch 18/70
66/66 [==============================] - 9s 132ms/step - loss: 0.1513 - acc: 0.6070 - val_loss: 0.1979 - val_acc: 0.5652
Epoch 19/70
66/66 [==============================] - 9s 133ms/step - loss: 0.1456 - acc: 0.6112 - val_loss: 0.1988 - val_acc: 0.5748
Epoch 20/70
66/66 [==============================] - 9s 133ms/step - loss: 0.1406 - acc: 0.6147 - val_loss: 0.2033 - val_acc: 0.5726

In [80]:
pred_train = aspect_model_bil_con.predict(padded_aspect_train)
pred_val = aspect_model_bil_con.predict(padded_aspect_val)
pred_test = aspect_model_bil_con.predict(padded_aspect_test)

df_train_pred = round(pd.DataFrame(pred_train), 0)
df_train_true_ = label_aspect_train
df_train_pred.columns = df_train_true_.columns

df_val_pred = round(pd.DataFrame(pred_val), 0)
df_val_true_ = label_aspect_val
df_val_pred.columns = df_val_true_.columns

df_test_pred = round(pd.DataFrame(pred_test), 0)
df_test_true_ = label_aspect_test
df_test_pred.columns = df_test_true_.columns

264/264 [==============================] - 4s 14ms/step
30/30 [==============================] - 0s 13ms/step
74/74 [==============================] - 1s 14ms/step

In [81]:
def get_pd_report(label_aspect_train, df_test_true_, df_test_pred):
    aspect_result_bilstm_report = {}
    for col in label_aspect_train.columns:
        aspect_result_bilstm = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
        aspect_result_bilstm_report[col] = pd.DataFrame(aspect_result_bilstm).T
        aspect_result_bilstm_report[col]['aspect'] = col
        
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_bilstm_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_bilstm_report[indx]])
    
    return output_aspect_report

In [82]:
aspect_result_bilstm_report = {}
for col in label_aspect_train.columns:
    print(col)
    aspect_result_bilstm = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
    print(aspect_result_bilstm)
    
    aspect_result_bilstm_report[col] = pd.DataFrame(aspect_result_bilstm).T
    aspect_result_bilstm_report[col]['aspect'] = col
    
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_bilstm_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_bilstm_report[indx]])

is_price
{'0': {'precision': 0.9580896686159844, 'recall': 0.9834917458729364, 'f1-score': 0.9706245371513207, 'support': 1999}, '1': {'precision': 0.8854166666666666, 'recall': 0.7478005865102639, 'f1-score': 0.8108108108108107, 'support': 341}, 'accuracy': 0.9491452991452991, 'macro avg': {'precision': 0.9217531676413255, 'recall': 0.8656461661916002, 'f1-score': 0.8907176739810657, 'support': 2340}, 'weighted avg': {'precision': 0.9474992867079856, 'recall': 0.9491452991452991, 'f1-score': 0.947335442842725, 'support': 2340}}
is_shipping
{'0': {'precision': 0.9821208384710234, 'recall': 0.9743119266055046, 'f1-score': 0.9782007982806263, 'support': 1635}, '1': {'precision': 0.9415041782729805, 'recall': 0.9588652482269504, 'f1-score': 0.9501054111033029, 'support': 705}, 'accuracy': 0.9696581196581197, 'macro avg': {'precision': 0.9618125083720019, 'recall': 0.9665885874162274, 'f1-score': 0.9641531046919647, 'support': 2340}, 'weighted avg': {'precision': 0.9698837677703309, 'recall': 0.9696581196581197, 'f1-score': 0.9697361624002788, 'support': 2340}}
is_outlook
{'0': {'precision': 0.9490316004077471, 'recall': 0.8709073900841908, 'f1-score': 0.9082926829268293, 'support': 1069}, '1': {'precision': 0.8984547461368654, 'recall': 0.96066089693155, 'f1-score': 0.9285171102661597, 'support': 1271}, 'accuracy': 0.9196581196581196, 'macro avg': {'precision': 0.9237431732723063, 'recall': 0.9157841435078704, 'f1-score': 0.9184048965964945, 'support': 2340}, 'weighted avg': {'precision': 0.9215601552033493, 'recall': 0.9196581196581196, 'f1-score': 0.9192778312807989, 'support': 2340}}
is_quality
{'0': {'precision': 0.9163701067615658, 'recall': 0.93409915356711, 'f1-score': 0.9251497005988024, 'support': 1654}, '1': {'precision': 0.8333333333333334, 'recall': 0.7944606413994169, 'f1-score': 0.8134328358208956, 'support': 686}, 'accuracy': 0.8931623931623932, 'macro avg': {'precision': 0.8748517200474496, 'recall': 0.8642798974832635, 'f1-score': 0.869291268209849, 'support': 2340}, 'weighted avg': {'precision': 0.8920268475428618, 'recall': 0.8931623931623932, 'f1-score': 0.8923985171639118, 'support': 2340}}
is_size
{'0': {'precision': 0.9733196511031298, 'recall': 0.9713261648745519, 'f1-score': 0.9723218862121987, 'support': 1953}, '1': {'precision': 0.8567774936061381, 'recall': 0.8656330749354005, 'f1-score': 0.8611825192802056, 'support': 387}, 'accuracy': 0.9538461538461539, 'macro avg': {'precision': 0.915048572354634, 'recall': 0.9184796199049763, 'f1-score': 0.9167522027462022, 'support': 2340}, 'weighted avg': {'precision': 0.9540453712093965, 'recall': 0.9538461538461539, 'f1-score': 0.9539411447580615, 'support': 2340}}
is_shopservice
{'0': {'precision': 0.9344444444444444, 'recall': 0.9666666666666667, 'f1-score': 0.9502824858757062, 'support': 1740}, '1': {'precision': 0.8925925925925926, 'recall': 0.8033333333333333, 'f1-score': 0.8456140350877193, 'support': 600}, 'accuracy': 0.9247863247863248, 'macro avg': {'precision': 0.9135185185185185, 'recall': 0.885, 'f1-score': 0.8979482604817127, 'support': 2340}, 'weighted avg': {'precision': 0.9237132003798669, 'recall': 0.9247863247863248, 'f1-score': 0.9234444215710941, 'support': 2340}}
is_general
{'0': {'precision': 0.9024767801857585, 'recall': 0.9398173025255239, 'f1-score': 0.9207686233219268, 'support': 1861}, '1': {'precision': 0.7213930348258707, 'recall': 0.605427974947808, 'f1-score': 0.6583427922814984, 'support': 479}, 'accuracy': 0.8713675213675214, 'macro avg': {'precision': 0.8119349075058147, 'recall': 0.7726226387366659, 'f1-score': 0.7895557078017126, 'support': 2340}, 'weighted avg': {'precision': 0.8654087827381576, 'recall': 0.8713675213675214, 'f1-score': 0.867049831412369, 'support': 2340}}
is_others
{'0': {'precision': 0.9713114754098361, 'recall': 0.9916317991631799, 'f1-score': 0.9813664596273292, 'support': 2151}, '1': {'precision': 0.875, 'recall': 0.6666666666666666, 'f1-score': 0.7567567567567567, 'support': 189}, 'accuracy': 0.9653846153846154, 'macro avg': {'precision': 0.923155737704918, 'recall': 0.8291492329149233, 'f1-score': 0.8690616081920429, 'support': 2340}, 'weighted avg': {'precision': 0.9635324716267339, 'recall': 0.9653846153846154, 'f1-score': 0.9632249067031675, 'support': 2340}}

In [83]:
for col in label_aspect_train.columns:
    print(col)
    aspect_result = classification_report(df_test_true_[col], df_test_pred[col])

    print(aspect_result)

is_price
              precision    recall  f1-score   support

           0       0.96      0.98      0.97      1999
           1       0.89      0.75      0.81       341

    accuracy                           0.95      2340
   macro avg       0.92      0.87      0.89      2340
weighted avg       0.95      0.95      0.95      2340

is_shipping
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1635
           1       0.94      0.96      0.95       705

    accuracy                           0.97      2340
   macro avg       0.96      0.97      0.96      2340
weighted avg       0.97      0.97      0.97      2340

is_outlook
              precision    recall  f1-score   support

           0       0.95      0.87      0.91      1069
           1       0.90      0.96      0.93      1271

    accuracy                           0.92      2340
   macro avg       0.92      0.92      0.92      2340
weighted avg       0.92      0.92      0.92      2340

is_quality
              precision    recall  f1-score   support

           0       0.92      0.93      0.93      1654
           1       0.83      0.79      0.81       686

    accuracy                           0.89      2340
   macro avg       0.87      0.86      0.87      2340
weighted avg       0.89      0.89      0.89      2340

is_size
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1953
           1       0.86      0.87      0.86       387

    accuracy                           0.95      2340
   macro avg       0.92      0.92      0.92      2340
weighted avg       0.95      0.95      0.95      2340

is_shopservice
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      1740
           1       0.89      0.80      0.85       600

    accuracy                           0.92      2340
   macro avg       0.91      0.89      0.90      2340
weighted avg       0.92      0.92      0.92      2340

is_general
              precision    recall  f1-score   support

           0       0.90      0.94      0.92      1861
           1       0.72      0.61      0.66       479

    accuracy                           0.87      2340
   macro avg       0.81      0.77      0.79      2340
weighted avg       0.87      0.87      0.87      2340

is_others
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      2151
           1       0.88      0.67      0.76       189

    accuracy                           0.97      2340
   macro avg       0.92      0.83      0.87      2340
weighted avg       0.96      0.97      0.96      2340

In [84]:
path = '/kaggle/working/'

In [85]:
save_result_pred_aspect(df_test_true_, df_test_pred, data_eval = 'test', model_type = 'bilstm_con')
save_result_pred_aspect(df_val_true_, df_val_pred, data_eval = 'eval', model_type = 'bilstm_con')

In [86]:
lst_aspect = []
for col in label_aspect_train.columns.values:
    if col!='is_others':
        lst_aspect.append(col.split('_')[1])

In [87]:
sentiment_model_bil_con = {}
for aspect in lst_aspect:
    sentiment_model_bil_con[aspect] = bilstm_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val)

Epoch 1/70
10/10 [==============================] - 8s 301ms/step - loss: 0.6680 - acc: 0.5372 - val_loss: 0.5658 - val_acc: 0.7681
Epoch 2/70
10/10 [==============================] - 2s 191ms/step - loss: 0.5349 - acc: 0.7426 - val_loss: 0.4600 - val_acc: 0.7681
Epoch 3/70
10/10 [==============================] - 2s 193ms/step - loss: 0.4634 - acc: 0.7426 - val_loss: 0.4222 - val_acc: 0.7681
Epoch 4/70
10/10 [==============================] - 2s 183ms/step - loss: 0.4338 - acc: 0.7426 - val_loss: 0.4015 - val_acc: 0.7681
Epoch 5/70
10/10 [==============================] - 2s 182ms/step - loss: 0.4094 - acc: 0.7426 - val_loss: 0.3706 - val_acc: 0.7681
Epoch 6/70
10/10 [==============================] - 2s 185ms/step - loss: 0.3695 - acc: 0.7426 - val_loss: 0.3352 - val_acc: 0.7681
Epoch 7/70
10/10 [==============================] - 2s 186ms/step - loss: 0.3310 - acc: 0.7426 - val_loss: 0.2962 - val_acc: 0.7681
Epoch 8/70
10/10 [==============================] - 2s 159ms/step - loss: 0.2937 - acc: 0.7458 - val_loss: 0.2661 - val_acc: 0.7899
Epoch 9/70
10/10 [==============================] - 2s 171ms/step - loss: 0.2584 - acc: 0.8129 - val_loss: 0.2426 - val_acc: 0.8478
Epoch 10/70
10/10 [==============================] - 1s 146ms/step - loss: 0.2375 - acc: 0.8425 - val_loss: 0.2263 - val_acc: 0.8696
Epoch 11/70
10/10 [==============================] - 2s 164ms/step - loss: 0.2152 - acc: 0.8857 - val_loss: 0.2136 - val_acc: 0.8696
Epoch 12/70
10/10 [==============================] - 2s 170ms/step - loss: 0.1972 - acc: 0.9009 - val_loss: 0.2055 - val_acc: 0.8768
Epoch 13/70
10/10 [==============================] - 2s 162ms/step - loss: 0.1899 - acc: 0.8961 - val_loss: 0.2105 - val_acc: 0.8478
Epoch 14/70
10/10 [==============================] - 2s 162ms/step - loss: 0.1766 - acc: 0.8985 - val_loss: 0.1910 - val_acc: 0.8986
Epoch 15/70
10/10 [==============================] - 2s 162ms/step - loss: 0.1654 - acc: 0.9145 - val_loss: 0.1891 - val_acc: 0.8841
Epoch 16/70
10/10 [==============================] - 2s 150ms/step - loss: 0.1553 - acc: 0.9225 - val_loss: 0.1929 - val_acc: 0.8841
Epoch 17/70
10/10 [==============================] - 2s 155ms/step - loss: 0.1428 - acc: 0.9249 - val_loss: 0.1948 - val_acc: 0.8696
Epoch 18/70
10/10 [==============================] - 1s 143ms/step - loss: 0.1316 - acc: 0.9400 - val_loss: 0.1916 - val_acc: 0.8841
Epoch 1/70
20/20 [==============================] - 10s 256ms/step - loss: 0.6622 - acc: 0.6111 - val_loss: 0.5725 - val_acc: 0.7799
Epoch 2/70
20/20 [==============================] - 4s 183ms/step - loss: 0.5084 - acc: 0.7962 - val_loss: 0.4016 - val_acc: 0.7799
Epoch 3/70
20/20 [==============================] - 4s 182ms/step - loss: 0.3512 - acc: 0.8121 - val_loss: 0.2674 - val_acc: 0.8414
Epoch 4/70
20/20 [==============================] - 3s 176ms/step - loss: 0.2454 - acc: 0.8838 - val_loss: 0.1998 - val_acc: 0.9061
Epoch 5/70
20/20 [==============================] - 3s 171ms/step - loss: 0.1934 - acc: 0.9144 - val_loss: 0.1719 - val_acc: 0.9094
Epoch 6/70
20/20 [==============================] - 3s 160ms/step - loss: 0.1712 - acc: 0.9200 - val_loss: 0.1578 - val_acc: 0.9126
Epoch 7/70
20/20 [==============================] - 3s 151ms/step - loss: 0.1598 - acc: 0.9232 - val_loss: 0.1514 - val_acc: 0.9126
Epoch 8/70
20/20 [==============================] - 3s 150ms/step - loss: 0.1486 - acc: 0.9279 - val_loss: 0.1465 - val_acc: 0.9126
Epoch 9/70
20/20 [==============================] - 3s 141ms/step - loss: 0.1382 - acc: 0.9295 - val_loss: 0.1435 - val_acc: 0.9223
Epoch 10/70
20/20 [==============================] - 3s 159ms/step - loss: 0.1329 - acc: 0.9299 - val_loss: 0.1396 - val_acc: 0.9191
Epoch 11/70
20/20 [==============================] - 3s 133ms/step - loss: 0.1225 - acc: 0.9359 - val_loss: 0.1446 - val_acc: 0.9288
Epoch 12/70
20/20 [==============================] - 3s 138ms/step - loss: 0.1142 - acc: 0.9379 - val_loss: 0.1349 - val_acc: 0.9288
Epoch 13/70
20/20 [==============================] - 3s 159ms/step - loss: 0.1079 - acc: 0.9415 - val_loss: 0.1445 - val_acc: 0.9223
Epoch 14/70
20/20 [==============================] - 3s 136ms/step - loss: 0.1012 - acc: 0.9423 - val_loss: 0.1352 - val_acc: 0.9288
Epoch 15/70
20/20 [==============================] - 3s 131ms/step - loss: 0.0954 - acc: 0.9486 - val_loss: 0.1367 - val_acc: 0.9191
Epoch 1/70
36/36 [==============================] - 13s 217ms/step - loss: 0.3576 - acc: 0.8777 - val_loss: 0.2179 - val_acc: 0.9024
Epoch 2/70
36/36 [==============================] - 6s 172ms/step - loss: 0.2360 - acc: 0.8777 - val_loss: 0.1775 - val_acc: 0.9024
Epoch 3/70
36/36 [==============================] - 6s 171ms/step - loss: 0.1921 - acc: 0.8777 - val_loss: 0.1488 - val_acc: 0.9044
Epoch 4/70
36/36 [==============================] - 6s 166ms/step - loss: 0.1616 - acc: 0.9038 - val_loss: 0.1309 - val_acc: 0.9343
Epoch 5/70
36/36 [==============================] - 5s 144ms/step - loss: 0.1405 - acc: 0.9227 - val_loss: 0.1238 - val_acc: 0.9422
Epoch 6/70
36/36 [==============================] - 5s 143ms/step - loss: 0.1303 - acc: 0.9246 - val_loss: 0.1183 - val_acc: 0.9422
Epoch 7/70
36/36 [==============================] - 5s 145ms/step - loss: 0.1212 - acc: 0.9303 - val_loss: 0.1163 - val_acc: 0.9422
Epoch 8/70
36/36 [==============================] - 5s 144ms/step - loss: 0.1113 - acc: 0.9347 - val_loss: 0.1129 - val_acc: 0.9422
Epoch 9/70
36/36 [==============================] - 5s 139ms/step - loss: 0.1069 - acc: 0.9362 - val_loss: 0.1145 - val_acc: 0.9402
Epoch 10/70
36/36 [==============================] - 5s 137ms/step - loss: 0.0980 - acc: 0.9404 - val_loss: 0.1123 - val_acc: 0.9422
Epoch 11/70
36/36 [==============================] - 5s 140ms/step - loss: 0.0891 - acc: 0.9454 - val_loss: 0.1161 - val_acc: 0.9303
Epoch 12/70
36/36 [==============================] - 5s 135ms/step - loss: 0.0834 - acc: 0.9492 - val_loss: 0.1124 - val_acc: 0.9382
Epoch 13/70
36/36 [==============================] - 5s 139ms/step - loss: 0.0776 - acc: 0.9531 - val_loss: 0.1122 - val_acc: 0.9402
Epoch 14/70
36/36 [==============================] - 5s 131ms/step - loss: 0.0667 - acc: 0.9582 - val_loss: 0.1281 - val_acc: 0.9263
Epoch 15/70
36/36 [==============================] - 5s 129ms/step - loss: 0.0607 - acc: 0.9663 - val_loss: 0.1169 - val_acc: 0.9283
Epoch 16/70
36/36 [==============================] - 5s 133ms/step - loss: 0.0572 - acc: 0.9663 - val_loss: 0.1254 - val_acc: 0.9303
Epoch 1/70
20/20 [==============================] - 10s 242ms/step - loss: 0.5464 - acc: 0.6981 - val_loss: 0.5040 - val_acc: 0.6953
Epoch 2/70
20/20 [==============================] - 4s 180ms/step - loss: 0.4698 - acc: 0.7116 - val_loss: 0.4696 - val_acc: 0.6953
Epoch 3/70
20/20 [==============================] - 3s 167ms/step - loss: 0.4392 - acc: 0.7116 - val_loss: 0.4374 - val_acc: 0.6953
Epoch 4/70
20/20 [==============================] - 4s 179ms/step - loss: 0.4009 - acc: 0.7116 - val_loss: 0.3928 - val_acc: 0.6953
Epoch 5/70
20/20 [==============================] - 4s 181ms/step - loss: 0.3612 - acc: 0.7227 - val_loss: 0.3753 - val_acc: 0.7061
Epoch 6/70
20/20 [==============================] - 3s 163ms/step - loss: 0.3286 - acc: 0.7481 - val_loss: 0.3293 - val_acc: 0.7849
Epoch 7/70
20/20 [==============================] - 3s 152ms/step - loss: 0.2938 - acc: 0.8100 - val_loss: 0.3112 - val_acc: 0.8136
Epoch 8/70
20/20 [==============================] - 3s 150ms/step - loss: 0.2749 - acc: 0.8231 - val_loss: 0.2938 - val_acc: 0.7993
Epoch 9/70
20/20 [==============================] - 3s 149ms/step - loss: 0.2569 - acc: 0.8445 - val_loss: 0.2858 - val_acc: 0.8244
Epoch 10/70
20/20 [==============================] - 3s 154ms/step - loss: 0.2357 - acc: 0.8604 - val_loss: 0.2716 - val_acc: 0.7993
Epoch 11/70
20/20 [==============================] - 3s 146ms/step - loss: 0.2155 - acc: 0.8715 - val_loss: 0.2636 - val_acc: 0.8280
Epoch 12/70
20/20 [==============================] - 3s 155ms/step - loss: 0.1973 - acc: 0.8790 - val_loss: 0.2612 - val_acc: 0.8315
Epoch 13/70
20/20 [==============================] - 3s 151ms/step - loss: 0.1859 - acc: 0.8877 - val_loss: 0.2671 - val_acc: 0.8208
Epoch 14/70
20/20 [==============================] - 3s 134ms/step - loss: 0.1680 - acc: 0.9040 - val_loss: 0.2639 - val_acc: 0.8208
Epoch 15/70
20/20 [==============================] - 3s 143ms/step - loss: 0.1523 - acc: 0.9080 - val_loss: 0.2587 - val_acc: 0.8244
Epoch 16/70
20/20 [==============================] - 3s 142ms/step - loss: 0.1378 - acc: 0.9226 - val_loss: 0.2711 - val_acc: 0.8244
Epoch 17/70
20/20 [==============================] - 3s 147ms/step - loss: 0.1231 - acc: 0.9314 - val_loss: 0.2693 - val_acc: 0.8208
Epoch 18/70
20/20 [==============================] - 3s 138ms/step - loss: 0.1144 - acc: 0.9393 - val_loss: 0.2779 - val_acc: 0.8315
Epoch 1/70
12/12 [==============================] - 8s 284ms/step - loss: 0.6407 - acc: 0.3978 - val_loss: 0.6257 - val_acc: 0.4400
Epoch 2/70
12/12 [==============================] - 2s 187ms/step - loss: 0.6140 - acc: 0.5209 - val_loss: 0.5914 - val_acc: 0.5200
Epoch 3/70
12/12 [==============================] - 2s 192ms/step - loss: 0.5866 - acc: 0.5688 - val_loss: 0.5566 - val_acc: 0.6333
Epoch 4/70
12/12 [==============================] - 2s 199ms/step - loss: 0.5465 - acc: 0.6384 - val_loss: 0.5112 - val_acc: 0.6400
Epoch 5/70
12/12 [==============================] - 2s 185ms/step - loss: 0.4929 - acc: 0.6822 - val_loss: 0.4662 - val_acc: 0.6400
Epoch 6/70
12/12 [==============================] - 2s 174ms/step - loss: 0.4419 - acc: 0.6975 - val_loss: 0.4367 - val_acc: 0.6733
Epoch 7/70
12/12 [==============================] - 2s 165ms/step - loss: 0.4050 - acc: 0.7218 - val_loss: 0.4233 - val_acc: 0.7067
Epoch 8/70
12/12 [==============================] - 2s 154ms/step - loss: 0.3861 - acc: 0.7302 - val_loss: 0.4048 - val_acc: 0.7400
Epoch 9/70
12/12 [==============================] - 2s 151ms/step - loss: 0.3628 - acc: 0.7497 - val_loss: 0.3939 - val_acc: 0.7667
Epoch 10/70
12/12 [==============================] - 2s 163ms/step - loss: 0.3441 - acc: 0.7733 - val_loss: 0.3927 - val_acc: 0.7667
Epoch 11/70
12/12 [==============================] - 2s 138ms/step - loss: 0.3277 - acc: 0.7844 - val_loss: 0.3765 - val_acc: 0.7533
Epoch 12/70
12/12 [==============================] - 2s 160ms/step - loss: 0.3208 - acc: 0.7872 - val_loss: 0.3652 - val_acc: 0.7467
Epoch 13/70
12/12 [==============================] - 2s 173ms/step - loss: 0.2975 - acc: 0.8150 - val_loss: 0.3598 - val_acc: 0.7800
Epoch 14/70
12/12 [==============================] - 2s 152ms/step - loss: 0.2921 - acc: 0.8157 - val_loss: 0.3573 - val_acc: 0.7600
Epoch 15/70
12/12 [==============================] - 2s 152ms/step - loss: 0.2833 - acc: 0.8171 - val_loss: 0.3576 - val_acc: 0.7733
Epoch 16/70
12/12 [==============================] - 2s 165ms/step - loss: 0.2675 - acc: 0.8345 - val_loss: 0.3491 - val_acc: 0.7867
Epoch 17/70
12/12 [==============================] - 2s 148ms/step - loss: 0.2573 - acc: 0.8394 - val_loss: 0.3496 - val_acc: 0.7733
Epoch 18/70
12/12 [==============================] - 2s 146ms/step - loss: 0.2522 - acc: 0.8373 - val_loss: 0.3678 - val_acc: 0.7867
Epoch 19/70
12/12 [==============================] - 2s 142ms/step - loss: 0.2393 - acc: 0.8470 - val_loss: 0.3653 - val_acc: 0.7933
Epoch 1/70
18/18 [==============================] - 11s 244ms/step - loss: 0.5141 - acc: 0.7243 - val_loss: 0.4187 - val_acc: 0.7438
Epoch 2/70
18/18 [==============================] - 3s 191ms/step - loss: 0.4277 - acc: 0.7243 - val_loss: 0.3773 - val_acc: 0.7438
Epoch 3/70
18/18 [==============================] - 3s 178ms/step - loss: 0.3829 - acc: 0.7252 - val_loss: 0.3327 - val_acc: 0.7479
Epoch 4/70
18/18 [==============================] - 3s 163ms/step - loss: 0.3357 - acc: 0.7617 - val_loss: 0.2920 - val_acc: 0.8182
Epoch 5/70
18/18 [==============================] - 3s 166ms/step - loss: 0.2940 - acc: 0.8132 - val_loss: 0.2646 - val_acc: 0.8306
Epoch 6/70
18/18 [==============================] - 3s 156ms/step - loss: 0.2727 - acc: 0.8389 - val_loss: 0.2490 - val_acc: 0.8512
Epoch 7/70
18/18 [==============================] - 3s 151ms/step - loss: 0.2484 - acc: 0.8547 - val_loss: 0.2395 - val_acc: 0.8554
Epoch 8/70
18/18 [==============================] - 2s 138ms/step - loss: 0.2286 - acc: 0.8700 - val_loss: 0.2263 - val_acc: 0.8719
Epoch 9/70
18/18 [==============================] - 3s 150ms/step - loss: 0.2105 - acc: 0.8786 - val_loss: 0.2164 - val_acc: 0.8843
Epoch 10/70
18/18 [==============================] - 3s 147ms/step - loss: 0.1951 - acc: 0.8962 - val_loss: 0.2143 - val_acc: 0.8636
Epoch 11/70
18/18 [==============================] - 2s 139ms/step - loss: 0.1849 - acc: 0.8980 - val_loss: 0.2229 - val_acc: 0.8678
Epoch 12/70
18/18 [==============================] - 3s 150ms/step - loss: 0.1717 - acc: 0.9003 - val_loss: 0.2002 - val_acc: 0.8843
Epoch 13/70
18/18 [==============================] - 3s 146ms/step - loss: 0.1609 - acc: 0.9106 - val_loss: 0.1927 - val_acc: 0.8802
Epoch 14/70
18/18 [==============================] - 2s 138ms/step - loss: 0.1427 - acc: 0.9210 - val_loss: 0.1994 - val_acc: 0.8843
Epoch 15/70
18/18 [==============================] - 3s 147ms/step - loss: 0.1351 - acc: 0.9251 - val_loss: 0.1900 - val_acc: 0.8967
Epoch 16/70
18/18 [==============================] - 2s 139ms/step - loss: 0.1275 - acc: 0.9287 - val_loss: 0.1996 - val_acc: 0.8802
Epoch 17/70
18/18 [==============================] - 3s 142ms/step - loss: 0.1170 - acc: 0.9310 - val_loss: 0.2189 - val_acc: 0.8760
Epoch 18/70
18/18 [==============================] - 2s 139ms/step - loss: 0.1115 - acc: 0.9368 - val_loss: 0.1906 - val_acc: 0.8884
Epoch 1/70
13/13 [==============================] - 8s 273ms/step - loss: 0.6552 - acc: 0.4155 - val_loss: 0.5933 - val_acc: 0.5904
Epoch 2/70
13/13 [==============================] - 3s 198ms/step - loss: 0.5621 - acc: 0.5858 - val_loss: 0.5192 - val_acc: 0.5532
Epoch 3/70
13/13 [==============================] - 2s 172ms/step - loss: 0.5003 - acc: 0.6107 - val_loss: 0.4906 - val_acc: 0.5638
Epoch 4/70
13/13 [==============================] - 2s 184ms/step - loss: 0.4695 - acc: 0.6575 - val_loss: 0.4709 - val_acc: 0.5745
Epoch 5/70
13/13 [==============================] - 2s 168ms/step - loss: 0.4469 - acc: 0.6843 - val_loss: 0.4434 - val_acc: 0.6383
Epoch 6/70
13/13 [==============================] - 2s 182ms/step - loss: 0.4079 - acc: 0.7330 - val_loss: 0.4034 - val_acc: 0.7447
Epoch 7/70
13/13 [==============================] - 2s 181ms/step - loss: 0.3854 - acc: 0.7664 - val_loss: 0.4084 - val_acc: 0.7500
Epoch 8/70
13/13 [==============================] - 2s 159ms/step - loss: 0.3537 - acc: 0.7762 - val_loss: 0.4088 - val_acc: 0.7713
Epoch 9/70
13/13 [==============================] - 2s 154ms/step - loss: 0.3404 - acc: 0.7962 - val_loss: 0.3762 - val_acc: 0.7819
Epoch 10/70
13/13 [==============================] - 2s 144ms/step - loss: 0.3267 - acc: 0.8029 - val_loss: 0.3780 - val_acc: 0.7766
Epoch 11/70
13/13 [==============================] - 2s 162ms/step - loss: 0.3141 - acc: 0.8151 - val_loss: 0.3671 - val_acc: 0.7766
Epoch 12/70
13/13 [==============================] - 2s 139ms/step - loss: 0.2977 - acc: 0.8224 - val_loss: 0.3551 - val_acc: 0.7660
Epoch 13/70
13/13 [==============================] - 2s 147ms/step - loss: 0.2815 - acc: 0.8339 - val_loss: 0.3541 - val_acc: 0.7553
Epoch 14/70
13/13 [==============================] - 2s 157ms/step - loss: 0.2742 - acc: 0.8418 - val_loss: 0.3523 - val_acc: 0.7660
Epoch 15/70
13/13 [==============================] - 2s 152ms/step - loss: 0.2649 - acc: 0.8455 - val_loss: 0.3541 - val_acc: 0.7713
Epoch 16/70
13/13 [==============================] - 2s 151ms/step - loss: 0.2520 - acc: 0.8564 - val_loss: 0.3551 - val_acc: 0.7660
Epoch 17/70
13/13 [==============================] - 2s 139ms/step - loss: 0.2391 - acc: 0.8619 - val_loss: 0.3893 - val_acc: 0.7713

In [88]:
df_sentiment_train_pred = {}
df_sentiment_train_true_ = {}

df_sentiment_val_true_ = {}
df_sentiment_val_pred = {}

df_sentiment_test_true_ = {}
df_sentiment_test_pred = {}


for aspect in lst_aspect:
    pred_sentiment_train = sentiment_model_bil_con[aspect].predict(padded_sentiment_train[aspect])
    pred_sentiment_val = sentiment_model_bil_con[aspect].predict(padded_sentiment_val[aspect])
    pred_sentiment_test = sentiment_model_bil_con[aspect].predict(padded_sentiment_test[aspect])
    
    df_sentiment_train_pred[aspect] = np.argmax(pred_sentiment_train, axis=1)
    df_sentiment_train_true_[aspect] = np.argmax(label_sentiment_train[aspect], axis = 1)
    
    df_sentiment_val_pred[aspect] = np.argmax(pred_sentiment_val, axis=1)
    df_sentiment_val_true_[aspect] = np.argmax(label_sentiment_val[aspect], axis = 1)
    
    df_sentiment_test_pred[aspect] = np.argmax(pred_sentiment_test, axis=1)
    df_sentiment_test_true_[aspect] = np.argmax(label_sentiment_test[aspect], axis=1)

40/40 [==============================] - 1s 14ms/step
5/5 [==============================] - 0s 13ms/step
11/11 [==============================] - 0s 16ms/step
79/79 [==============================] - 2s 14ms/step
10/10 [==============================] - 0s 13ms/step
23/23 [==============================] - 0s 15ms/step
143/143 [==============================] - 3s 14ms/step
16/16 [==============================] - 0s 13ms/step
40/40 [==============================] - 1s 13ms/step
79/79 [==============================] - 2s 14ms/step
9/9 [==============================] - 0s 13ms/step
22/22 [==============================] - 0s 15ms/step
45/45 [==============================] - 1s 13ms/step
5/5 [==============================] - 0s 13ms/step
13/13 [==============================] - 0s 13ms/step
70/70 [==============================] - 2s 14ms/step
8/8 [==============================] - 0s 17ms/step
19/19 [==============================] - 0s 15ms/step
52/52 [==============================] - 1s 14ms/step
6/6 [==============================] - 0s 20ms/step
15/15 [==============================] - 0s 13ms/step

In [89]:
def get_pd_report_sentiment(df_sentiment_test_true_, df_sentiment_test_pred):
    sentiment_result_bilstm = {}
    for aspect in lst_aspect:
        sentiment_result_bilstm[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
        sentiment_result_bilstm[aspect]['aspect'] = aspect

    output_sentiment_report = pd.DataFrame()
    for indx, val in sentiment_result_bilstm.items():
        output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

    return output_aspect_report

In [90]:
sentiment_result_bilstm = {}
# for aspect in lst_aspect:
for aspect in lst_aspect:
    sentiment_result_bilstm[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
    sentiment_result_bilstm[aspect]['aspect'] = aspect

output_sentiment_report = pd.DataFrame()
for indx, val in sentiment_result_bilstm.items():
    output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [91]:
output_sentiment_report

              precision    recall  f1-score      support       aspect
0              0.000000  0.000000  0.000000     3.000000        price
1              0.920168  0.886640  0.903093   247.000000        price
2              0.708738  0.802198  0.752577    91.000000        price
accuracy       0.856305  0.856305  0.856305     0.856305        price
macro avg      0.542969  0.562946  0.551890   341.000000        price
weighted avg   0.855650  0.856305  0.854981   341.000000        price
0              0.808511  0.919355  0.860377   124.000000     shipping
1              0.958855  0.976321  0.967509   549.000000     shipping
2              0.200000  0.031250  0.054054    32.000000     shipping
accuracy       0.923404  0.923404  0.923404     0.923404     shipping
macro avg      0.655789  0.642308  0.627313   705.000000     shipping
weighted avg   0.897967  0.923404  0.907204   705.000000     shipping
0              0.737374  0.768421  0.752577    95.000000      outlook
1              0.966132  0.969589  0.967857  1118.000000      outlook
2              0.380000  0.327586  0.351852    58.000000      outlook
accuracy       0.925256  0.925256  0.925256     0.925256      outlook
macro avg      0.694502  0.688532  0.690762  1271.000000      outlook
weighted avg   0.922286  0.925256  0.923656  1271.000000      outlook
0              0.737500  0.602041  0.662921    98.000000      quality
1              0.920000  0.914226  0.917104   478.000000      quality
2              0.476923  0.568807  0.518828   109.000000      quality
accuracy       0.814599  0.814599  0.814599     0.814599      quality
macro avg      0.711474  0.695025  0.699618   685.000000      quality
weighted avg   0.823386  0.814599  0.817364   685.000000      quality
0              0.614943  0.856000  0.715719   125.000000         size
1              0.933333  0.933333  0.933333   165.000000         size
2              0.687500  0.340206  0.455172    97.000000         size
accuracy       0.759690  0.759690  0.759690     0.759690         size
macro avg      0.745259  0.709847  0.701408   387.000000         size
weighted avg   0.768877  0.759690  0.743195   387.000000         size
0              0.783784  0.828571  0.805556   140.000000  shopservice
1              0.922222  0.962877  0.942111   431.000000  shopservice
2              0.500000  0.034483  0.064516    29.000000  shopservice
accuracy       0.886667  0.886667  0.886667     0.886667  shopservice
macro avg      0.735335  0.608644  0.604061   600.000000  shopservice
weighted avg   0.869513  0.886667  0.867831   600.000000  shopservice
0              0.000000  0.000000  0.000000    11.000000      general
1              0.816770  0.922807  0.866557   285.000000      general
2              0.814103  0.697802  0.751479   182.000000      general
accuracy       0.815900  0.815900  0.815900     0.815900      general
macro avg      0.543624  0.540203  0.539345   478.000000      general
weighted avg   0.796959  0.815900  0.802799   478.000000      general

In [92]:
for aspect in lst_aspect:
    print(aspect)
    print(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist()))

price
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.92      0.89      0.90       247
           2       0.71      0.80      0.75        91

    accuracy                           0.86       341
   macro avg       0.54      0.56      0.55       341
weighted avg       0.86      0.86      0.85       341

shipping
              precision    recall  f1-score   support

           0       0.81      0.92      0.86       124
           1       0.96      0.98      0.97       549
           2       0.20      0.03      0.05        32

    accuracy                           0.92       705
   macro avg       0.66      0.64      0.63       705
weighted avg       0.90      0.92      0.91       705

outlook
              precision    recall  f1-score   support

           0       0.74      0.77      0.75        95
           1       0.97      0.97      0.97      1118
           2       0.38      0.33      0.35        58

    accuracy                           0.93      1271
   macro avg       0.69      0.69      0.69      1271
weighted avg       0.92      0.93      0.92      1271

quality
              precision    recall  f1-score   support

           0       0.74      0.60      0.66        98
           1       0.92      0.91      0.92       478
           2       0.48      0.57      0.52       109

    accuracy                           0.81       685
   macro avg       0.71      0.70      0.70       685
weighted avg       0.82      0.81      0.82       685

size
              precision    recall  f1-score   support

           0       0.61      0.86      0.72       125
           1       0.93      0.93      0.93       165
           2       0.69      0.34      0.46        97

    accuracy                           0.76       387
   macro avg       0.75      0.71      0.70       387
weighted avg       0.77      0.76      0.74       387

shopservice
              precision    recall  f1-score   support

           0       0.78      0.83      0.81       140
           1       0.92      0.96      0.94       431
           2       0.50      0.03      0.06        29

    accuracy                           0.89       600
   macro avg       0.74      0.61      0.60       600
weighted avg       0.87      0.89      0.87       600

general
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.82      0.92      0.87       285
           2       0.81      0.70      0.75       182

    accuracy                           0.82       478
   macro avg       0.54      0.54      0.54       478
weighted avg       0.80      0.82      0.80       478

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [93]:
for i in lst_aspect:
    with open(f'{path}elmo_bilstm_con_test_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_test_true_[i].tolist(), df_sentiment_test_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [94]:
for i in lst_aspect:
    with open(f'{path}elmo_bilstm_con_val_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_val_true_[i].tolist(), df_sentiment_val_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## 4. BiGRU + Conv1D

In [95]:
def gru_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_aspect_size,
                      output_dim=embedding_dim,
                      embeddings_initializer=Constant(embedding_aspect_matrix),
                      input_length=max_len,
                      trainable=True)(input)
    dropout1 = SpatialDropout1D(0.2)(embed)

    lstm = Bidirectional(GRU(units = 200, activation = 'tanh', return_sequences = True))(dropout1)
    conv = Conv1D(128, kernel_size = 2, padding = "valid", kernel_initializer = "he_uniform")(lstm)

    avg_pool1 = GlobalAveragePooling1D()(conv)
    max_pool1 = GlobalMaxPooling1D()(conv)
    
    concat = Concatenate(axis=-1)([avg_pool1, max_pool1])
    dense2 = Dense(units = 128, activation = 'relu')(concat)
    dropout1 = Dropout(rate = 0.2)(dense2)
    dense3 = Dense(units = 64, activation = 'relu')(dropout1)
    dense4 = Dense(units = 32, activation = 'relu')(dense3)
    out_aspect = Dense(units = 8, activation = 'sigmoid', name='out_aspect')(dense4)
    
    aspect_model = tf.keras.Model(inputs = input, outputs = out_aspect)
    aspect_model.compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    # Fit model
    history = aspect_model.fit(x=padded_aspect_train,
                               y=label_aspect_train.to_numpy(),
                               validation_data=(padded_aspect_val, label_aspect_val.to_numpy()),
                               batch_size = 128,
                               epochs=epochs,
                               callbacks = [callback],
                               verbose=1)
    
    return aspect_model

def gru_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_sentiment_size[aspect],
                  output_dim=embedding_dim,
                  embeddings_initializer=Constant(embedding_sentiment_matrix[aspect]),
                  input_length=max_len,
                  trainable=True)(input)
  
    dropout1 = SpatialDropout1D(0.2)(embed)
    lstm = Bidirectional(GRU(units = 200, activation = 'tanh', return_sequences = True))(dropout1)
    conv = Conv1D(128, kernel_size = 2, padding = "valid", kernel_initializer = "he_uniform")(lstm)

    avg_pool1 = GlobalAveragePooling1D()(conv)
    max_pool1 = GlobalMaxPooling1D()(conv)
      
      
    concat = Concatenate(axis=-1)([avg_pool1, max_pool1])

    sentiment_dense2 = Dense(128, activation='relu')(concat)
    sentiment_dropout1 = Dropout(0.2)(sentiment_dense2)
    sentiment_dense3 = Dense(64, activation='relu')(sentiment_dropout1)
    sentiment_dense4 = Dense(32, activation='relu')(sentiment_dense3)
    out_sentiment = Dense(units = 3, activation = 'softmax')(sentiment_dense4)
    
    sentiment_model_big_con[aspect] = tf.keras.Model(inputs = input, outputs = out_sentiment)
    sentiment_model_big_con[aspect].compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    history = sentiment_model_big_con[aspect].fit(x=padded_sentiment_train[aspect],
                                          y=label_sentiment_train[aspect],
                                          validation_data=(padded_sentiment_val[aspect], label_sentiment_val[aspect]),
                                          batch_size = 128,
                                          epochs=epochs,
                                          callbacks = [callback],
                                          verbose=1)
    
    return sentiment_model_big_con[aspect]

In [105]:
aspect_model_big_con = gru_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val)

Epoch 1/70
66/66 [==============================] - 18s 190ms/step - loss: 0.5504 - acc: 0.2807 - val_loss: 0.4711 - val_acc: 0.3066
Epoch 2/70
66/66 [==============================] - 11s 164ms/step - loss: 0.4488 - acc: 0.3934 - val_loss: 0.3983 - val_acc: 0.5085
Epoch 3/70
66/66 [==============================] - 9s 141ms/step - loss: 0.3854 - acc: 0.4789 - val_loss: 0.3401 - val_acc: 0.5449
Epoch 4/70
66/66 [==============================] - 9s 139ms/step - loss: 0.3293 - acc: 0.5058 - val_loss: 0.2927 - val_acc: 0.5620
Epoch 5/70
66/66 [==============================] - 9s 132ms/step - loss: 0.2901 - acc: 0.5316 - val_loss: 0.2606 - val_acc: 0.5652
Epoch 6/70
66/66 [==============================] - 8s 120ms/step - loss: 0.2610 - acc: 0.5566 - val_loss: 0.2410 - val_acc: 0.5940
Epoch 7/70
66/66 [==============================] - 8s 118ms/step - loss: 0.2389 - acc: 0.5689 - val_loss: 0.2275 - val_acc: 0.5983
Epoch 8/70
66/66 [==============================] - 8s 116ms/step - loss: 0.2252 - acc: 0.5920 - val_loss: 0.2218 - val_acc: 0.5716
Epoch 9/70
66/66 [==============================] - 8s 115ms/step - loss: 0.2129 - acc: 0.5916 - val_loss: 0.2124 - val_acc: 0.5887
Epoch 10/70
66/66 [==============================] - 7s 109ms/step - loss: 0.2015 - acc: 0.5991 - val_loss: 0.2055 - val_acc: 0.6079
Epoch 11/70
66/66 [==============================] - 7s 112ms/step - loss: 0.1924 - acc: 0.6078 - val_loss: 0.2018 - val_acc: 0.5940
Epoch 12/70
66/66 [==============================] - 7s 108ms/step - loss: 0.1862 - acc: 0.6071 - val_loss: 0.2039 - val_acc: 0.5940
Epoch 13/70
66/66 [==============================] - 7s 108ms/step - loss: 0.1799 - acc: 0.6146 - val_loss: 0.1978 - val_acc: 0.6186
Epoch 14/70
66/66 [==============================] - 7s 104ms/step - loss: 0.1722 - acc: 0.6105 - val_loss: 0.1955 - val_acc: 0.5673
Epoch 15/70
66/66 [==============================] - 7s 106ms/step - loss: 0.1670 - acc: 0.6112 - val_loss: 0.1949 - val_acc: 0.5929
Epoch 16/70
66/66 [==============================] - 7s 109ms/step - loss: 0.1607 - acc: 0.6151 - val_loss: 0.1949 - val_acc: 0.5385
Epoch 17/70
66/66 [==============================] - 7s 109ms/step - loss: 0.1570 - acc: 0.6168 - val_loss: 0.1912 - val_acc: 0.5887
Epoch 18/70
66/66 [==============================] - 7s 106ms/step - loss: 0.1521 - acc: 0.6180 - val_loss: 0.1909 - val_acc: 0.5865
Epoch 19/70
66/66 [==============================] - 7s 106ms/step - loss: 0.1461 - acc: 0.6186 - val_loss: 0.1905 - val_acc: 0.6111
Epoch 20/70
66/66 [==============================] - 7s 108ms/step - loss: 0.1437 - acc: 0.6220 - val_loss: 0.1894 - val_acc: 0.5748
Epoch 21/70
66/66 [==============================] - 7s 109ms/step - loss: 0.1358 - acc: 0.6220 - val_loss: 0.1907 - val_acc: 0.5726
Epoch 22/70
66/66 [==============================] - 7s 108ms/step - loss: 0.1324 - acc: 0.6292 - val_loss: 0.1916 - val_acc: 0.5929
Epoch 23/70
66/66 [==============================] - 7s 107ms/step - loss: 0.1280 - acc: 0.6302 - val_loss: 0.1919 - val_acc: 0.5812

In [106]:
pred_train = aspect_model_big_con.predict(padded_aspect_train)
pred_val = aspect_model_big_con.predict(padded_aspect_val)
pred_test = aspect_model_big_con.predict(padded_aspect_test)

df_train_pred = round(pd.DataFrame(pred_train), 0)
df_train_true_ = label_aspect_train
df_train_pred.columns = df_train_true_.columns

df_val_pred = round(pd.DataFrame(pred_val), 0)
df_val_true_ = label_aspect_val
df_val_pred.columns = df_val_true_.columns

df_test_pred = round(pd.DataFrame(pred_test), 0)
df_test_true_ = label_aspect_test
df_test_pred.columns = df_test_true_.columns

264/264 [==============================] - 4s 12ms/step
30/30 [==============================] - 0s 11ms/step
74/74 [==============================] - 1s 12ms/step

In [107]:
def get_pd_report(label_aspect_train, df_test_true_, df_test_pred):
    aspect_result_gru_report = {}
    for col in label_aspect_train.columns:
        aspect_result_gru_report = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
        aspect_result_gru_report[col] = pd.DataFrame(aspect_result_bilstm).T
        aspect_result_gru_report[col]['aspect'] = col
        
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_gru_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_gru_report[indx]])
    
    return output_aspect_report

In [108]:
aspect_result_gru_report = {}
for col in label_aspect_train.columns:
    print(col)
    aspect_result_gru = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
    print(aspect_result_gru)
    
    aspect_result_gru_report[col] = pd.DataFrame(aspect_result_gru).T
    aspect_result_gru_report[col]['aspect'] = col
    
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_gru_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_gru_report[indx]])

is_price
{'0': {'precision': 0.9656188605108055, 'recall': 0.9834917458729364, 'f1-score': 0.9744733581164807, 'support': 1999}, '1': {'precision': 0.8914473684210527, 'recall': 0.7947214076246334, 'f1-score': 0.8403100775193798, 'support': 341}, 'accuracy': 0.955982905982906, 'macro avg': {'precision': 0.928533114465929, 'recall': 0.8891065767487849, 'f1-score': 0.9073917178179303, 'support': 2340}, 'weighted avg': {'precision': 0.9548101088857601, 'recall': 0.955982905982906, 'f1-score': 0.9549222133798948, 'support': 2340}}
is_shipping
{'0': {'precision': 0.9808286951144094, 'recall': 0.9700305810397554, 'f1-score': 0.97539975399754, 'support': 1635}, '1': {'precision': 0.9322268326417704, 'recall': 0.9560283687943263, 'f1-score': 0.9439775910364147, 'support': 705}, 'accuracy': 0.9658119658119658, 'macro avg': {'precision': 0.9565277638780899, 'recall': 0.9630294749170408, 'f1-score': 0.9596886725169773, 'support': 2340}, 'weighted avg': {'precision': 0.9661858262925245, 'recall': 0.9658119658119658, 'f1-score': 0.9659328202848931, 'support': 2340}}
is_outlook
{'0': {'precision': 0.9033423667570009, 'recall': 0.9354536950420954, 'f1-score': 0.9191176470588235, 'support': 1069}, '1': {'precision': 0.9440389294403893, 'recall': 0.9158143194335169, 'f1-score': 0.9297124600638977, 'support': 1271}, 'accuracy': 0.9247863247863248, 'macro avg': {'precision': 0.923690648098695, 'recall': 0.9256340072378062, 'f1-score': 0.9244150535613607, 'support': 2340}, 'weighted avg': {'precision': 0.9254472091375934, 'recall': 0.9247863247863248, 'f1-score': 0.9248723510457676, 'support': 2340}}
is_quality
{'0': {'precision': 0.9273947528981086, 'recall': 0.9189842805320435, 'f1-score': 0.9231703613726084, 'support': 1654}, '1': {'precision': 0.8088445078459344, 'recall': 0.826530612244898, 'f1-score': 0.8175919250180245, 'support': 686}, 'accuracy': 0.8918803418803419, 'macro avg': {'precision': 0.8681196303720216, 'recall': 0.8727574463884707, 'f1-score': 0.8703811431953165, 'support': 2340}, 'weighted avg': {'precision': 0.8926402793486251, 'recall': 0.8918803418803419, 'f1-score': 0.8922187343045552, 'support': 2340}}
is_size
{'0': {'precision': 0.9791666666666666, 'recall': 0.9626216077828981, 'f1-score': 0.9708236509166022, 'support': 1953}, '1': {'precision': 0.8261904761904761, 'recall': 0.896640826873385, 'f1-score': 0.8599752168525402, 'support': 387}, 'accuracy': 0.9517094017094017, 'macro avg': {'precision': 0.9026785714285714, 'recall': 0.9296312173281416, 'f1-score': 0.9153994338845712, 'support': 2340}, 'weighted avg': {'precision': 0.9538667582417584, 'recall': 0.9517094017094017, 'f1-score': 0.9524910252829304, 'support': 2340}}
is_shopservice
{'0': {'precision': 0.944538766270515, 'recall': 0.9591954022988506, 'f1-score': 0.9518106643855146, 'support': 1740}, '1': {'precision': 0.8760907504363001, 'recall': 0.8366666666666667, 'f1-score': 0.855924978687127, 'support': 600}, 'accuracy': 0.9277777777777778, 'macro avg': {'precision': 0.9103147583534076, 'recall': 0.8979310344827587, 'f1-score': 0.9038678215363208, 'support': 2340}, 'weighted avg': {'precision': 0.9269879929796906, 'recall': 0.9277777777777778, 'f1-score': 0.9272245911295178, 'support': 2340}}
is_general
{'0': {'precision': 0.8978139298423996, 'recall': 0.9489521762493284, 'f1-score': 0.922675026123302, 'support': 1861}, '1': {'precision': 0.7453083109919572, 'recall': 0.5803757828810021, 'f1-score': 0.6525821596244132, 'support': 479}, 'accuracy': 0.8735042735042735, 'macro avg': {'precision': 0.8215611204171784, 'recall': 0.7646639795651653, 'f1-score': 0.7876285928738576, 'support': 2340}, 'weighted avg': {'precision': 0.8665958993170313, 'recall': 0.8735042735042735, 'f1-score': 0.8673867855023756, 'support': 2340}}
is_others
{'0': {'precision': 0.9783709157846295, 'recall': 0.9883774988377498, 'f1-score': 0.9833487511563367, 'support': 2151}, '1': {'precision': 0.8502994011976048, 'recall': 0.7513227513227513, 'f1-score': 0.797752808988764, 'support': 189}, 'accuracy': 0.9692307692307692, 'macro avg': {'precision': 0.9143351584911172, 'recall': 0.8698501250802506, 'f1-score': 0.8905507800725503, 'support': 2340}, 'weighted avg': {'precision': 0.9680266780679853, 'recall': 0.9692307692307692, 'f1-score': 0.9683583096735711, 'support': 2340}}

In [109]:
for col in label_aspect_train.columns:
    print(col)
    aspect_result = classification_report(df_test_true_[col], df_test_pred[col])

    print(aspect_result)

is_price
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1999
           1       0.89      0.79      0.84       341

    accuracy                           0.96      2340
   macro avg       0.93      0.89      0.91      2340
weighted avg       0.95      0.96      0.95      2340

is_shipping
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1635
           1       0.93      0.96      0.94       705

    accuracy                           0.97      2340
   macro avg       0.96      0.96      0.96      2340
weighted avg       0.97      0.97      0.97      2340

is_outlook
              precision    recall  f1-score   support

           0       0.90      0.94      0.92      1069
           1       0.94      0.92      0.93      1271

    accuracy                           0.92      2340
   macro avg       0.92      0.93      0.92      2340
weighted avg       0.93      0.92      0.92      2340

is_quality
              precision    recall  f1-score   support

           0       0.93      0.92      0.92      1654
           1       0.81      0.83      0.82       686

    accuracy                           0.89      2340
   macro avg       0.87      0.87      0.87      2340
weighted avg       0.89      0.89      0.89      2340

is_size
              precision    recall  f1-score   support

           0       0.98      0.96      0.97      1953
           1       0.83      0.90      0.86       387

    accuracy                           0.95      2340
   macro avg       0.90      0.93      0.92      2340
weighted avg       0.95      0.95      0.95      2340

is_shopservice
              precision    recall  f1-score   support

           0       0.94      0.96      0.95      1740
           1       0.88      0.84      0.86       600

    accuracy                           0.93      2340
   macro avg       0.91      0.90      0.90      2340
weighted avg       0.93      0.93      0.93      2340

is_general
              precision    recall  f1-score   support

           0       0.90      0.95      0.92      1861
           1       0.75      0.58      0.65       479

    accuracy                           0.87      2340
   macro avg       0.82      0.76      0.79      2340
weighted avg       0.87      0.87      0.87      2340

is_others
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      2151
           1       0.85      0.75      0.80       189

    accuracy                           0.97      2340
   macro avg       0.91      0.87      0.89      2340
weighted avg       0.97      0.97      0.97      2340

In [110]:
path = '/kaggle/working/'

In [111]:
save_result_pred_aspect(df_test_true_, df_test_pred, data_eval = 'test', model_type = 'bigru_con')
save_result_pred_aspect(df_val_true_, df_val_pred, data_eval = 'eval', model_type = 'bigru_con')

In [112]:
lst_aspect = []
for col in label_aspect_train.columns.values:
    if col!='is_others':
        lst_aspect.append(col.split('_')[1])

In [113]:
sentiment_model_big_con = {}
for aspect in lst_aspect:
    sentiment_model_big_con[aspect] = gru_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val)

Epoch 1/70
10/10 [==============================] - 8s 267ms/step - loss: 0.5278 - acc: 0.7330 - val_loss: 0.4123 - val_acc: 0.7681
Epoch 2/70
10/10 [==============================] - 2s 181ms/step - loss: 0.4319 - acc: 0.7426 - val_loss: 0.3728 - val_acc: 0.7681
Epoch 3/70
10/10 [==============================] - 2s 158ms/step - loss: 0.3904 - acc: 0.7426 - val_loss: 0.3330 - val_acc: 0.7681
Epoch 4/70
10/10 [==============================] - 2s 184ms/step - loss: 0.3477 - acc: 0.7474 - val_loss: 0.2933 - val_acc: 0.7754
Epoch 5/70
10/10 [==============================] - 2s 170ms/step - loss: 0.3018 - acc: 0.7786 - val_loss: 0.2513 - val_acc: 0.8261
Epoch 6/70
10/10 [==============================] - 2s 169ms/step - loss: 0.2568 - acc: 0.8385 - val_loss: 0.2214 - val_acc: 0.8913
Epoch 7/70
10/10 [==============================] - 2s 159ms/step - loss: 0.2215 - acc: 0.8641 - val_loss: 0.2080 - val_acc: 0.8841
Epoch 8/70
10/10 [==============================] - 1s 110ms/step - loss: 0.2019 - acc: 0.8825 - val_loss: 0.2017 - val_acc: 0.8623
Epoch 9/70
10/10 [==============================] - 1s 151ms/step - loss: 0.1854 - acc: 0.8905 - val_loss: 0.1921 - val_acc: 0.8841
Epoch 10/70
10/10 [==============================] - 2s 169ms/step - loss: 0.1756 - acc: 0.9049 - val_loss: 0.1868 - val_acc: 0.9058
Epoch 11/70
10/10 [==============================] - 2s 159ms/step - loss: 0.1745 - acc: 0.9049 - val_loss: 0.1903 - val_acc: 0.8986
Epoch 12/70
10/10 [==============================] - 1s 140ms/step - loss: 0.1560 - acc: 0.9217 - val_loss: 0.1827 - val_acc: 0.9058
Epoch 13/70
10/10 [==============================] - 1s 122ms/step - loss: 0.1538 - acc: 0.9225 - val_loss: 0.1813 - val_acc: 0.8986
Epoch 14/70
10/10 [==============================] - 1s 120ms/step - loss: 0.1415 - acc: 0.9329 - val_loss: 0.1791 - val_acc: 0.9130
Epoch 15/70
10/10 [==============================] - 2s 164ms/step - loss: 0.1349 - acc: 0.9305 - val_loss: 0.1805 - val_acc: 0.9058
Epoch 16/70
10/10 [==============================] - 1s 131ms/step - loss: 0.1314 - acc: 0.9353 - val_loss: 0.1852 - val_acc: 0.8986
Epoch 17/70
10/10 [==============================] - 1s 138ms/step - loss: 0.1244 - acc: 0.9416 - val_loss: 0.1763 - val_acc: 0.9130
Epoch 18/70
10/10 [==============================] - 1s 132ms/step - loss: 0.1188 - acc: 0.9392 - val_loss: 0.1900 - val_acc: 0.9058
Epoch 19/70
10/10 [==============================] - 1s 153ms/step - loss: 0.1094 - acc: 0.9496 - val_loss: 0.1868 - val_acc: 0.9058
Epoch 20/70
10/10 [==============================] - 1s 112ms/step - loss: 0.1068 - acc: 0.9512 - val_loss: 0.1850 - val_acc: 0.9058
Epoch 1/70
20/20 [==============================] - 11s 223ms/step - loss: 0.4774 - acc: 0.7026 - val_loss: 0.3876 - val_acc: 0.7799
Epoch 2/70
20/20 [==============================] - 4s 184ms/step - loss: 0.3564 - acc: 0.7930 - val_loss: 0.3264 - val_acc: 0.7799
Epoch 3/70
20/20 [==============================] - 3s 157ms/step - loss: 0.2903 - acc: 0.8010 - val_loss: 0.2395 - val_acc: 0.8414
Epoch 4/70
20/20 [==============================] - 3s 142ms/step - loss: 0.2115 - acc: 0.8861 - val_loss: 0.1865 - val_acc: 0.9094
Epoch 5/70
20/20 [==============================] - 3s 162ms/step - loss: 0.1739 - acc: 0.9104 - val_loss: 0.1678 - val_acc: 0.9061
Epoch 6/70
20/20 [==============================] - 3s 135ms/step - loss: 0.1577 - acc: 0.9168 - val_loss: 0.1554 - val_acc: 0.9094
Epoch 7/70
20/20 [==============================] - 3s 124ms/step - loss: 0.1444 - acc: 0.9200 - val_loss: 0.1440 - val_acc: 0.9159
Epoch 8/70
20/20 [==============================] - 3s 134ms/step - loss: 0.1338 - acc: 0.9252 - val_loss: 0.1415 - val_acc: 0.9159
Epoch 9/70
20/20 [==============================] - 3s 129ms/step - loss: 0.1317 - acc: 0.9287 - val_loss: 0.1401 - val_acc: 0.9223
Epoch 10/70
20/20 [==============================] - 2s 120ms/step - loss: 0.1226 - acc: 0.9319 - val_loss: 0.1372 - val_acc: 0.9223
Epoch 11/70
20/20 [==============================] - 3s 142ms/step - loss: 0.1135 - acc: 0.9351 - val_loss: 0.1390 - val_acc: 0.9256
Epoch 12/70
20/20 [==============================] - 2s 120ms/step - loss: 0.1096 - acc: 0.9387 - val_loss: 0.1354 - val_acc: 0.9288
Epoch 13/70
20/20 [==============================] - 2s 120ms/step - loss: 0.1014 - acc: 0.9423 - val_loss: 0.1365 - val_acc: 0.9288
Epoch 14/70
20/20 [==============================] - 2s 125ms/step - loss: 0.0957 - acc: 0.9443 - val_loss: 0.1341 - val_acc: 0.9256
Epoch 15/70
20/20 [==============================] - 2s 120ms/step - loss: 0.0904 - acc: 0.9506 - val_loss: 0.1410 - val_acc: 0.9288
Epoch 16/70
20/20 [==============================] - 2s 116ms/step - loss: 0.0840 - acc: 0.9534 - val_loss: 0.1421 - val_acc: 0.9288
Epoch 17/70
20/20 [==============================] - 2s 107ms/step - loss: 0.0768 - acc: 0.9562 - val_loss: 0.1394 - val_acc: 0.9288
Epoch 1/70
36/36 [==============================] - 12s 201ms/step - loss: 0.4490 - acc: 0.7202 - val_loss: 0.2223 - val_acc: 0.9024
Epoch 2/70
36/36 [==============================] - 6s 152ms/step - loss: 0.2565 - acc: 0.8777 - val_loss: 0.1889 - val_acc: 0.9024
Epoch 3/70
36/36 [==============================] - 5s 150ms/step - loss: 0.2168 - acc: 0.8777 - val_loss: 0.1651 - val_acc: 0.9024
Epoch 4/70
36/36 [==============================] - 5s 141ms/step - loss: 0.1877 - acc: 0.8858 - val_loss: 0.1412 - val_acc: 0.9203
Epoch 5/70
36/36 [==============================] - 4s 126ms/step - loss: 0.1621 - acc: 0.9102 - val_loss: 0.1224 - val_acc: 0.9343
Epoch 6/70
36/36 [==============================] - 4s 122ms/step - loss: 0.1408 - acc: 0.9213 - val_loss: 0.1131 - val_acc: 0.9402
Epoch 7/70
36/36 [==============================] - 4s 116ms/step - loss: 0.1312 - acc: 0.9292 - val_loss: 0.1069 - val_acc: 0.9462
Epoch 8/70
36/36 [==============================] - 4s 113ms/step - loss: 0.1198 - acc: 0.9336 - val_loss: 0.1019 - val_acc: 0.9462
Epoch 9/70
36/36 [==============================] - 4s 112ms/step - loss: 0.1142 - acc: 0.9367 - val_loss: 0.0983 - val_acc: 0.9462
Epoch 10/70
36/36 [==============================] - 4s 113ms/step - loss: 0.1068 - acc: 0.9376 - val_loss: 0.0963 - val_acc: 0.9502
Epoch 11/70
36/36 [==============================] - 4s 110ms/step - loss: 0.1016 - acc: 0.9417 - val_loss: 0.0974 - val_acc: 0.9482
Epoch 12/70
36/36 [==============================] - 4s 113ms/step - loss: 0.0942 - acc: 0.9439 - val_loss: 0.0954 - val_acc: 0.9482
Epoch 13/70
36/36 [==============================] - 4s 113ms/step - loss: 0.0878 - acc: 0.9496 - val_loss: 0.0902 - val_acc: 0.9402
Epoch 14/70
36/36 [==============================] - 4s 108ms/step - loss: 0.0854 - acc: 0.9500 - val_loss: 0.0944 - val_acc: 0.9462
Epoch 15/70
36/36 [==============================] - 4s 111ms/step - loss: 0.0789 - acc: 0.9538 - val_loss: 0.0898 - val_acc: 0.9462
Epoch 16/70
36/36 [==============================] - 4s 111ms/step - loss: 0.0714 - acc: 0.9595 - val_loss: 0.0884 - val_acc: 0.9422
Epoch 17/70
36/36 [==============================] - 4s 109ms/step - loss: 0.0657 - acc: 0.9599 - val_loss: 0.0897 - val_acc: 0.9442
Epoch 18/70
36/36 [==============================] - 4s 106ms/step - loss: 0.0620 - acc: 0.9632 - val_loss: 0.0925 - val_acc: 0.9462
Epoch 19/70
36/36 [==============================] - 4s 114ms/step - loss: 0.0576 - acc: 0.9676 - val_loss: 0.0884 - val_acc: 0.9442
Epoch 1/70
20/20 [==============================] - 10s 227ms/step - loss: 0.5888 - acc: 0.7001 - val_loss: 0.5025 - val_acc: 0.6953
Epoch 2/70
20/20 [==============================] - 3s 168ms/step - loss: 0.4760 - acc: 0.7116 - val_loss: 0.4709 - val_acc: 0.6953
Epoch 3/70
20/20 [==============================] - 3s 173ms/step - loss: 0.4472 - acc: 0.7116 - val_loss: 0.4386 - val_acc: 0.6953
Epoch 4/70
20/20 [==============================] - 3s 153ms/step - loss: 0.4133 - acc: 0.7124 - val_loss: 0.3993 - val_acc: 0.6989
Epoch 5/70
20/20 [==============================] - 3s 137ms/step - loss: 0.3764 - acc: 0.7219 - val_loss: 0.3732 - val_acc: 0.7276
Epoch 6/70
20/20 [==============================] - 3s 148ms/step - loss: 0.3459 - acc: 0.7422 - val_loss: 0.3488 - val_acc: 0.7419
Epoch 7/70
20/20 [==============================] - 3s 135ms/step - loss: 0.3240 - acc: 0.7624 - val_loss: 0.3226 - val_acc: 0.7599
Epoch 8/70
20/20 [==============================] - 2s 125ms/step - loss: 0.2979 - acc: 0.7818 - val_loss: 0.3082 - val_acc: 0.7814
Epoch 9/70
20/20 [==============================] - 3s 138ms/step - loss: 0.2813 - acc: 0.7985 - val_loss: 0.2918 - val_acc: 0.8029
Epoch 10/70
20/20 [==============================] - 2s 119ms/step - loss: 0.2645 - acc: 0.8326 - val_loss: 0.2924 - val_acc: 0.7957
Epoch 11/70
20/20 [==============================] - 2s 124ms/step - loss: 0.2554 - acc: 0.8413 - val_loss: 0.2780 - val_acc: 0.8100
Epoch 12/70
20/20 [==============================] - 3s 129ms/step - loss: 0.2353 - acc: 0.8568 - val_loss: 0.2671 - val_acc: 0.8136
Epoch 13/70
20/20 [==============================] - 3s 130ms/step - loss: 0.2236 - acc: 0.8675 - val_loss: 0.2685 - val_acc: 0.8100
Epoch 14/70
20/20 [==============================] - 2s 119ms/step - loss: 0.2122 - acc: 0.8707 - val_loss: 0.2577 - val_acc: 0.8100
Epoch 15/70
20/20 [==============================] - 2s 120ms/step - loss: 0.1992 - acc: 0.8830 - val_loss: 0.2602 - val_acc: 0.8244
Epoch 16/70
20/20 [==============================] - 3s 129ms/step - loss: 0.1886 - acc: 0.8921 - val_loss: 0.2594 - val_acc: 0.8208
Epoch 17/70
20/20 [==============================] - 2s 111ms/step - loss: 0.1738 - acc: 0.9004 - val_loss: 0.2599 - val_acc: 0.8136
Epoch 1/70
12/12 [==============================] - 8s 265ms/step - loss: 0.6458 - acc: 0.4013 - val_loss: 0.6042 - val_acc: 0.5400
Epoch 2/70
12/12 [==============================] - 2s 170ms/step - loss: 0.6068 - acc: 0.5063 - val_loss: 0.5722 - val_acc: 0.5600
Epoch 3/70
12/12 [==============================] - 2s 186ms/step - loss: 0.5655 - acc: 0.6036 - val_loss: 0.5307 - val_acc: 0.6200
Epoch 4/70
12/12 [==============================] - 2s 168ms/step - loss: 0.5156 - acc: 0.6579 - val_loss: 0.4850 - val_acc: 0.6400
Epoch 5/70
12/12 [==============================] - 2s 153ms/step - loss: 0.4657 - acc: 0.6843 - val_loss: 0.4640 - val_acc: 0.6467
Epoch 6/70
12/12 [==============================] - 2s 161ms/step - loss: 0.4251 - acc: 0.7093 - val_loss: 0.4426 - val_acc: 0.6667
Epoch 7/70
12/12 [==============================] - 2s 155ms/step - loss: 0.3974 - acc: 0.7239 - val_loss: 0.4274 - val_acc: 0.6667
Epoch 8/70
12/12 [==============================] - 2s 133ms/step - loss: 0.3779 - acc: 0.7350 - val_loss: 0.4158 - val_acc: 0.7000
Epoch 9/70
12/12 [==============================] - 2s 148ms/step - loss: 0.3699 - acc: 0.7441 - val_loss: 0.4020 - val_acc: 0.7200
Epoch 10/70
12/12 [==============================] - 2s 149ms/step - loss: 0.3500 - acc: 0.7573 - val_loss: 0.4027 - val_acc: 0.7267
Epoch 11/70
12/12 [==============================] - 2s 131ms/step - loss: 0.3429 - acc: 0.7615 - val_loss: 0.3729 - val_acc: 0.7400
Epoch 12/70
12/12 [==============================] - 2s 141ms/step - loss: 0.3258 - acc: 0.7928 - val_loss: 0.3677 - val_acc: 0.7667
Epoch 13/70
12/12 [==============================] - 2s 149ms/step - loss: 0.3209 - acc: 0.7900 - val_loss: 0.3743 - val_acc: 0.7667
Epoch 14/70
12/12 [==============================] - 2s 157ms/step - loss: 0.3200 - acc: 0.7796 - val_loss: 0.3521 - val_acc: 0.7667
Epoch 15/70
12/12 [==============================] - 2s 139ms/step - loss: 0.2998 - acc: 0.8011 - val_loss: 0.3526 - val_acc: 0.7867
Epoch 16/70
12/12 [==============================] - 1s 117ms/step - loss: 0.2883 - acc: 0.8213 - val_loss: 0.3436 - val_acc: 0.7800
Epoch 17/70
12/12 [==============================] - 1s 126ms/step - loss: 0.2849 - acc: 0.8129 - val_loss: 0.3382 - val_acc: 0.7867
Epoch 18/70
12/12 [==============================] - 1s 124ms/step - loss: 0.2697 - acc: 0.8345 - val_loss: 0.3307 - val_acc: 0.7933
Epoch 19/70
12/12 [==============================] - 2s 140ms/step - loss: 0.2635 - acc: 0.8359 - val_loss: 0.3293 - val_acc: 0.7800
Epoch 20/70
12/12 [==============================] - 1s 124ms/step - loss: 0.2468 - acc: 0.8526 - val_loss: 0.3224 - val_acc: 0.8067
Epoch 21/70
12/12 [==============================] - 2s 120ms/step - loss: 0.2373 - acc: 0.8623 - val_loss: 0.3199 - val_acc: 0.8067
Epoch 22/70
12/12 [==============================] - 1s 125ms/step - loss: 0.2329 - acc: 0.8588 - val_loss: 0.3256 - val_acc: 0.8133
Epoch 23/70
12/12 [==============================] - 2s 151ms/step - loss: 0.2171 - acc: 0.8713 - val_loss: 0.3255 - val_acc: 0.8000
Epoch 24/70
12/12 [==============================] - 1s 127ms/step - loss: 0.2067 - acc: 0.8811 - val_loss: 0.3206 - val_acc: 0.8133
Epoch 1/70
18/18 [==============================] - 9s 221ms/step - loss: 0.6116 - acc: 0.5591 - val_loss: 0.4892 - val_acc: 0.7438
Epoch 2/70
18/18 [==============================] - 3s 166ms/step - loss: 0.4708 - acc: 0.7243 - val_loss: 0.4055 - val_acc: 0.7438
Epoch 3/70
18/18 [==============================] - 3s 156ms/step - loss: 0.4233 - acc: 0.7265 - val_loss: 0.3753 - val_acc: 0.7438
Epoch 4/70
18/18 [==============================] - 3s 166ms/step - loss: 0.3948 - acc: 0.7360 - val_loss: 0.3460 - val_acc: 0.7521
Epoch 5/70
18/18 [==============================] - 3s 159ms/step - loss: 0.3566 - acc: 0.7599 - val_loss: 0.3144 - val_acc: 0.8058
Epoch 6/70
18/18 [==============================] - 2s 140ms/step - loss: 0.3233 - acc: 0.8010 - val_loss: 0.2856 - val_acc: 0.8388
Epoch 7/70
18/18 [==============================] - 3s 162ms/step - loss: 0.2971 - acc: 0.8240 - val_loss: 0.2584 - val_acc: 0.8430
Epoch 8/70
18/18 [==============================] - 2s 122ms/step - loss: 0.2729 - acc: 0.8407 - val_loss: 0.2476 - val_acc: 0.8471
Epoch 9/70
18/18 [==============================] - 2s 135ms/step - loss: 0.2514 - acc: 0.8606 - val_loss: 0.2319 - val_acc: 0.8678
Epoch 10/70
18/18 [==============================] - 3s 140ms/step - loss: 0.2310 - acc: 0.8642 - val_loss: 0.2181 - val_acc: 0.8802
Epoch 11/70
18/18 [==============================] - 2s 136ms/step - loss: 0.2088 - acc: 0.8849 - val_loss: 0.2055 - val_acc: 0.8967
Epoch 12/70
18/18 [==============================] - 2s 122ms/step - loss: 0.2010 - acc: 0.8890 - val_loss: 0.2001 - val_acc: 0.8967
Epoch 13/70
18/18 [==============================] - 2s 126ms/step - loss: 0.1881 - acc: 0.8998 - val_loss: 0.1920 - val_acc: 0.8967
Epoch 14/70
18/18 [==============================] - 2s 118ms/step - loss: 0.1765 - acc: 0.9043 - val_loss: 0.1874 - val_acc: 0.9050
Epoch 15/70
18/18 [==============================] - 2s 104ms/step - loss: 0.1603 - acc: 0.9075 - val_loss: 0.1848 - val_acc: 0.9008
Epoch 16/70
18/18 [==============================] - 2s 117ms/step - loss: 0.1521 - acc: 0.9174 - val_loss: 0.1792 - val_acc: 0.8967
Epoch 17/70
18/18 [==============================] - 2s 118ms/step - loss: 0.1399 - acc: 0.9183 - val_loss: 0.1757 - val_acc: 0.9008
Epoch 18/70
18/18 [==============================] - 2s 112ms/step - loss: 0.1291 - acc: 0.9292 - val_loss: 0.1777 - val_acc: 0.8884
Epoch 19/70
18/18 [==============================] - 2s 118ms/step - loss: 0.1215 - acc: 0.9337 - val_loss: 0.1762 - val_acc: 0.9050
Epoch 20/70
18/18 [==============================] - 2s 117ms/step - loss: 0.1122 - acc: 0.9400 - val_loss: 0.1735 - val_acc: 0.8967
Epoch 21/70
18/18 [==============================] - 2s 114ms/step - loss: 0.1025 - acc: 0.9458 - val_loss: 0.1736 - val_acc: 0.9132
Epoch 22/70
18/18 [==============================] - 2s 113ms/step - loss: 0.0932 - acc: 0.9508 - val_loss: 0.1754 - val_acc: 0.9008
Epoch 23/70
18/18 [==============================] - 2s 120ms/step - loss: 0.0911 - acc: 0.9490 - val_loss: 0.1775 - val_acc: 0.9091
Epoch 1/70
13/13 [==============================] - 8s 261ms/step - loss: 0.5445 - acc: 0.5985 - val_loss: 0.5202 - val_acc: 0.5479
Epoch 2/70
13/13 [==============================] - 2s 174ms/step - loss: 0.4927 - acc: 0.5991 - val_loss: 0.4887 - val_acc: 0.5479
Epoch 3/70
13/13 [==============================] - 2s 159ms/step - loss: 0.4704 - acc: 0.6083 - val_loss: 0.4627 - val_acc: 0.6064
Epoch 4/70
13/13 [==============================] - 2s 160ms/step - loss: 0.4415 - acc: 0.6582 - val_loss: 0.4331 - val_acc: 0.6968
Epoch 5/70
13/13 [==============================] - 2s 175ms/step - loss: 0.4028 - acc: 0.7263 - val_loss: 0.4073 - val_acc: 0.7340
Epoch 6/70
13/13 [==============================] - 2s 146ms/step - loss: 0.3722 - acc: 0.7646 - val_loss: 0.3951 - val_acc: 0.7500
Epoch 7/70
13/13 [==============================] - 2s 139ms/step - loss: 0.3552 - acc: 0.7695 - val_loss: 0.3720 - val_acc: 0.7766
Epoch 8/70
13/13 [==============================] - 2s 160ms/step - loss: 0.3315 - acc: 0.7968 - val_loss: 0.3771 - val_acc: 0.7606
Epoch 9/70
13/13 [==============================] - 2s 131ms/step - loss: 0.3180 - acc: 0.7987 - val_loss: 0.3607 - val_acc: 0.7819
Epoch 10/70
13/13 [==============================] - 2s 123ms/step - loss: 0.3039 - acc: 0.8157 - val_loss: 0.3542 - val_acc: 0.7819
Epoch 11/70
13/13 [==============================] - 2s 123ms/step - loss: 0.2909 - acc: 0.8254 - val_loss: 0.3529 - val_acc: 0.7766
Epoch 12/70
13/13 [==============================] - 2s 136ms/step - loss: 0.2776 - acc: 0.8315 - val_loss: 0.3507 - val_acc: 0.7766
Epoch 13/70
13/13 [==============================] - 2s 140ms/step - loss: 0.2695 - acc: 0.8406 - val_loss: 0.3517 - val_acc: 0.7766
Epoch 14/70
13/13 [==============================] - 2s 125ms/step - loss: 0.2588 - acc: 0.8467 - val_loss: 0.3682 - val_acc: 0.7660
Epoch 15/70
13/13 [==============================] - 2s 133ms/step - loss: 0.2398 - acc: 0.8589 - val_loss: 0.3436 - val_acc: 0.7872
Epoch 16/70
13/13 [==============================] - 2s 126ms/step - loss: 0.2322 - acc: 0.8637 - val_loss: 0.3431 - val_acc: 0.7926
Epoch 17/70
13/13 [==============================] - 1s 104ms/step - loss: 0.2222 - acc: 0.8735 - val_loss: 0.3520 - val_acc: 0.7713
Epoch 18/70
13/13 [==============================] - 2s 132ms/step - loss: 0.2031 - acc: 0.8923 - val_loss: 0.3569 - val_acc: 0.7766
Epoch 19/70
13/13 [==============================] - 2s 118ms/step - loss: 0.1917 - acc: 0.8978 - val_loss: 0.3948 - val_acc: 0.7500

In [114]:
df_sentiment_train_pred = {}
df_sentiment_train_true_ = {}

df_sentiment_val_true_ = {}
df_sentiment_val_pred = {}

df_sentiment_test_true_ = {}
df_sentiment_test_pred = {}


for aspect in lst_aspect:
    pred_sentiment_train = sentiment_model_big_con[aspect].predict(padded_sentiment_train[aspect])
    pred_sentiment_val = sentiment_model_big_con[aspect].predict(padded_sentiment_val[aspect])
    pred_sentiment_test = sentiment_model_big_con[aspect].predict(padded_sentiment_test[aspect])
    
    df_sentiment_train_pred[aspect] = np.argmax(pred_sentiment_train, axis=1)
    df_sentiment_train_true_[aspect] = np.argmax(label_sentiment_train[aspect], axis = 1)
    
    df_sentiment_val_pred[aspect] = np.argmax(pred_sentiment_val, axis=1)
    df_sentiment_val_true_[aspect] = np.argmax(label_sentiment_val[aspect], axis = 1)
    
    df_sentiment_test_pred[aspect] = np.argmax(pred_sentiment_test, axis=1)
    df_sentiment_test_true_[aspect] = np.argmax(label_sentiment_test[aspect], axis=1)

40/40 [==============================] - 1s 14ms/step
5/5 [==============================] - 0s 11ms/step
11/11 [==============================] - 0s 12ms/step
79/79 [==============================] - 2s 12ms/step
10/10 [==============================] - 0s 11ms/step
23/23 [==============================] - 0s 12ms/step
143/143 [==============================] - 2s 12ms/step
16/16 [==============================] - 0s 12ms/step
40/40 [==============================] - 0s 12ms/step
79/79 [==============================] - 2s 12ms/step
9/9 [==============================] - 0s 11ms/step
22/22 [==============================] - 0s 12ms/step
45/45 [==============================] - 1s 12ms/step
5/5 [==============================] - 0s 11ms/step
13/13 [==============================] - 0s 11ms/step
70/70 [==============================] - 2s 12ms/step
8/8 [==============================] - 0s 11ms/step
19/19 [==============================] - 0s 12ms/step
52/52 [==============================] - 1s 12ms/step
6/6 [==============================] - 0s 11ms/step
15/15 [==============================] - 0s 12ms/step

In [115]:
def get_pd_report_sentiment(df_sentiment_test_true_, df_sentiment_test_pred):
    sentiment_result_bilstm = {}
    for aspect in lst_aspect:
        sentiment_result_bilstm[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
        sentiment_result_bilstm[aspect]['aspect'] = aspect

    output_sentiment_report = pd.DataFrame()
    for indx, val in sentiment_result_bilstm.items():
        output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

    return output_aspect_report

In [116]:
sentiment_result_gru = {}
# for aspect in lst_aspect:
for aspect in lst_aspect:
    sentiment_result_gru[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
    sentiment_result_gru[aspect]['aspect'] = aspect

output_sentiment_report = pd.DataFrame()
for indx, val in sentiment_result_bilstm.items():
    output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [117]:
output_sentiment_report

              precision    recall  f1-score      support       aspect
0              0.000000  0.000000  0.000000     3.000000        price
1              0.920168  0.886640  0.903093   247.000000        price
2              0.708738  0.802198  0.752577    91.000000        price
accuracy       0.856305  0.856305  0.856305     0.856305        price
macro avg      0.542969  0.562946  0.551890   341.000000        price
weighted avg   0.855650  0.856305  0.854981   341.000000        price
0              0.808511  0.919355  0.860377   124.000000     shipping
1              0.958855  0.976321  0.967509   549.000000     shipping
2              0.200000  0.031250  0.054054    32.000000     shipping
accuracy       0.923404  0.923404  0.923404     0.923404     shipping
macro avg      0.655789  0.642308  0.627313   705.000000     shipping
weighted avg   0.897967  0.923404  0.907204   705.000000     shipping
0              0.737374  0.768421  0.752577    95.000000      outlook
1              0.966132  0.969589  0.967857  1118.000000      outlook
2              0.380000  0.327586  0.351852    58.000000      outlook
accuracy       0.925256  0.925256  0.925256     0.925256      outlook
macro avg      0.694502  0.688532  0.690762  1271.000000      outlook
weighted avg   0.922286  0.925256  0.923656  1271.000000      outlook
0              0.737500  0.602041  0.662921    98.000000      quality
1              0.920000  0.914226  0.917104   478.000000      quality
2              0.476923  0.568807  0.518828   109.000000      quality
accuracy       0.814599  0.814599  0.814599     0.814599      quality
macro avg      0.711474  0.695025  0.699618   685.000000      quality
weighted avg   0.823386  0.814599  0.817364   685.000000      quality
0              0.614943  0.856000  0.715719   125.000000         size
1              0.933333  0.933333  0.933333   165.000000         size
2              0.687500  0.340206  0.455172    97.000000         size
accuracy       0.759690  0.759690  0.759690     0.759690         size
macro avg      0.745259  0.709847  0.701408   387.000000         size
weighted avg   0.768877  0.759690  0.743195   387.000000         size
0              0.783784  0.828571  0.805556   140.000000  shopservice
1              0.922222  0.962877  0.942111   431.000000  shopservice
2              0.500000  0.034483  0.064516    29.000000  shopservice
accuracy       0.886667  0.886667  0.886667     0.886667  shopservice
macro avg      0.735335  0.608644  0.604061   600.000000  shopservice
weighted avg   0.869513  0.886667  0.867831   600.000000  shopservice
0              0.000000  0.000000  0.000000    11.000000      general
1              0.816770  0.922807  0.866557   285.000000      general
2              0.814103  0.697802  0.751479   182.000000      general
accuracy       0.815900  0.815900  0.815900     0.815900      general
macro avg      0.543624  0.540203  0.539345   478.000000      general
weighted avg   0.796959  0.815900  0.802799   478.000000      general

In [118]:
for aspect in lst_aspect:
    print(aspect)
    print(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist()))

price
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.93      0.91      0.92       247
           2       0.76      0.82      0.79        91

    accuracy                           0.88       341
   macro avg       0.56      0.58      0.57       341
weighted avg       0.87      0.88      0.87       341

shipping
              precision    recall  f1-score   support

           0       0.83      0.95      0.89       124
           1       0.96      0.98      0.97       549
           2       0.00      0.00      0.00        32

    accuracy                           0.93       705
   macro avg       0.60      0.64      0.62       705
weighted avg       0.90      0.93      0.91       705

outlook
              precision    recall  f1-score   support

           0       0.75      0.80      0.77        95
           1       0.97      0.97      0.97      1118
           2       0.34      0.33      0.33        58

    accuracy                           0.92      1271
   macro avg       0.68      0.70      0.69      1271
weighted avg       0.92      0.92      0.92      1271

quality
              precision    recall  f1-score   support

           0       0.76      0.68      0.72        98
           1       0.92      0.92      0.92       478
           2       0.52      0.57      0.54       109

    accuracy                           0.83       685
   macro avg       0.73      0.72      0.73       685
weighted avg       0.83      0.83      0.83       685

size
              precision    recall  f1-score   support

           0       0.66      0.78      0.72       125
           1       0.92      0.93      0.93       165
           2       0.64      0.48      0.55        97

    accuracy                           0.77       387
   macro avg       0.74      0.73      0.73       387
weighted avg       0.77      0.77      0.76       387

shopservice
              precision    recall  f1-score   support

           0       0.80      0.84      0.82       140
           1       0.94      0.97      0.95       431
           2       0.36      0.14      0.20        29

    accuracy                           0.90       600
   macro avg       0.70      0.65      0.66       600
weighted avg       0.88      0.90      0.88       600

general
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.82      0.89      0.85       285
           2       0.78      0.71      0.75       182

    accuracy                           0.81       478
   macro avg       0.53      0.54      0.53       478
weighted avg       0.79      0.81      0.79       478

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [119]:
for i in lst_aspect:
    with open(f'{path}elmo_bigru_con_test_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_test_true_[i].tolist(), df_sentiment_test_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [120]:
for i in lst_aspect:
    with open(f'{path}elmo_bigru_con_val_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_val_true_[i].tolist(), df_sentiment_val_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## 5. BiLSTM + BiGRU + Conv1D

In [121]:
def bilstm_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_aspect_size,
                  output_dim=embedding_dim,
                  embeddings_initializer=Constant(embedding_aspect_matrix),
                  input_length=max_len,
                  trainable=True)(input)

    dropout1 = SpatialDropout1D(0.2)(embed)

    lstm = Bidirectional(LSTM(units = 200, activation = 'tanh', return_sequences = True))(dropout1)
    conv_lstm = Conv1D(128, kernel_size = 2, padding = "valid", kernel_initializer = "he_uniform")(lstm)

    gru = Bidirectional(GRU(units = 200, activation = 'tanh', return_sequences = True))(dropout1)
    conv_gru = Conv1D(128, kernel_size = 2, padding = "valid", kernel_initializer = "he_uniform")(gru)


    avg_pool1 = GlobalAveragePooling1D()(conv_lstm)
    max_pool1 = GlobalMaxPooling1D()(conv_lstm)

    avg_pool2 = GlobalAveragePooling1D()(conv_gru)
    max_pool2 = GlobalMaxPooling1D()(conv_gru)
      
      
    concat = Concatenate(axis=-1)([avg_pool1, max_pool1, avg_pool2, max_pool2])
 
    aspect_dense1 = Dense(units = 256, activation = 'relu')(concat)
    aspect_dense2 = Dense(128, activation='relu')(aspect_dense1)
    aspect_dropout1 = Dropout(0.2)(aspect_dense2)
    aspect_dense3 = Dense(64, activation='relu')(aspect_dropout1)
    aspect_dense4 = Dense(32, activation='relu')(aspect_dense3)
    aspect_dense5 = Dense(8, activation='sigmoid')(aspect_dense4)

    
    aspect_model = tf.keras.Model(inputs = input, outputs = aspect_dense5)
    aspect_model.compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    # Fit model
    history = aspect_model.fit(x=padded_aspect_train,
                               y=label_aspect_train.to_numpy(),
                               validation_data=(padded_aspect_val, label_aspect_val.to_numpy()),
                               batch_size = 128,
                               epochs=epochs,
                               callbacks = [callback],
                               verbose=1)
    
    return aspect_model

def bilstm_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val, epochs=70):
    input = Input(shape=(max_len,))
    embed = Embedding(input_dim=vocab_sentiment_size[aspect],
                  output_dim=embedding_dim,
                  embeddings_initializer=Constant(embedding_sentiment_matrix[aspect]),
                  input_length=max_len,
                  trainable=True)(input)
  
    dropout1 = SpatialDropout1D(0.2)(embed)

    lstm = Bidirectional(LSTM(units = 200, activation = 'tanh', return_sequences = True))(dropout1)
    conv_lstm = Conv1D(128, kernel_size = 2, padding = "valid", kernel_initializer = "he_uniform")(lstm)

    gru = Bidirectional(GRU(units = 200, activation = 'tanh', return_sequences = True))(dropout1)
    conv_gru = Conv1D(128, kernel_size = 2, padding = "valid", kernel_initializer = "he_uniform")(gru)


    avg_pool1 = GlobalAveragePooling1D()(conv_lstm)
    max_pool1 = GlobalMaxPooling1D()(conv_lstm)

    avg_pool2 = GlobalAveragePooling1D()(conv_gru)
    max_pool2 = GlobalMaxPooling1D()(conv_gru)
      
      
    concat = Concatenate(axis=-1)([avg_pool1, max_pool1, avg_pool2, max_pool2])

    sentiment_dense1 = Dense(units = 256, activation = 'relu')(concat)
    sentiment_dense2 = Dense(128, activation='relu')(sentiment_dense1)
    sentiment_dropout1 = Dropout(0.2)(sentiment_dense2)
    sentiment_dense3 = Dense(64, activation='relu')(sentiment_dropout1)
    sentiment_dense4 = Dense(32, activation='relu')(sentiment_dense3)
    out_sentiment = Dense(units = 3, activation = 'softmax')(sentiment_dense4)
    
    sentiment_model_lgc[aspect] = tf.keras.Model(inputs = input, outputs = out_sentiment)
    sentiment_model_lgc[aspect].compile(optimizer=Adam(learning_rate = 0.0001), loss='binary_crossentropy', metrics=['acc'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    
    history = sentiment_model_lgc[aspect].fit(x=padded_sentiment_train[aspect],
                                          y=label_sentiment_train[aspect],
                                          validation_data=(padded_sentiment_val[aspect], label_sentiment_val[aspect]),
                                          batch_size = 128,
                                          epochs=epochs,
                                          callbacks = [callback],
                                          verbose=1)
    
    return sentiment_model_lgc[aspect]

In [122]:
aspect_model_lgc = bilstm_aspect(vocab_aspect_size, embedding_dim, max_len, embedding_aspect_matrix, padded_aspect_train, padded_aspect_val, label_aspect_train, label_aspect_val)

Epoch 1/70
66/66 [==============================] - 29s 304ms/step - loss: 0.5298 - acc: 0.3075 - val_loss: 0.4518 - val_acc: 0.4209
Epoch 2/70
66/66 [==============================] - 17s 263ms/step - loss: 0.4288 - acc: 0.4721 - val_loss: 0.3869 - val_acc: 0.5085
Epoch 3/70
66/66 [==============================] - 17s 261ms/step - loss: 0.3741 - acc: 0.5147 - val_loss: 0.3290 - val_acc: 0.5011
Epoch 4/70
66/66 [==============================] - 16s 248ms/step - loss: 0.3191 - acc: 0.5387 - val_loss: 0.2770 - val_acc: 0.5994
Epoch 5/70
66/66 [==============================] - 16s 239ms/step - loss: 0.2690 - acc: 0.5780 - val_loss: 0.2448 - val_acc: 0.5865
Epoch 6/70
66/66 [==============================] - 16s 239ms/step - loss: 0.2412 - acc: 0.5780 - val_loss: 0.2225 - val_acc: 0.6015
Epoch 7/70
66/66 [==============================] - 16s 237ms/step - loss: 0.2203 - acc: 0.5943 - val_loss: 0.2140 - val_acc: 0.5908
Epoch 8/70
66/66 [==============================] - 16s 236ms/step - loss: 0.2063 - acc: 0.5919 - val_loss: 0.2093 - val_acc: 0.5919
Epoch 9/70
66/66 [==============================] - 15s 235ms/step - loss: 0.1941 - acc: 0.6038 - val_loss: 0.2040 - val_acc: 0.6261
Epoch 10/70
66/66 [==============================] - 15s 231ms/step - loss: 0.1833 - acc: 0.6068 - val_loss: 0.1988 - val_acc: 0.5929
Epoch 11/70
66/66 [==============================] - 15s 233ms/step - loss: 0.1734 - acc: 0.6102 - val_loss: 0.1962 - val_acc: 0.5823
Epoch 12/70
66/66 [==============================] - 15s 228ms/step - loss: 0.1678 - acc: 0.6113 - val_loss: 0.2001 - val_acc: 0.5823
Epoch 13/70
66/66 [==============================] - 15s 228ms/step - loss: 0.1599 - acc: 0.6127 - val_loss: 0.1966 - val_acc: 0.5812
Epoch 14/70
66/66 [==============================] - 15s 233ms/step - loss: 0.1515 - acc: 0.6134 - val_loss: 0.1972 - val_acc: 0.5716

In [123]:
pred_train = aspect_model_lgc.predict(padded_aspect_train)
pred_val = aspect_model_lgc.predict(padded_aspect_val)
pred_test = aspect_model_lgc.predict(padded_aspect_test)

df_train_pred = round(pd.DataFrame(pred_train), 0)
df_train_true_ = label_aspect_train
df_train_pred.columns = df_train_true_.columns

df_val_pred = round(pd.DataFrame(pred_val), 0)
df_val_true_ = label_aspect_val
df_val_pred.columns = df_val_true_.columns

df_test_pred = round(pd.DataFrame(pred_test), 0)
df_test_true_ = label_aspect_test
df_test_pred.columns = df_test_true_.columns

264/264 [==============================] - 8s 25ms/step
30/30 [==============================] - 1s 25ms/step
74/74 [==============================] - 2s 25ms/step

In [124]:
def get_pd_report(label_aspect_train, df_test_true_, df_test_pred):
    aspect_result_bilstm_report = {}
    for col in label_aspect_train.columns:
        aspect_result_bilstm = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
        aspect_result_bilstm_report[col] = pd.DataFrame(aspect_result_bilstm).T
        aspect_result_bilstm_report[col]['aspect'] = col
        
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_bilstm_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_bilstm_report[indx]])
    
    return output_aspect_report

In [125]:
aspect_result_bilstm_report = {}
for col in label_aspect_train.columns:
    print(col)
    aspect_result_bilstm = classification_report(df_test_true_[col], df_test_pred[col], output_dict=True)
    print(aspect_result_bilstm)
    
    aspect_result_bilstm_report[col] = pd.DataFrame(aspect_result_bilstm).T
    aspect_result_bilstm_report[col]['aspect'] = col
    
    output_aspect_report = pd.DataFrame()
    for indx, val in aspect_result_bilstm_report.items():
        output_aspect_report = pd.concat([output_aspect_report, aspect_result_bilstm_report[indx]])

is_price
{'0': {'precision': 0.9572400388726919, 'recall': 0.9854927463731866, 'f1-score': 0.9711609563717033, 'support': 1999}, '1': {'precision': 0.8971631205673759, 'recall': 0.7419354838709677, 'f1-score': 0.8121990369181381, 'support': 341}, 'accuracy': 0.95, 'macro avg': {'precision': 0.9272015797200339, 'recall': 0.8637141151220772, 'f1-score': 0.8916799966449207, 'support': 2340}, 'weighted avg': {'precision': 0.9484852400940113, 'recall': 0.95, 'f1-score': 0.9479959928957777, 'support': 2340}}
is_shipping
{'0': {'precision': 0.9809113300492611, 'recall': 0.9743119266055046, 'f1-score': 0.9776004909481436, 'support': 1635}, '1': {'precision': 0.9413407821229051, 'recall': 0.9560283687943263, 'f1-score': 0.9486277269528501, 'support': 705}, 'accuracy': 0.9688034188034188, 'macro avg': {'precision': 0.961126056086083, 'recall': 0.9651701476999155, 'f1-score': 0.9631141089504969, 'support': 2340}, 'weighted avg': {'precision': 0.9689894341996538, 'recall': 0.9688034188034188, 'f1-score': 0.9688715171803308, 'support': 2340}}
is_outlook
{'0': {'precision': 0.9019248395967002, 'recall': 0.9204864359214219, 'f1-score': 0.9111111111111111, 'support': 1069}, '1': {'precision': 0.9319455564451561, 'recall': 0.9158143194335169, 'f1-score': 0.9238095238095236, 'support': 1271}, 'accuracy': 0.9179487179487179, 'macro avg': {'precision': 0.9169351980209282, 'recall': 0.9181503776774693, 'f1-score': 0.9174603174603173, 'support': 2340}, 'weighted avg': {'precision': 0.9182309640045581, 'recall': 0.9179487179487179, 'f1-score': 0.9180084113417446, 'support': 2340}}
is_quality
{'0': {'precision': 0.917513448894202, 'recall': 0.9280532043530835, 'f1-score': 0.9227532311391645, 'support': 1654}, '1': {'precision': 0.8215892053973014, 'recall': 0.7988338192419825, 'f1-score': 0.8100517368810052, 'support': 686}, 'accuracy': 0.8901709401709401, 'macro avg': {'precision': 0.8695513271457518, 'recall': 0.863443511797533, 'f1-score': 0.8664024840100848, 'support': 2340}, 'weighted avg': {'precision': 0.8893920681083584, 'recall': 0.8901709401709401, 'f1-score': 0.8897133913694649, 'support': 2340}}
is_size
{'0': {'precision': 0.9731958762886598, 'recall': 0.9667178699436764, 'f1-score': 0.9699460570254302, 'support': 1953}, '1': {'precision': 0.8375, 'recall': 0.8656330749354005, 'f1-score': 0.8513341804320204, 'support': 387}, 'accuracy': 0.95, 'macro avg': {'precision': 0.9053479381443299, 'recall': 0.9161754724395385, 'f1-score': 0.9106401187287253, 'support': 2340}, 'weighted avg': {'precision': 0.9507538659793815, 'recall': 0.95, 'f1-score': 0.9503294774349816, 'support': 2340}}
is_shopservice
{'0': {'precision': 0.9289647577092511, 'recall': 0.9695402298850575, 'f1-score': 0.9488188976377954, 'support': 1740}, '1': {'precision': 0.898854961832061, 'recall': 0.785, 'f1-score': 0.8380782918149466, 'support': 600}, 'accuracy': 0.9222222222222223, 'macro avg': {'precision': 0.9139098597706561, 'recall': 0.8772701149425288, 'f1-score': 0.8934485947263711, 'support': 2340}, 'weighted avg': {'precision': 0.9212442972279202, 'recall': 0.9222222222222223, 'f1-score': 0.9204238705037316, 'support': 2340}}
is_general
{'0': {'precision': 0.901740020470829, 'recall': 0.9468027941966685, 'f1-score': 0.9237221494102227, 'support': 1861}, '1': {'precision': 0.7435233160621761, 'recall': 0.5991649269311065, 'f1-score': 0.6635838150289016, 'support': 479}, 'accuracy': 0.8756410256410256, 'macro avg': {'precision': 0.8226316682665026, 'recall': 0.7729838605638875, 'f1-score': 0.7936529822195622, 'support': 2340}, 'weighted avg': {'precision': 0.8693529258504253, 'recall': 0.8756410256410256, 'f1-score': 0.8704716100219095, 'support': 2340}}
is_others
{'0': {'precision': 0.9801202034211743, 'recall': 0.9855880985588099, 'f1-score': 0.9828465461288827, 'support': 2151}, '1': {'precision': 0.8248587570621468, 'recall': 0.7724867724867724, 'f1-score': 0.7978142076502732, 'support': 189}, 'accuracy': 0.9683760683760684, 'macro avg': {'precision': 0.9024894802416605, 'recall': 0.8790374355227912, 'f1-score': 0.890330376889578, 'support': 2340}, 'weighted avg': {'precision': 0.9675798558306374, 'recall': 0.9683760683760684, 'f1-score': 0.9679016264825334, 'support': 2340}}

In [126]:
for col in label_aspect_train.columns:
    print(col)
    aspect_result = classification_report(df_test_true_[col], df_test_pred[col])

    print(aspect_result)

is_price
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1999
           1       0.90      0.74      0.81       341

    accuracy                           0.95      2340
   macro avg       0.93      0.86      0.89      2340
weighted avg       0.95      0.95      0.95      2340

is_shipping
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1635
           1       0.94      0.96      0.95       705

    accuracy                           0.97      2340
   macro avg       0.96      0.97      0.96      2340
weighted avg       0.97      0.97      0.97      2340

is_outlook
              precision    recall  f1-score   support

           0       0.90      0.92      0.91      1069
           1       0.93      0.92      0.92      1271

    accuracy                           0.92      2340
   macro avg       0.92      0.92      0.92      2340
weighted avg       0.92      0.92      0.92      2340

is_quality
              precision    recall  f1-score   support

           0       0.92      0.93      0.92      1654
           1       0.82      0.80      0.81       686

    accuracy                           0.89      2340
   macro avg       0.87      0.86      0.87      2340
weighted avg       0.89      0.89      0.89      2340

is_size
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1953
           1       0.84      0.87      0.85       387

    accuracy                           0.95      2340
   macro avg       0.91      0.92      0.91      2340
weighted avg       0.95      0.95      0.95      2340

is_shopservice
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      1740
           1       0.90      0.79      0.84       600

    accuracy                           0.92      2340
   macro avg       0.91      0.88      0.89      2340
weighted avg       0.92      0.92      0.92      2340

is_general
              precision    recall  f1-score   support

           0       0.90      0.95      0.92      1861
           1       0.74      0.60      0.66       479

    accuracy                           0.88      2340
   macro avg       0.82      0.77      0.79      2340
weighted avg       0.87      0.88      0.87      2340

is_others
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      2151
           1       0.82      0.77      0.80       189

    accuracy                           0.97      2340
   macro avg       0.90      0.88      0.89      2340
weighted avg       0.97      0.97      0.97      2340

In [127]:
path = '/kaggle/working/'

In [128]:
save_result_pred_aspect(df_test_true_, df_test_pred, data_eval = 'test', model_type = 'bilstm_bigru_con')
save_result_pred_aspect(df_val_true_, df_val_pred, data_eval = 'eval', model_type = 'bilstm_bigru_con')

In [129]:
lst_aspect = []
for col in label_aspect_train.columns.values:
    if col!='is_others':
        lst_aspect.append(col.split('_')[1])

In [130]:
sentiment_model_lgc = {}
for aspect in lst_aspect:
    sentiment_model_lgc[aspect] = bilstm_polarity(aspect, vocab_sentiment_size, embedding_dim, max_len, embedding_sentiment_matrix, padded_sentiment_train, padded_sentiment_val, label_sentiment_train, label_sentiment_val)

Epoch 1/70
10/10 [==============================] - 13s 449ms/step - loss: 0.6779 - acc: 0.2470 - val_loss: 0.6236 - val_acc: 0.2246
Epoch 2/70
10/10 [==============================] - 3s 292ms/step - loss: 0.6056 - acc: 0.3221 - val_loss: 0.5464 - val_acc: 0.7826
Epoch 3/70
10/10 [==============================] - 3s 288ms/step - loss: 0.5382 - acc: 0.5548 - val_loss: 0.4657 - val_acc: 0.7681
Epoch 4/70
10/10 [==============================] - 3s 270ms/step - loss: 0.4591 - acc: 0.7258 - val_loss: 0.3889 - val_acc: 0.7681
Epoch 5/70
10/10 [==============================] - 3s 257ms/step - loss: 0.4047 - acc: 0.7378 - val_loss: 0.3565 - val_acc: 0.7681
Epoch 6/70
10/10 [==============================] - 3s 262ms/step - loss: 0.3704 - acc: 0.7426 - val_loss: 0.3261 - val_acc: 0.7681
Epoch 7/70
10/10 [==============================] - 3s 251ms/step - loss: 0.3342 - acc: 0.7538 - val_loss: 0.2775 - val_acc: 0.7826
Epoch 8/70
10/10 [==============================] - 3s 295ms/step - loss: 0.2750 - acc: 0.8265 - val_loss: 0.2292 - val_acc: 0.8696
Epoch 9/70
10/10 [==============================] - 3s 289ms/step - loss: 0.2304 - acc: 0.8745 - val_loss: 0.2074 - val_acc: 0.8913
Epoch 10/70
10/10 [==============================] - 3s 258ms/step - loss: 0.1996 - acc: 0.8873 - val_loss: 0.1963 - val_acc: 0.8986
Epoch 11/70
10/10 [==============================] - 3s 261ms/step - loss: 0.1836 - acc: 0.9033 - val_loss: 0.1916 - val_acc: 0.9058
Epoch 12/70
10/10 [==============================] - 2s 253ms/step - loss: 0.1736 - acc: 0.9089 - val_loss: 0.1859 - val_acc: 0.8986
Epoch 13/70
10/10 [==============================] - 2s 237ms/step - loss: 0.1574 - acc: 0.9185 - val_loss: 0.1766 - val_acc: 0.9130
Epoch 14/70
10/10 [==============================] - 3s 250ms/step - loss: 0.1401 - acc: 0.9345 - val_loss: 0.1764 - val_acc: 0.9130
Epoch 15/70
10/10 [==============================] - 2s 243ms/step - loss: 0.1258 - acc: 0.9424 - val_loss: 0.1875 - val_acc: 0.8913
Epoch 16/70
10/10 [==============================] - 3s 251ms/step - loss: 0.1248 - acc: 0.9440 - val_loss: 0.1860 - val_acc: 0.8913
Epoch 17/70
10/10 [==============================] - 3s 264ms/step - loss: 0.1195 - acc: 0.9345 - val_loss: 0.1735 - val_acc: 0.8986
Epoch 18/70
10/10 [==============================] - 2s 249ms/step - loss: 0.1058 - acc: 0.9592 - val_loss: 0.1703 - val_acc: 0.9058
Epoch 19/70
10/10 [==============================] - 2s 247ms/step - loss: 0.0928 - acc: 0.9656 - val_loss: 0.1848 - val_acc: 0.8841
Epoch 20/70
10/10 [==============================] - 2s 237ms/step - loss: 0.0895 - acc: 0.9624 - val_loss: 0.1838 - val_acc: 0.8913
Epoch 21/70
10/10 [==============================] - 2s 230ms/step - loss: 0.0774 - acc: 0.9712 - val_loss: 0.1835 - val_acc: 0.8986
Epoch 1/70
20/20 [==============================] - 16s 355ms/step - loss: 0.4993 - acc: 0.7643 - val_loss: 0.3881 - val_acc: 0.7799
Epoch 2/70
20/20 [==============================] - 6s 278ms/step - loss: 0.3625 - acc: 0.7930 - val_loss: 0.3319 - val_acc: 0.7799
Epoch 3/70
20/20 [==============================] - 5s 264ms/step - loss: 0.2897 - acc: 0.8113 - val_loss: 0.2265 - val_acc: 0.8932
Epoch 4/70
20/20 [==============================] - 6s 278ms/step - loss: 0.2029 - acc: 0.9057 - val_loss: 0.1910 - val_acc: 0.8997
Epoch 5/70
20/20 [==============================] - 6s 278ms/step - loss: 0.1711 - acc: 0.9164 - val_loss: 0.1697 - val_acc: 0.9029
Epoch 6/70
20/20 [==============================] - 5s 249ms/step - loss: 0.1519 - acc: 0.9224 - val_loss: 0.1565 - val_acc: 0.9094
Epoch 7/70
20/20 [==============================] - 5s 255ms/step - loss: 0.1427 - acc: 0.9268 - val_loss: 0.1437 - val_acc: 0.9159
Epoch 8/70
20/20 [==============================] - 5s 247ms/step - loss: 0.1308 - acc: 0.9319 - val_loss: 0.1427 - val_acc: 0.9159
Epoch 9/70
20/20 [==============================] - 5s 250ms/step - loss: 0.1234 - acc: 0.9323 - val_loss: 0.1413 - val_acc: 0.9223
Epoch 10/70
20/20 [==============================] - 5s 239ms/step - loss: 0.1163 - acc: 0.9375 - val_loss: 0.1425 - val_acc: 0.9159
Epoch 11/70
20/20 [==============================] - 5s 245ms/step - loss: 0.1039 - acc: 0.9391 - val_loss: 0.1473 - val_acc: 0.9159
Epoch 12/70
20/20 [==============================] - 5s 237ms/step - loss: 0.0958 - acc: 0.9423 - val_loss: 0.1395 - val_acc: 0.9320
Epoch 13/70
20/20 [==============================] - 4s 225ms/step - loss: 0.0878 - acc: 0.9475 - val_loss: 0.1399 - val_acc: 0.9288
Epoch 14/70
20/20 [==============================] - 5s 237ms/step - loss: 0.0771 - acc: 0.9562 - val_loss: 0.1420 - val_acc: 0.9320
Epoch 15/70
20/20 [==============================] - 5s 233ms/step - loss: 0.0683 - acc: 0.9642 - val_loss: 0.1406 - val_acc: 0.9256
Epoch 1/70
36/36 [==============================] - 20s 321ms/step - loss: 0.3332 - acc: 0.8764 - val_loss: 0.2132 - val_acc: 0.9024
Epoch 2/70
36/36 [==============================] - 10s 271ms/step - loss: 0.2308 - acc: 0.8777 - val_loss: 0.1694 - val_acc: 0.9024
Epoch 3/70
36/36 [==============================] - 9s 254ms/step - loss: 0.1800 - acc: 0.8865 - val_loss: 0.1361 - val_acc: 0.9382
Epoch 4/70
36/36 [==============================] - 9s 245ms/step - loss: 0.1472 - acc: 0.9172 - val_loss: 0.1197 - val_acc: 0.9382
Epoch 5/70
36/36 [==============================] - 9s 246ms/step - loss: 0.1303 - acc: 0.9286 - val_loss: 0.1109 - val_acc: 0.9442
Epoch 6/70
36/36 [==============================] - 9s 236ms/step - loss: 0.1162 - acc: 0.9319 - val_loss: 0.1027 - val_acc: 0.9462
Epoch 7/70
36/36 [==============================] - 8s 237ms/step - loss: 0.1072 - acc: 0.9354 - val_loss: 0.1013 - val_acc: 0.9462
Epoch 8/70
36/36 [==============================] - 8s 235ms/step - loss: 0.0944 - acc: 0.9437 - val_loss: 0.0933 - val_acc: 0.9482
Epoch 9/70
36/36 [==============================] - 8s 235ms/step - loss: 0.0894 - acc: 0.9463 - val_loss: 0.0997 - val_acc: 0.9363
Epoch 10/70
36/36 [==============================] - 8s 225ms/step - loss: 0.0780 - acc: 0.9538 - val_loss: 0.0914 - val_acc: 0.9422
Epoch 11/70
36/36 [==============================] - 8s 229ms/step - loss: 0.0673 - acc: 0.9614 - val_loss: 0.0934 - val_acc: 0.9422
Epoch 12/70
36/36 [==============================] - 8s 233ms/step - loss: 0.0572 - acc: 0.9689 - val_loss: 0.0902 - val_acc: 0.9402
Epoch 13/70
36/36 [==============================] - 9s 239ms/step - loss: 0.0485 - acc: 0.9748 - val_loss: 0.0921 - val_acc: 0.9502
Epoch 14/70
36/36 [==============================] - 8s 226ms/step - loss: 0.0418 - acc: 0.9825 - val_loss: 0.0969 - val_acc: 0.9522
Epoch 15/70
36/36 [==============================] - 8s 229ms/step - loss: 0.0361 - acc: 0.9829 - val_loss: 0.1035 - val_acc: 0.9462
Epoch 1/70
20/20 [==============================] - 16s 365ms/step - loss: 0.5337 - acc: 0.7061 - val_loss: 0.4795 - val_acc: 0.6953
Epoch 2/70
20/20 [==============================] - 6s 285ms/step - loss: 0.4492 - acc: 0.7116 - val_loss: 0.4276 - val_acc: 0.6953
Epoch 3/70
20/20 [==============================] - 5s 262ms/step - loss: 0.3987 - acc: 0.7152 - val_loss: 0.3827 - val_acc: 0.7276
Epoch 4/70
20/20 [==============================] - 5s 271ms/step - loss: 0.3539 - acc: 0.7549 - val_loss: 0.3496 - val_acc: 0.7527
Epoch 5/70
20/20 [==============================] - 5s 266ms/step - loss: 0.3197 - acc: 0.7791 - val_loss: 0.3338 - val_acc: 0.7527
Epoch 6/70
20/20 [==============================] - 5s 251ms/step - loss: 0.2909 - acc: 0.7949 - val_loss: 0.3116 - val_acc: 0.7670
Epoch 7/70
20/20 [==============================] - 5s 260ms/step - loss: 0.2710 - acc: 0.8144 - val_loss: 0.2906 - val_acc: 0.7885
Epoch 8/70
20/20 [==============================] - 5s 250ms/step - loss: 0.2507 - acc: 0.8314 - val_loss: 0.2824 - val_acc: 0.7957
Epoch 9/70
20/20 [==============================] - 5s 252ms/step - loss: 0.2268 - acc: 0.8512 - val_loss: 0.2734 - val_acc: 0.7993
Epoch 10/70
20/20 [==============================] - 5s 242ms/step - loss: 0.2052 - acc: 0.8671 - val_loss: 0.2676 - val_acc: 0.8172
Epoch 11/70
20/20 [==============================] - 5s 247ms/step - loss: 0.1941 - acc: 0.8754 - val_loss: 0.2655 - val_acc: 0.8100
Epoch 12/70
20/20 [==============================] - 5s 244ms/step - loss: 0.1735 - acc: 0.8949 - val_loss: 0.2604 - val_acc: 0.8100
Epoch 13/70
20/20 [==============================] - 5s 242ms/step - loss: 0.1507 - acc: 0.9167 - val_loss: 0.2571 - val_acc: 0.8244
Epoch 14/70
20/20 [==============================] - 5s 241ms/step - loss: 0.1398 - acc: 0.9171 - val_loss: 0.2546 - val_acc: 0.8280
Epoch 15/70
20/20 [==============================] - 5s 242ms/step - loss: 0.1172 - acc: 0.9385 - val_loss: 0.2601 - val_acc: 0.8244
Epoch 16/70
20/20 [==============================] - 4s 225ms/step - loss: 0.1058 - acc: 0.9429 - val_loss: 0.2790 - val_acc: 0.8315
Epoch 17/70
20/20 [==============================] - 5s 230ms/step - loss: 0.0883 - acc: 0.9611 - val_loss: 0.2676 - val_acc: 0.8315
Epoch 1/70
12/12 [==============================] - 14s 413ms/step - loss: 0.6511 - acc: 0.3658 - val_loss: 0.6278 - val_acc: 0.5467
Epoch 2/70
12/12 [==============================] - 3s 276ms/step - loss: 0.6204 - acc: 0.5556 - val_loss: 0.6069 - val_acc: 0.6400
Epoch 3/70
12/12 [==============================] - 3s 280ms/step - loss: 0.5943 - acc: 0.6210 - val_loss: 0.5743 - val_acc: 0.6400
Epoch 4/70
12/12 [==============================] - 3s 272ms/step - loss: 0.5593 - acc: 0.6606 - val_loss: 0.5397 - val_acc: 0.6533
Epoch 5/70
12/12 [==============================] - 3s 267ms/step - loss: 0.5136 - acc: 0.6961 - val_loss: 0.5010 - val_acc: 0.6333
Epoch 6/70
12/12 [==============================] - 3s 247ms/step - loss: 0.4738 - acc: 0.7038 - val_loss: 0.4578 - val_acc: 0.6733
Epoch 7/70
12/12 [==============================] - 3s 252ms/step - loss: 0.4346 - acc: 0.7170 - val_loss: 0.4225 - val_acc: 0.7067
Epoch 8/70
12/12 [==============================] - 3s 254ms/step - loss: 0.3978 - acc: 0.7385 - val_loss: 0.3958 - val_acc: 0.7333
Epoch 9/70
12/12 [==============================] - 3s 253ms/step - loss: 0.3675 - acc: 0.7684 - val_loss: 0.3676 - val_acc: 0.7733
Epoch 10/70
12/12 [==============================] - 3s 241ms/step - loss: 0.3424 - acc: 0.7796 - val_loss: 0.3510 - val_acc: 0.7800
Epoch 11/70
12/12 [==============================] - 3s 256ms/step - loss: 0.3280 - acc: 0.7914 - val_loss: 0.3439 - val_acc: 0.7733
Epoch 12/70
12/12 [==============================] - 3s 258ms/step - loss: 0.3028 - acc: 0.8046 - val_loss: 0.3383 - val_acc: 0.7867
Epoch 13/70
12/12 [==============================] - 3s 247ms/step - loss: 0.2928 - acc: 0.8227 - val_loss: 0.3280 - val_acc: 0.8133
Epoch 14/70
12/12 [==============================] - 3s 239ms/step - loss: 0.2816 - acc: 0.8164 - val_loss: 0.3237 - val_acc: 0.8133
Epoch 15/70
12/12 [==============================] - 3s 248ms/step - loss: 0.2635 - acc: 0.8366 - val_loss: 0.3475 - val_acc: 0.8200
Epoch 16/70
12/12 [==============================] - 3s 221ms/step - loss: 0.2474 - acc: 0.8512 - val_loss: 0.3299 - val_acc: 0.8133
Epoch 17/70
12/12 [==============================] - 3s 240ms/step - loss: 0.2258 - acc: 0.8672 - val_loss: 0.3461 - val_acc: 0.8133
Epoch 1/70
18/18 [==============================] - 17s 364ms/step - loss: 0.6416 - acc: 0.4792 - val_loss: 0.5367 - val_acc: 0.7438
Epoch 2/70
18/18 [==============================] - 5s 283ms/step - loss: 0.4874 - acc: 0.7238 - val_loss: 0.3973 - val_acc: 0.7438
Epoch 3/70
18/18 [==============================] - 5s 259ms/step - loss: 0.4076 - acc: 0.7374 - val_loss: 0.3558 - val_acc: 0.7479
Epoch 4/70
18/18 [==============================] - 5s 264ms/step - loss: 0.3574 - acc: 0.7739 - val_loss: 0.3190 - val_acc: 0.7975
Epoch 5/70
18/18 [==============================] - 5s 263ms/step - loss: 0.3198 - acc: 0.8127 - val_loss: 0.2801 - val_acc: 0.8388
Epoch 6/70
18/18 [==============================] - 5s 261ms/step - loss: 0.2865 - acc: 0.8461 - val_loss: 0.2634 - val_acc: 0.8471
Epoch 7/70
18/18 [==============================] - 5s 250ms/step - loss: 0.2558 - acc: 0.8624 - val_loss: 0.2326 - val_acc: 0.8802
Epoch 8/70
18/18 [==============================] - 5s 253ms/step - loss: 0.2281 - acc: 0.8791 - val_loss: 0.2160 - val_acc: 0.8926
Epoch 9/70
18/18 [==============================] - 4s 241ms/step - loss: 0.2063 - acc: 0.8903 - val_loss: 0.2195 - val_acc: 0.8678
Epoch 10/70
18/18 [==============================] - 4s 229ms/step - loss: 0.1963 - acc: 0.8940 - val_loss: 0.1979 - val_acc: 0.8843
Epoch 11/70
18/18 [==============================] - 4s 234ms/step - loss: 0.1732 - acc: 0.9084 - val_loss: 0.1902 - val_acc: 0.8926
Epoch 12/70
18/18 [==============================] - 4s 250ms/step - loss: 0.1558 - acc: 0.9206 - val_loss: 0.1988 - val_acc: 0.8802
Epoch 13/70
18/18 [==============================] - 4s 233ms/step - loss: 0.1411 - acc: 0.9269 - val_loss: 0.1864 - val_acc: 0.9008
Epoch 14/70
18/18 [==============================] - 4s 231ms/step - loss: 0.1220 - acc: 0.9337 - val_loss: 0.2006 - val_acc: 0.8802
Epoch 15/70
18/18 [==============================] - 4s 227ms/step - loss: 0.1120 - acc: 0.9359 - val_loss: 0.1979 - val_acc: 0.8843
Epoch 16/70
18/18 [==============================] - 4s 237ms/step - loss: 0.1066 - acc: 0.9377 - val_loss: 0.1902 - val_acc: 0.9050
Epoch 1/70
13/13 [==============================] - 14s 408ms/step - loss: 0.6789 - acc: 0.3388 - val_loss: 0.6194 - val_acc: 0.4415
Epoch 2/70
13/13 [==============================] - 4s 290ms/step - loss: 0.5929 - acc: 0.4532 - val_loss: 0.5379 - val_acc: 0.5585
Epoch 3/70
13/13 [==============================] - 4s 269ms/step - loss: 0.5301 - acc: 0.5505 - val_loss: 0.5093 - val_acc: 0.5479
Epoch 4/70
13/13 [==============================] - 4s 281ms/step - loss: 0.5022 - acc: 0.5931 - val_loss: 0.4971 - val_acc: 0.5479
Epoch 5/70
13/13 [==============================] - 4s 277ms/step - loss: 0.4838 - acc: 0.6259 - val_loss: 0.4819 - val_acc: 0.5745
Epoch 6/70
13/13 [==============================] - 3s 264ms/step - loss: 0.4631 - acc: 0.6715 - val_loss: 0.4424 - val_acc: 0.6968
Epoch 7/70
13/13 [==============================] - 3s 263ms/step - loss: 0.4242 - acc: 0.7409 - val_loss: 0.4068 - val_acc: 0.7287
Epoch 8/70
13/13 [==============================] - 3s 249ms/step - loss: 0.3824 - acc: 0.7743 - val_loss: 0.3832 - val_acc: 0.7447
Epoch 9/70
13/13 [==============================] - 3s 244ms/step - loss: 0.3442 - acc: 0.7853 - val_loss: 0.3714 - val_acc: 0.7713
Epoch 10/70
13/13 [==============================] - 3s 265ms/step - loss: 0.3272 - acc: 0.8054 - val_loss: 0.3625 - val_acc: 0.7819
Epoch 11/70
13/13 [==============================] - 3s 261ms/step - loss: 0.3105 - acc: 0.8193 - val_loss: 0.3572 - val_acc: 0.7766
Epoch 12/70
13/13 [==============================] - 3s 248ms/step - loss: 0.2911 - acc: 0.8291 - val_loss: 0.3587 - val_acc: 0.7819
Epoch 13/70
13/13 [==============================] - 3s 256ms/step - loss: 0.2747 - acc: 0.8552 - val_loss: 0.3879 - val_acc: 0.7766
Epoch 14/70
13/13 [==============================] - 3s 254ms/step - loss: 0.2674 - acc: 0.8528 - val_loss: 0.3745 - val_acc: 0.7766

In [131]:
df_sentiment_train_pred = {}
df_sentiment_train_true_ = {}

df_sentiment_val_true_ = {}
df_sentiment_val_pred = {}

df_sentiment_test_true_ = {}
df_sentiment_test_pred = {}


for aspect in lst_aspect:
    pred_sentiment_train = sentiment_model_lgc[aspect].predict(padded_sentiment_train[aspect])
    pred_sentiment_val = sentiment_model_lgc[aspect].predict(padded_sentiment_val[aspect])
    pred_sentiment_test = sentiment_model_lgc[aspect].predict(padded_sentiment_test[aspect])
    
    df_sentiment_train_pred[aspect] = np.argmax(pred_sentiment_train, axis=1)
    df_sentiment_train_true_[aspect] = np.argmax(label_sentiment_train[aspect], axis = 1)
    
    df_sentiment_val_pred[aspect] = np.argmax(pred_sentiment_val, axis=1)
    df_sentiment_val_true_[aspect] = np.argmax(label_sentiment_val[aspect], axis = 1)
    
    df_sentiment_test_pred[aspect] = np.argmax(pred_sentiment_test, axis=1)
    df_sentiment_test_true_[aspect] = np.argmax(label_sentiment_test[aspect], axis=1)

40/40 [==============================] - 2s 27ms/step
5/5 [==============================] - 0s 24ms/step
11/11 [==============================] - 0s 25ms/step
79/79 [==============================] - 3s 25ms/step
10/10 [==============================] - 0s 25ms/step
23/23 [==============================] - 1s 25ms/step
143/143 [==============================] - 5s 25ms/step
16/16 [==============================] - 0s 25ms/step
40/40 [==============================] - 1s 25ms/step
79/79 [==============================] - 3s 25ms/step
9/9 [==============================] - 0s 25ms/step
22/22 [==============================] - 1s 25ms/step
45/45 [==============================] - 2s 25ms/step
5/5 [==============================] - 0s 24ms/step
13/13 [==============================] - 0s 25ms/step
70/70 [==============================] - 3s 25ms/step
8/8 [==============================] - 0s 25ms/step
19/19 [==============================] - 0s 25ms/step
52/52 [==============================] - 3s 25ms/step
6/6 [==============================] - 0s 25ms/step
15/15 [==============================] - 0s 25ms/step

In [132]:
def get_pd_report_sentiment(df_sentiment_test_true_, df_sentiment_test_pred):
    sentiment_result_bilstm = {}
    for aspect in lst_aspect:
        sentiment_result_bilstm[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
        sentiment_result_bilstm[aspect]['aspect'] = aspect

    output_sentiment_report = pd.DataFrame()
    for indx, val in sentiment_result_bilstm.items():
        output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

    return output_aspect_report

In [133]:
sentiment_result_bilstm = {}
# for aspect in lst_aspect:
for aspect in lst_aspect:
    sentiment_result_bilstm[aspect] = pd.DataFrame(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist(), output_dict=True)).T
    sentiment_result_bilstm[aspect]['aspect'] = aspect

output_sentiment_report = pd.DataFrame()
for indx, val in sentiment_result_bilstm.items():
    output_sentiment_report = pd.concat([output_sentiment_report, sentiment_result_bilstm[indx]])

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [134]:
output_sentiment_report

              precision    recall  f1-score      support       aspect
0              0.000000  0.000000  0.000000     3.000000        price
1              0.904382  0.919028  0.911647   247.000000        price
2              0.777778  0.769231  0.773481    91.000000        price
accuracy       0.870968  0.870968  0.870968     0.870968        price
macro avg      0.560720  0.562753  0.561709   341.000000        price
weighted avg   0.862640  0.870968  0.866755   341.000000        price
0              0.822695  0.935484  0.875472   124.000000     shipping
1              0.965517  0.969035  0.967273   549.000000     shipping
2              0.153846  0.062500  0.088889    32.000000     shipping
accuracy       0.921986  0.921986  0.921986     0.921986     shipping
macro avg      0.647353  0.655673  0.643878   705.000000     shipping
weighted avg   0.903555  0.921986  0.911256   705.000000     shipping
0              0.837838  0.652632  0.733728    95.000000      outlook
1              0.963556  0.969589  0.966563  1118.000000      outlook
2              0.277778  0.344828  0.307692    58.000000      outlook
accuracy       0.917388  0.917388  0.917388     0.917388      outlook
macro avg      0.693057  0.655683  0.669328  1271.000000      outlook
weighted avg   0.922865  0.917388  0.919093  1271.000000      outlook
0              0.752941  0.653061  0.699454    98.000000      quality
1              0.916143  0.914226  0.915183   478.000000      quality
2              0.479675  0.541284  0.508621   109.000000      quality
accuracy       0.817518  0.817518  0.817518     0.817518      quality
macro avg      0.716253  0.702857  0.707752   685.000000      quality
weighted avg   0.823342  0.817518  0.819626   685.000000      quality
0              0.685315  0.784000  0.731343   125.000000         size
1              0.926380  0.915152  0.920732   165.000000         size
2              0.654321  0.546392  0.595506    97.000000         size
accuracy       0.780362  0.780362  0.780362     0.780362         size
macro avg      0.755339  0.748514  0.749194   387.000000         size
weighted avg   0.780326  0.780362  0.778043   387.000000         size
0              0.797203  0.814286  0.805654   140.000000  shopservice
1              0.916300  0.965197  0.940113   431.000000  shopservice
2              0.333333  0.034483  0.062500    29.000000  shopservice
accuracy       0.885000  0.885000  0.885000     0.885000  shopservice
macro avg      0.682279  0.604655  0.602756   600.000000  shopservice
weighted avg   0.860334  0.885000  0.866321   600.000000  shopservice
0              0.000000  0.000000  0.000000    11.000000      general
1              0.808176  0.901754  0.852405   285.000000      general
2              0.793750  0.697802  0.742690   182.000000      general
accuracy       0.803347  0.803347  0.803347     0.803347      general
macro avg      0.533975  0.533186  0.531698   478.000000      general
weighted avg   0.784085  0.803347  0.791014   478.000000      general

In [135]:
for aspect in lst_aspect:
    print(aspect)
    print(classification_report(df_sentiment_test_true_[aspect].tolist(), df_sentiment_test_pred[aspect].tolist()))

price
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.90      0.92      0.91       247
           2       0.78      0.77      0.77        91

    accuracy                           0.87       341
   macro avg       0.56      0.56      0.56       341
weighted avg       0.86      0.87      0.87       341

shipping
              precision    recall  f1-score   support

           0       0.82      0.94      0.88       124
           1       0.97      0.97      0.97       549
           2       0.15      0.06      0.09        32

    accuracy                           0.92       705
   macro avg       0.65      0.66      0.64       705
weighted avg       0.90      0.92      0.91       705

outlook
              precision    recall  f1-score   support

           0       0.84      0.65      0.73        95
           1       0.96      0.97      0.97      1118
           2       0.28      0.34      0.31        58

    accuracy                           0.92      1271
   macro avg       0.69      0.66      0.67      1271
weighted avg       0.92      0.92      0.92      1271

quality
              precision    recall  f1-score   support

           0       0.75      0.65      0.70        98
           1       0.92      0.91      0.92       478
           2       0.48      0.54      0.51       109

    accuracy                           0.82       685
   macro avg       0.72      0.70      0.71       685
weighted avg       0.82      0.82      0.82       685

size
              precision    recall  f1-score   support

           0       0.69      0.78      0.73       125
           1       0.93      0.92      0.92       165
           2       0.65      0.55      0.60        97

    accuracy                           0.78       387
   macro avg       0.76      0.75      0.75       387
weighted avg       0.78      0.78      0.78       387

shopservice
              precision    recall  f1-score   support

           0       0.80      0.81      0.81       140
           1       0.92      0.97      0.94       431
           2       0.33      0.03      0.06        29

    accuracy                           0.89       600
   macro avg       0.68      0.60      0.60       600
weighted avg       0.86      0.89      0.87       600

general
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.81      0.90      0.85       285
           2       0.79      0.70      0.74       182

    accuracy                           0.80       478
   macro avg       0.53      0.53      0.53       478
weighted avg       0.78      0.80      0.79       478

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [136]:
for i in lst_aspect:
    with open(f'{path}elmo_bilstm_bigru_con_test_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_test_true_[i].tolist(), df_sentiment_test_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [137]:
for i in lst_aspect:
    with open(f'{path}elmo_bilstm_bigru_con_val_result.txt', "a") as dest:
        dest.write("Classification report for aspect: {} \n".format(i.upper()))
        dest.write(classification_report(df_sentiment_val_true_[i].tolist(), df_sentiment_val_pred[i].tolist()))

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

# VI. Overall Results

## 1. BiLSTM

In [138]:
pred_test = aspect_model_bil.predict(padded_aspect_test)
df_pred = round(pd.DataFrame(pred_test), 0)
df_true = label_aspect_test
df_pred.columns = df_true.columns

74/74 [==============================] - 1s 13ms/step

In [139]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [140]:
list_aspect = df_train.columns[1:9]
list_aspect

Index(['Price', 'Shipping', 'Outlook', 'Quality', 'Size', 'Shop_Service',
       'General', 'Others'],
      dtype='object')

In [141]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [142]:
aspect_test = []
aspect_pred = []

for row_test, row_pred in zip(y_true, y_pred):
    for index, (col_test, col_pred) in enumerate(zip(list(row_test), list(row_pred))):
        aspect_test.append(bool(col_test) * list_aspect[index])
        aspect_pred.append(bool(col_pred) * list_aspect[index])

## a) Aspect Detection

In [143]:
aspect_report = classification_report(aspect_test, aspect_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_test, aspect_pred, digits=4, zero_division=1))

              precision    recall  f1-score   support

                 0.9397    0.9561    0.9478     14062
     General     0.6476    0.6367    0.6421       479
      Others     0.8395    0.7196    0.7749       189
     Outlook     0.9359    0.8954    0.9152      1271
       Price     0.9046    0.6950    0.7861       341
     Quality     0.7878    0.8120    0.7997       686
    Shipping     0.9429    0.9362    0.9395       705
Shop_Service     0.8757    0.7517    0.8090       600
        Size     0.8206    0.8036    0.8120       387

    accuracy                         0.9209     18720
   macro avg     0.8549    0.8007    0.8251     18720
weighted avg     0.9203    0.9209    0.9201     18720

## b) Polarity Detection

In [144]:
y_sen_pred = []
y_sen_true = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_bil[aspect].predict(padded_sentiment_test[aspect])
    y_sen_pred.extend(list(np.argmax(pred_sentiment_test, axis=1)))
    y_sen_true.extend(list(np.argmax(label_sentiment_test[aspect], axis=1)))

11/11 [==============================] - 0s 13ms/step
23/23 [==============================] - 0s 13ms/step
40/40 [==============================] - 1s 13ms/step
22/22 [==============================] - 0s 13ms/step
13/13 [==============================] - 0s 13ms/step
19/19 [==============================] - 0s 13ms/step
15/15 [==============================] - 0s 13ms/step

In [145]:
replacements = {0: 'negative', 1: 'positive', 2: 'neutral'}

In [146]:
target_names = list(map(str, replacements.values()))
target_names

['negative', 'positive', 'neutral']

In [147]:
polarity_report = classification_report(y_sen_true, y_sen_pred, digits=4, output_dict=True)
print(classification_report(y_sen_true, y_sen_pred, target_names=target_names, digits=4))

              precision    recall  f1-score   support

    negative     0.7043    0.7433    0.7233       596
    positive     0.9183    0.9481    0.9330      3273
     neutral     0.6536    0.5017    0.5676       598

    accuracy                         0.8610      4467
   macro avg     0.7587    0.7310    0.7413      4467
weighted avg     0.8543    0.8610    0.8561      4467

## c) Aspect + Polarity

In [148]:
aspect_polarity_test = []
aspect_polarity_pred = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_bil[aspect].predict(padded_sentiment_test[aspect])
    pred_sentiment_test = list(np.argmax(pred_sentiment_test, axis=1))
    sen_test = list(np.argmax(label_sentiment_test[aspect], axis=1))
    for i in range(len(sen_test)):
        aspect_polarity_pred.append(f'{aspect},{replacements[pred_sentiment_test[i]]}')
        aspect_polarity_test.append(f'{aspect},{replacements[sen_test[i]]}')

11/11 [==============================] - 0s 13ms/step
23/23 [==============================] - 0s 13ms/step
40/40 [==============================] - 1s 13ms/step
22/22 [==============================] - 0s 13ms/step
13/13 [==============================] - 0s 13ms/step
19/19 [==============================] - 0s 13ms/step
15/15 [==============================] - 0s 13ms/step

In [149]:
aspect_polarity_report = classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1))

                      precision    recall  f1-score   support

    general,negative     1.0000    0.0000    0.0000        11
     general,neutral     0.7840    0.6978    0.7384       182
    general,positive     0.8101    0.8982    0.8519       285
    outlook,negative     0.7571    0.5579    0.6424        95
     outlook,neutral     0.4400    0.1897    0.2651        58
    outlook,positive     0.9396    0.9884    0.9634      1118
      price,negative     1.0000    0.0000    0.0000         3
       price,neutral     0.7315    0.8681    0.7940        91
      price,positive     0.9442    0.8907    0.9167       247
    quality,negative     0.7500    0.5816    0.6552        98
     quality,neutral     0.5806    0.4954    0.5347       109
    quality,positive     0.8760    0.9456    0.9095       478
   shipping,negative     0.8346    0.8952    0.8638       124
    shipping,neutral     0.0909    0.0625    0.0741        32
   shipping,positive     0.9618    0.9636    0.9627       549
shopservice,negative     0.6704    0.8571    0.7524       140
 shopservice,neutral     1.0000    0.0000    0.0000        29
shopservice,positive     0.9287    0.9072    0.9178       431
       size,negative     0.5965    0.8160    0.6892       125
        size,neutral     0.5510    0.2784    0.3699        97
       size,positive     0.8982    0.9091    0.9036       165

            accuracy                         0.8610      4467
           macro avg     0.7688    0.6096    0.6097      4467
        weighted avg     0.8562    0.8610    0.8499      4467

## d) Overall

In [151]:
aspect_dict = aspect_report['macro avg']
aspect_dict['accuracy'] = aspect_report['accuracy']

polarity_dict  = polarity_report['macro avg']
polarity_dict['accuracy'] = polarity_report['accuracy']

aspect_polarity_dict = aspect_polarity_report['macro avg']
aspect_polarity_dict['accuracy'] = aspect_polarity_report['accuracy']

In [152]:
df_report_bi = pd.DataFrame.from_dict([aspect_dict, polarity_dict, aspect_polarity_dict])
df_report_bi.index = ['Aspect Detection', 'Polarity Detection', 'Aspect + Polarity']
df_report_bi = df_report_bi.drop('support', axis=1)

## 2. BiGRU

In [153]:
pred_test = aspect_model_gru.predict(padded_aspect_test)
df_pred = round(pd.DataFrame(pred_test), 0)
df_true = label_aspect_test
df_pred.columns = df_true.columns

74/74 [==============================] - 1s 13ms/step

In [154]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [155]:
list_aspect = df_train.columns[1:9]
list_aspect

Index(['Price', 'Shipping', 'Outlook', 'Quality', 'Size', 'Shop_Service',
       'General', 'Others'],
      dtype='object')

In [156]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [157]:
aspect_test = []
aspect_pred = []

for row_test, row_pred in zip(y_true, y_pred):
    for index, (col_test, col_pred) in enumerate(zip(list(row_test), list(row_pred))):
        aspect_test.append(bool(col_test) * list_aspect[index])
        aspect_pred.append(bool(col_pred) * list_aspect[index])

## a) Aspect Detection

In [158]:
aspect_report = classification_report(aspect_test, aspect_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_test, aspect_pred, digits=4, zero_division=1))

              precision    recall  f1-score   support

                 0.9453    0.9602    0.9527     14062
     General     0.7444    0.5595    0.6389       479
      Others     0.8161    0.7513    0.7824       189
     Outlook     0.9302    0.9221    0.9261      1271
       Price     0.8836    0.7566    0.8152       341
     Quality     0.8213    0.8105    0.8158       686
    Shipping     0.9435    0.9475    0.9455       705
Shop_Service     0.8590    0.7917    0.8239       600
        Size     0.8180    0.8708    0.8436       387

    accuracy                         0.9283     18720
   macro avg     0.8624    0.8189    0.8382     18720
weighted avg     0.9267    0.9283    0.9269     18720

## b) Polarity Detection

In [214]:
y_sen_pred = []
y_sen_true = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_gru[aspect].predict(padded_sentiment_test[aspect])
    y_sen_pred.extend(list(np.argmax(pred_sentiment_test, axis=1)))
    y_sen_true.extend(list(np.argmax(label_sentiment_test[aspect], axis=1)))

11/11 [==============================] - 0s 21ms/step
23/23 [==============================] - 0s 11ms/step
40/40 [==============================] - 0s 11ms/step
22/22 [==============================] - 0s 11ms/step
13/13 [==============================] - 0s 11ms/step
19/19 [==============================] - 0s 11ms/step
15/15 [==============================] - 0s 11ms/step

In [215]:
replacements = {0: 'negative', 1: 'positive', 2: 'neutral'}

In [216]:
target_names = list(map(str, replacements.values()))
target_names

['negative', 'positive', 'neutral']

In [217]:
polarity_report = classification_report(y_sen_true, y_sen_pred, digits=4, output_dict=True)
print(classification_report(y_sen_true, y_sen_pred, target_names=target_names, digits=4))

              precision    recall  f1-score   support

    negative     0.7268    0.7500    0.7382       596
    positive     0.9159    0.9514    0.9333      3273
     neutral     0.6283    0.4749    0.5410       598

    accuracy                         0.8608      4467
   macro avg     0.7570    0.7254    0.7375      4467
weighted avg     0.8522    0.8608    0.8548      4467

## c) Aspect + Polarity

In [218]:
aspect_polarity_test = []
aspect_polarity_pred = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_gru[aspect].predict(padded_sentiment_test[aspect])
    pred_sentiment_test = list(np.argmax(pred_sentiment_test, axis=1))
    sen_test = list(np.argmax(label_sentiment_test[aspect], axis=1))
    for i in range(len(sen_test)):
        aspect_polarity_pred.append(f'{aspect},{replacements[pred_sentiment_test[i]]}')
        aspect_polarity_test.append(f'{aspect},{replacements[sen_test[i]]}')

11/11 [==============================] - 0s 21ms/step
23/23 [==============================] - 0s 11ms/step
40/40 [==============================] - 0s 11ms/step
22/22 [==============================] - 0s 11ms/step
13/13 [==============================] - 0s 11ms/step
19/19 [==============================] - 0s 11ms/step
15/15 [==============================] - 0s 11ms/step

In [219]:
aspect_polarity_report = classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1))

                      precision    recall  f1-score   support

    general,negative     1.0000    0.0000    0.0000        11
     general,neutral     0.7843    0.6593    0.7164       182
    general,positive     0.7908    0.9018    0.8426       285
    outlook,negative     0.6981    0.7789    0.7363        95
     outlook,neutral     0.2963    0.2759    0.2857        58
    outlook,positive     0.9703    0.9642    0.9672      1118
      price,negative     1.0000    0.0000    0.0000         3
       price,neutral     0.7692    0.7692    0.7692        91
      price,positive     0.9040    0.9150    0.9095       247
    quality,negative     0.6500    0.5306    0.5843        98
     quality,neutral     0.5000    0.3303    0.3978       109
    quality,positive     0.8537    0.9519    0.9001       478
   shipping,negative     0.7959    0.9435    0.8635       124
    shipping,neutral     0.0000    0.0000    0.0000        32
   shipping,positive     0.9586    0.9709    0.9647       549
shopservice,negative     0.7625    0.8714    0.8133       140
 shopservice,neutral     1.0000    0.0000    0.0000        29
shopservice,positive     0.9295    0.9490    0.9392       431
       size,negative     0.6721    0.6560    0.6640       125
        size,neutral     0.5250    0.4330    0.4746        97
       size,positive     0.8432    0.9455    0.8914       165

            accuracy                         0.8608      4467
           macro avg     0.7478    0.6117    0.6057      4467
        weighted avg     0.8519    0.8608    0.8497      4467

## d) Overall

In [220]:
aspect_dict = aspect_report['macro avg']
aspect_dict['accuracy'] = aspect_report['accuracy']

polarity_dict  = polarity_report['macro avg']
polarity_dict['accuracy'] = polarity_report['accuracy']

aspect_polarity_dict = aspect_polarity_report['macro avg']
aspect_polarity_dict['accuracy'] = aspect_polarity_report['accuracy']

In [221]:
df_report_gru = pd.DataFrame.from_dict([aspect_dict, polarity_dict, aspect_polarity_dict])
df_report_gru.index = ['Aspect Detection', 'Polarity Detection', 'Aspect + Polarity']
df_report_gru = df_report_gru.drop('support', axis=1)

## 3. BiLSTM + Conv1D

In [168]:
pred_test = aspect_model_bil_con.predict(padded_aspect_test)
df_pred = round(pd.DataFrame(pred_test), 0)
df_true = label_aspect_test
df_pred.columns = df_true.columns

74/74 [==============================] - 1s 16ms/step

In [169]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [170]:
list_aspect = df_train.columns[1:9]
list_aspect

Index(['Price', 'Shipping', 'Outlook', 'Quality', 'Size', 'Shop_Service',
       'General', 'Others'],
      dtype='object')

In [171]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [172]:
aspect_test = []
aspect_pred = []

for row_test, row_pred in zip(y_true, y_pred):
    for index, (col_test, col_pred) in enumerate(zip(list(row_test), list(row_pred))):
        aspect_test.append(bool(col_test) * list_aspect[index])
        aspect_pred.append(bool(col_pred) * list_aspect[index])

## a) Aspect Detection

In [173]:
aspect_report = classification_report(aspect_test, aspect_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_test, aspect_pred, digits=4, zero_division=1))

              precision    recall  f1-score   support

                 0.9488    0.9597    0.9543     14062
     General     0.7214    0.6054    0.6583       479
      Others     0.8750    0.6667    0.7568       189
     Outlook     0.8985    0.9607    0.9285      1271
       Price     0.8854    0.7478    0.8108       341
     Quality     0.8333    0.7945    0.8134       686
    Shipping     0.9415    0.9589    0.9501       705
Shop_Service     0.8926    0.8033    0.8456       600
        Size     0.8568    0.8656    0.8612       387

    accuracy                         0.9309     18720
   macro avg     0.8726    0.8181    0.8421     18720
weighted avg     0.9295    0.9309    0.9296     18720

## b) Polarity Detection

In [222]:
y_sen_pred = []
y_sen_true = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_bil_con[aspect].predict(padded_sentiment_test[aspect])
    y_sen_pred.extend(list(np.argmax(pred_sentiment_test, axis=1)))
    y_sen_true.extend(list(np.argmax(label_sentiment_test[aspect], axis=1)))

11/11 [==============================] - 0s 22ms/step
23/23 [==============================] - 0s 14ms/step
40/40 [==============================] - 1s 14ms/step
22/22 [==============================] - 0s 14ms/step
13/13 [==============================] - 0s 14ms/step
19/19 [==============================] - 0s 14ms/step
15/15 [==============================] - 0s 13ms/step

In [223]:
replacements = {0: 'negative', 1: 'positive', 2: 'neutral'}

In [224]:
target_names = list(map(str, replacements.values()))
target_names

['negative', 'positive', 'neutral']

In [226]:
polarity_report = classification_report(y_sen_true, y_sen_pred, digits=4, output_dict=True)
print(classification_report(y_sen_true, y_sen_pred, target_names=target_names, digits=4))

              precision    recall  f1-score   support

    negative     0.7305    0.7869    0.7577       596
    positive     0.9331    0.9496    0.9412      3273
     neutral     0.6397    0.5284    0.5788       598

    accuracy                         0.8715      4467
   macro avg     0.7678    0.7550    0.7592      4467
weighted avg     0.8668    0.8715    0.8682      4467

## c) Aspect + Polarity

In [227]:
aspect_polarity_test = []
aspect_polarity_pred = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_bil_con[aspect].predict(padded_sentiment_test[aspect])
    pred_sentiment_test = list(np.argmax(pred_sentiment_test, axis=1))
    sen_test = list(np.argmax(label_sentiment_test[aspect], axis=1))
    for i in range(len(sen_test)):
        aspect_polarity_pred.append(f'{aspect},{replacements[pred_sentiment_test[i]]}')
        aspect_polarity_test.append(f'{aspect},{replacements[sen_test[i]]}')

11/11 [==============================] - 0s 26ms/step
23/23 [==============================] - 0s 14ms/step
40/40 [==============================] - 1s 14ms/step
22/22 [==============================] - 0s 14ms/step
13/13 [==============================] - 0s 14ms/step
19/19 [==============================] - 0s 14ms/step
15/15 [==============================] - 0s 13ms/step

In [228]:
aspect_polarity_report = classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1))

                      precision    recall  f1-score   support

    general,negative     1.0000    0.0000    0.0000        11
     general,neutral     0.8141    0.6978    0.7515       182
    general,positive     0.8168    0.9228    0.8666       285
    outlook,negative     0.7374    0.7684    0.7526        95
     outlook,neutral     0.3800    0.3276    0.3519        58
    outlook,positive     0.9661    0.9696    0.9679      1118
      price,negative     1.0000    0.0000    0.0000         3
       price,neutral     0.7087    0.8022    0.7526        91
      price,positive     0.9202    0.8866    0.9031       247
    quality,negative     0.7375    0.6020    0.6629        98
     quality,neutral     0.4769    0.5688    0.5188       109
    quality,positive     0.9200    0.9142    0.9171       478
   shipping,negative     0.8085    0.9194    0.8604       124
    shipping,neutral     0.2000    0.0312    0.0541        32
   shipping,positive     0.9589    0.9763    0.9675       549
shopservice,negative     0.7838    0.8286    0.8056       140
 shopservice,neutral     0.5000    0.0345    0.0645        29
shopservice,positive     0.9222    0.9629    0.9421       431
       size,negative     0.6149    0.8560    0.7157       125
        size,neutral     0.6875    0.3402    0.4552        97
       size,positive     0.9333    0.9333    0.9333       165

            accuracy                         0.8715      4467
           macro avg     0.7565    0.6354    0.6306      4467
        weighted avg     0.8675    0.8715    0.8635      4467

## d) Overall

In [229]:
aspect_dict = aspect_report['macro avg']
aspect_dict['accuracy'] = aspect_report['accuracy']

polarity_dict  = polarity_report['macro avg']
polarity_dict['accuracy'] = polarity_report['accuracy']

aspect_polarity_dict = aspect_polarity_report['macro avg']
aspect_polarity_dict['accuracy'] = aspect_polarity_report['accuracy']

In [230]:
df_report_bil_con = pd.DataFrame.from_dict([aspect_dict, polarity_dict, aspect_polarity_dict])
df_report_bil_con.index = ['Aspect Detection', 'Polarity Detection', 'Aspect + Polarity']
df_report_bil_con = df_report_bil_con.drop('support', axis=1)

## 4. BiGRU + Conv1D

In [231]:
pred_test = aspect_model_big_con.predict(padded_aspect_test)
df_pred = round(pd.DataFrame(pred_test), 0)
df_true = label_aspect_test
df_pred.columns = df_true.columns

74/74 [==============================] - 1s 13ms/step

In [232]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [233]:
list_aspect = df_train.columns[1:9]
list_aspect

Index(['Price', 'Shipping', 'Outlook', 'Quality', 'Size', 'Shop_Service',
       'General', 'Others'],
      dtype='object')

In [234]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [235]:
aspect_test = []
aspect_pred = []

for row_test, row_pred in zip(y_true, y_pred):
    for index, (col_test, col_pred) in enumerate(zip(list(row_test), list(row_pred))):
        aspect_test.append(bool(col_test) * list_aspect[index])
        aspect_pred.append(bool(col_pred) * list_aspect[index])

## a) Aspect Detection

In [236]:
aspect_report = classification_report(aspect_test, aspect_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_test, aspect_pred, digits=4, zero_division=1))

              precision    recall  f1-score   support

                 0.9499    0.9610    0.9554     14062
     General     0.7453    0.5804    0.6526       479
      Others     0.8503    0.7513    0.7978       189
     Outlook     0.9440    0.9158    0.9297      1271
       Price     0.8914    0.7947    0.8403       341
     Quality     0.8088    0.8265    0.8176       686
    Shipping     0.9322    0.9560    0.9440       705
Shop_Service     0.8761    0.8367    0.8559       600
        Size     0.8262    0.8966    0.8600       387

    accuracy                         0.9326     18720
   macro avg     0.8694    0.8355    0.8504     18720
weighted avg     0.9314    0.9326    0.9316     18720

## b) Polarity Detection

In [237]:
y_sen_pred = []
y_sen_true = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_big_con[aspect].predict(padded_sentiment_test[aspect])
    y_sen_pred.extend(list(np.argmax(pred_sentiment_test, axis=1)))
    y_sen_true.extend(list(np.argmax(label_sentiment_test[aspect], axis=1)))

11/11 [==============================] - 0s 22ms/step
23/23 [==============================] - 0s 12ms/step
40/40 [==============================] - 0s 12ms/step
22/22 [==============================] - 0s 12ms/step
13/13 [==============================] - 0s 12ms/step
19/19 [==============================] - 0s 12ms/step
15/15 [==============================] - 0s 12ms/step

In [238]:
replacements = {0: 'negative', 1: 'positive', 2: 'neutral'}

In [239]:
target_names = list(map(str, replacements.values()))
target_names

['negative', 'positive', 'neutral']

In [240]:
polarity_report = classification_report(y_sen_true, y_sen_pred, digits=4, output_dict=True)
print(classification_report(y_sen_true, y_sen_pred, target_names=target_names, digits=4))

              precision    recall  f1-score   support

    negative     0.7600    0.7970    0.7781       596
    positive     0.9378    0.9493    0.9435      3273
     neutral     0.6371    0.5635    0.5980       598

    accuracy                         0.8773      4467
   macro avg     0.7783    0.7699    0.7732      4467
weighted avg     0.8738    0.8773    0.8752      4467

## c) Aspect + Polarity

In [241]:
aspect_polarity_test = []
aspect_polarity_pred = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_big_con[aspect].predict(padded_sentiment_test[aspect])
    pred_sentiment_test = list(np.argmax(pred_sentiment_test, axis=1))
    sen_test = list(np.argmax(label_sentiment_test[aspect], axis=1))
    for i in range(len(sen_test)):
        aspect_polarity_pred.append(f'{aspect},{replacements[pred_sentiment_test[i]]}')
        aspect_polarity_test.append(f'{aspect},{replacements[sen_test[i]]}')

11/11 [==============================] - 0s 21ms/step
23/23 [==============================] - 0s 12ms/step
40/40 [==============================] - 0s 12ms/step
22/22 [==============================] - 0s 12ms/step
13/13 [==============================] - 0s 12ms/step
19/19 [==============================] - 0s 12ms/step
15/15 [==============================] - 0s 12ms/step

In [242]:
aspect_polarity_report = classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1))

                      precision    recall  f1-score   support

    general,negative     1.0000    0.0000    0.0000        11
     general,neutral     0.7831    0.7143    0.7471       182
    general,positive     0.8173    0.8947    0.8543       285
    outlook,negative     0.7451    0.8000    0.7716        95
     outlook,neutral     0.3393    0.3276    0.3333        58
    outlook,positive     0.9695    0.9651    0.9673      1118
      price,negative     1.0000    0.0000    0.0000         3
       price,neutral     0.7576    0.8242    0.7895        91
      price,positive     0.9256    0.9069    0.9162       247
    quality,negative     0.7614    0.6837    0.7204        98
     quality,neutral     0.5167    0.5688    0.5415       109
    quality,positive     0.9224    0.9205    0.9215       478
   shipping,negative     0.8310    0.9516    0.8872       124
    shipping,neutral     0.0000    0.0000    0.0000        32
   shipping,positive     0.9625    0.9818    0.9720       549
shopservice,negative     0.7959    0.8357    0.8153       140
 shopservice,neutral     0.3636    0.1379    0.2000        29
shopservice,positive     0.9412    0.9652    0.9530       431
       size,negative     0.6644    0.7760    0.7159       125
        size,neutral     0.6351    0.4845    0.5497        97
       size,positive     0.9222    0.9333    0.9277       165

            accuracy                         0.8773      4467
           macro avg     0.7454    0.6510    0.6468      4467
        weighted avg     0.8706    0.8773    0.8713      4467

## d) Overall

In [243]:
aspect_dict = aspect_report['macro avg']
aspect_dict['accuracy'] = aspect_report['accuracy']

polarity_dict  = polarity_report['macro avg']
polarity_dict['accuracy'] = polarity_report['accuracy']

aspect_polarity_dict = aspect_polarity_report['macro avg']
aspect_polarity_dict['accuracy'] = aspect_polarity_report['accuracy']

In [244]:
df_report_big_con = pd.DataFrame.from_dict([aspect_dict, polarity_dict, aspect_polarity_dict])
df_report_big_con.index = ['Aspect Detection', 'Polarity Detection', 'Aspect + Polarity']
df_report_big_con = df_report_big_con.drop('support', axis=1)

## 5. BiLSTM + BiGRU + Conv1D

In [245]:
pred_test = aspect_model_lgc.predict(padded_aspect_test)
df_pred = round(pd.DataFrame(pred_test), 0)
df_true = label_aspect_test
df_pred.columns = df_true.columns

74/74 [==============================] - 2s 27ms/step

In [246]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [247]:
list_aspect = df_train.columns[1:9]
list_aspect

Index(['Price', 'Shipping', 'Outlook', 'Quality', 'Size', 'Shop_Service',
       'General', 'Others'],
      dtype='object')

In [248]:
y_pred = []
y_true = []
for i in range(len(df_true)):
    y_pred.append(list(df_pred.loc[i]))
    y_true.append(list(df_true.loc[i]))

In [249]:
aspect_test = []
aspect_pred = []

for row_test, row_pred in zip(y_true, y_pred):
    for index, (col_test, col_pred) in enumerate(zip(list(row_test), list(row_pred))):
        aspect_test.append(bool(col_test) * list_aspect[index])
        aspect_pred.append(bool(col_pred) * list_aspect[index])

## a) Aspect Detection

In [250]:
aspect_report = classification_report(aspect_test, aspect_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_test, aspect_pred, digits=4, zero_division=1))

              precision    recall  f1-score   support

                 0.9455    0.9628    0.9541     14062
     General     0.7435    0.5992    0.6636       479
      Others     0.8249    0.7725    0.7978       189
     Outlook     0.9319    0.9158    0.9238      1271
       Price     0.8972    0.7419    0.8122       341
     Quality     0.8216    0.7988    0.8101       686
    Shipping     0.9413    0.9560    0.9486       705
Shop_Service     0.8989    0.7850    0.8381       600
        Size     0.8375    0.8656    0.8513       387

    accuracy                         0.9304     18720
   macro avg     0.8714    0.8220    0.8444     18720
weighted avg     0.9289    0.9304    0.9291     18720

## b) Polarity Detection

In [251]:
y_sen_pred = []
y_sen_true = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_lgc[aspect].predict(padded_sentiment_test[aspect])
    y_sen_pred.extend(list(np.argmax(pred_sentiment_test, axis=1)))
    y_sen_true.extend(list(np.argmax(label_sentiment_test[aspect], axis=1)))

11/11 [==============================] - 0s 34ms/step
23/23 [==============================] - 1s 25ms/step
40/40 [==============================] - 1s 25ms/step
22/22 [==============================] - 1s 25ms/step
13/13 [==============================] - 0s 25ms/step
19/19 [==============================] - 0s 25ms/step
15/15 [==============================] - 0s 25ms/step

In [252]:
replacements = {0: 'negative', 1: 'positive', 2: 'neutral'}

In [253]:
target_names = list(map(str, replacements.values()))
target_names

['negative', 'positive', 'neutral']

In [254]:
polarity_report = classification_report(y_sen_true, y_sen_pred, digits=4, output_dict=True)
print(classification_report(y_sen_true, y_sen_pred, target_names=target_names, digits=4))

              precision    recall  f1-score   support

    negative     0.7747    0.7617    0.7682       596
    positive     0.9296    0.9484    0.9389      3273
     neutral     0.6125    0.5552    0.5825       598

    accuracy                         0.8708      4467
   macro avg     0.7723    0.7551    0.7632      4467
weighted avg     0.8665    0.8708    0.8684      4467

## c) Aspect + Polarity

In [255]:
aspect_polarity_test = []
aspect_polarity_pred = []

for aspect in lst_aspect:
    pred_sentiment_test = sentiment_model_lgc[aspect].predict(padded_sentiment_test[aspect])
    pred_sentiment_test = list(np.argmax(pred_sentiment_test, axis=1))
    sen_test = list(np.argmax(label_sentiment_test[aspect], axis=1))
    for i in range(len(sen_test)):
        aspect_polarity_pred.append(f'{aspect},{replacements[pred_sentiment_test[i]]}')
        aspect_polarity_test.append(f'{aspect},{replacements[sen_test[i]]}')

11/11 [==============================] - 0s 38ms/step
23/23 [==============================] - 1s 25ms/step
40/40 [==============================] - 1s 25ms/step
22/22 [==============================] - 1s 25ms/step
13/13 [==============================] - 0s 25ms/step
19/19 [==============================] - 0s 25ms/step
15/15 [==============================] - 0s 25ms/step

In [256]:
aspect_polarity_report = classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1, output_dict=True)
print(classification_report(aspect_polarity_test, aspect_polarity_pred, digits=4, zero_division=1))

                      precision    recall  f1-score   support

    general,negative     1.0000    0.0000    0.0000        11
     general,neutral     0.7937    0.6978    0.7427       182
    general,positive     0.8082    0.9018    0.8524       285
    outlook,negative     0.8378    0.6526    0.7337        95
     outlook,neutral     0.2778    0.3448    0.3077        58
    outlook,positive     0.9636    0.9696    0.9666      1118
      price,negative     1.0000    0.0000    0.0000         3
       price,neutral     0.7778    0.7692    0.7735        91
      price,positive     0.9044    0.9190    0.9116       247
    quality,negative     0.7529    0.6531    0.6995        98
     quality,neutral     0.4797    0.5413    0.5086       109
    quality,positive     0.9161    0.9142    0.9152       478
   shipping,negative     0.8227    0.9355    0.8755       124
    shipping,neutral     0.1538    0.0625    0.0889        32
   shipping,positive     0.9655    0.9690    0.9673       549
shopservice,negative     0.7972    0.8143    0.8057       140
 shopservice,neutral     0.3333    0.0345    0.0625        29
shopservice,positive     0.9163    0.9652    0.9401       431
       size,negative     0.6853    0.7840    0.7313       125
        size,neutral     0.6543    0.5464    0.5955        97
       size,positive     0.9264    0.9152    0.9207       165

            accuracy                         0.8708      4467
           macro avg     0.7508    0.6376    0.6380      4467
        weighted avg     0.8675    0.8708    0.8656      4467

## d) Overall

In [257]:
aspect_dict = aspect_report['macro avg']
aspect_dict['accuracy'] = aspect_report['accuracy']

polarity_dict  = polarity_report['macro avg']
polarity_dict['accuracy'] = polarity_report['accuracy']

aspect_polarity_dict = aspect_polarity_report['macro avg']
aspect_polarity_dict['accuracy'] = aspect_polarity_report['accuracy']

In [258]:
df_report_lgc = pd.DataFrame.from_dict([aspect_dict, polarity_dict, aspect_polarity_dict])
df_report_lgc.index = ['Aspect Detection', 'Polarity Detection', 'Aspect + Polarity']
df_report_lgc = df_report_lgc.drop('support', axis=1)

In [259]:
res_all = [df_report_bi, df_report_gru, df_report_bil_con, df_report_big_con, df_report_lgc]
model_names = ['BiLSTM', 'BiGRU', 'BiLSTM + Conv1D', 'BiGRU + Conv1D', 'BiLSTM + BiGRU + Conv1D']
for i in range(len(res_all)):
    print(model_names[i])
    print(res_all[i])
    print('-' * 60)

BiLSTM
                    precision    recall  f1-score  accuracy
Aspect Detection     0.854910  0.800691  0.825143  0.920940
Polarity Detection   0.758735  0.731007  0.741287  0.860981
Aspect + Polarity    0.768824  0.609640  0.609739  0.860981
------------------------------------------------------------
BiGRU
                    precision    recall  f1-score  accuracy
Aspect Detection     0.871367  0.821967  0.844399  0.930395
Polarity Detection   0.757010  0.725446  0.737500  0.860757
Aspect + Polarity    0.747793  0.611730  0.605705  0.860757
------------------------------------------------------------
BiLSTM + Conv1D
                    precision    recall  f1-score  accuracy
Aspect Detection     0.871367  0.821967  0.844399  0.930395
Polarity Detection   0.767753  0.754976  0.759225  0.871502
Aspect + Polarity    0.756517  0.635358  0.630628  0.871502
------------------------------------------------------------
BiGRU + Conv1D
                    precision    recall  f1-score  accuracy
Aspect Detection     0.869370  0.835451  0.850357  0.932585
Polarity Detection   0.778291  0.769936  0.773205  0.877323
Aspect + Polarity    0.745420  0.651042  0.646834  0.877323
------------------------------------------------------------
BiLSTM + BiGRU + Conv1D
                    precision    recall  f1-score  accuracy
Aspect Detection     0.871367  0.821967  0.844399  0.930395
Polarity Detection   0.772303  0.755098  0.763182  0.870831
Aspect + Polarity    0.750806  0.637617  0.638045  0.870831
------------------------------------------------------------

In [260]:
import zipfile
import os
from IPython.display import FileLink

def zip_dir(directory = os.curdir, file_name = 'directory.zip'):
    """
    zip all the files in a directory
    
    Parameters
    _____
    directory: str
        directory needs to be zipped, defualt is current working directory
        
    file_name: str
        the name of the zipped file (including .zip), default is 'directory.zip'
        
    Returns
    _____
    Creates a hyperlink, which can be used to download the zip file)
    """
    os.chdir(directory)
    zip_ref = zipfile.ZipFile(file_name, mode='w')
    for folder, _, files in os.walk(directory):
        for file in files:
            if file_name in file:
                pass
            else:
                zip_ref.write(os.path.join(folder, file))

    return FileLink(file_name)

In [261]:
zip_dir()

/kaggle/working/directory.zip